### ISSUE TITLE
USB reenumeration bug

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#1005]
I unplugged my UHK from the USB port, and this is what the log showed:

```
[22:25:36.588] [debug] [UhkHidDevice] USB[W]: 09 
[22:25:36.596] [debug] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[22:25:36.858] [debug] [UhkHidDevice] USB[W]: 09 
[22:25:36.864] [debug] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[22:25:37.124] [debug] [UhkHidDevice] USB[W]: 09 
[22:25:37.132] [debug] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[22:25:37.682] [info] [DeviceService] Device connection state changed to: { bootloaderActive: false,
  connected: true,
  zeroInterfaceAvailable: false,
  hasPermission: true,
  udevRulesInfo: 'Ok',
  halvesInfo: { areHalvesMerged: true, isLeftHalfConnected: true } }
[22:25:37.705] [info] [ '[DeviceRendererService] dispatch action',
  '{"payload":{"bootloaderActive":false,"connected":true,"halvesInfo":{"areHalvesMerged":true,"isLeftHalfConnected":true},"hasPermission":true,"udevRulesInfo":"Ok","zeroInterfaceAvailable":false},"type":"[device] connection state changed"}' ]
[22:25:37.937] [info] [DeviceService] Device connection state changed to: { bootloaderActive: false,
  connected: false,
  zeroInterfaceAvailable: false,
  hasPermission: true,
  udevRulesInfo: 'Ok',
  halvesInfo: { areHalvesMerged: true, isLeftHalfConnected: true } }
[22:25:37.937] [info] [ '[DeviceRendererService] dispatch action',
  '{"payload":{"bootloaderActive":false,"connected":false,"halvesInfo":{"areHalvesMerged":true,"isLeftHalfConnected":true},"hasPermission":true,"udevRulesInfo":"Ok","zeroInterfaceAvailable":false},"type":"[device] connection state changed"}' ]
```

Then I replugged it:

```
[22:25:57.676] [debug] [UhkHidDevice] Available devices unchanged
[22:25:57.676] [error] [UhkHidDevice] Can not create device: Error: cannot open device with path /dev/hidraw6
    at new HID (/home/laci/projects/agent/packages/uhk-agent/dist/node_modules/node-hid/nodehid.js:54:17)
    at t.UhkHidDevice.connectToDevice (/home/laci/projects/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:281:1)
    at t.UhkHidDevice.getDevice (/home/laci/projects/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:249:1)
    at Promise (/home/laci/projects/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:105:1)
    at new Promise (<anonymous>)
    at t.UhkHidDevice.<anonymous> (/home/laci/projects/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:104:1)
    at Generator.next (<anonymous>)
    at /home/laci/projects/agent/packages/uhk-agent/dist/webpack:/uhk-usb/node_modules/tslib/tslib.es6.js:73:1
    at new Promise (<anonymous>)
    at Module.l (/home/laci/projects/agent/packages/uhk-agent/dist/webpack:/uhk-usb/node_modules/tslib/tslib.es6.js:69:1)

[22:25:58.065] [error] [DeviceService] UHK Device poller error Error: [UhkHidDevice] Device is not connected
    at Promise (/home/laci/projects/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:107:1)
    at new Promise (<anonymous>)
    at t.UhkHidDevice.<anonymous> (/home/laci/projects/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:104:1)
    at Generator.next (<anonymous>)
    at /home/laci/projects/agent/packages/uhk-agent/dist/webpack:/uhk-usb/node_modules/tslib/tslib.es6.js:73:1
    at new Promise (<anonymous>)
    at Module.l (/home/laci/projects/agent/packages/uhk-agent/dist/webpack:/uhk-usb/node_modules/tslib/tslib.es6.js:69:1)
    at t.UhkHidDevice.write (/home/laci/projects/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:103:1)
    at t.UhkHidDevice.<anonymous> (/home/laci/projects/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:235:1)
    at Generator.next (<anonymous>)

```

The "Cannot find your UHK! Please plug it in!" screen is visible, even tough my UHK is connected via USB.

**Comment by ert78gb** [comment]
Is it a permanent error? Because of the node-hid [connection](https://github.com/UltimateHackingKeyboard/agent/blob/4d2d6d40fbb2b3b2d23cf14d88fa057870e929e3/packages/uhk-usb/src/uhk-hid-device.ts#L316) throw the error

it looks like the device available in the devices list but after when the agent tries to connect:
- it is not available
- refuse the connection

**Comment by mondalaci** [comment]
Yes, I can always reproduce this issue on Linux.

**Comment by mondalaci** [comment]
This issue has been fixed by a previous commit.
