### ISSUE TITLE
Error updating Firmware to 8.6.0

### ISSUE THREAD

**Issue by FatBoyXPC** [UltimateHackingKeyboard/agent#1047]
I'm on Arch Linux so Karabiner is irrelevant to me. I'm running the latest agent (super awesome that you included contributors on the about page, btw!). I've got the keyboard together rather than split. I can reproduce this issue consistently.

Here's an output of the firmware console:

```

Start flashing firmware
[09:44:45.589] Agent version: 1.2.13
[09:44:45.590] [UhkHidDevice] USB[W]: 09
[09:44:45.598] [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[09:44:45.598] [DeviceOperation] USB[T]: Read left module version information
[09:44:45.599] [UhkHidDevice] USB[W]: 0e 01 00
[09:44:45.606] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[09:44:45.607] [DeviceOperation] USB[T]: Read right module version information
[09:44:45.607] [UhkHidDevice] USB[W]: 00 01
[09:44:45.614] [UhkHidDevice] USB[R]: 00 08 00 00 00 00 00 04 00 01 00 00 00 04 00 00 00 00 00 04 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[09:44:45.614] Device right firmware version: 8.0.0
[09:44:45.615] Device left firmware version: 8.0.0
[09:44:45.618] New firmware version: 8.6.0
[09:44:45.620] [UhkOperations] Operating system: Linux 5.3.1-arch1-1-ARCH x64
[09:44:45.620] [UhkOperations] Start flashing right firmware
[09:44:45.620] [UhkHidDevice] Start reenumeration, mode: Bootloader
[09:44:45.623] [UhkHidDevice] reenumeration devices [ { vendorId: 7504, productId: 24866, path: '/dev/hidraw0', serialNumber: '', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 0, usagePage: 14898, usage: 11825 }, { vendorId: 7504, productId: 24866, path: '/dev/hidraw1', serialNumber: '', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 1, usagePage: 48, usage: 24943 }, { vendorId: 7504, productId: 24866, path: '/dev/hidraw2', serialNumber: '', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 2, usagePage: 49 }, { vendorId: 7504, productId: 24866, path: '/dev/hidraw3', serialNumber: '', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 3, usagePage: 50 }, { vendorId: 7504, productId: 24866, path: '/dev/hidraw4', serialNumber: '', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 4, usagePage: 51 } ]
[09:44:45.624] [UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[09:44:45.725] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[09:44:45.726] [UhkHidDevice] USB[W]: 01 00 88 13 00 00
[09:44:45.871] [UhkHidDevice] reenumeration devices [ { vendorId: 7504, productId: 24866, path: '/dev/hidraw2', serialNumber: '', manufacturer: 'Ultimate Gadget Laboratories', release: 0, interface: -1 } ]
[09:44:45.873] [UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[09:44:45.974] [UhkHidDevice] reenumeration devices []
[09:44:45.975] [UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[09:44:46.075] [UhkHidDevice] reenumeration devices []
[09:44:46.076] [UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[09:44:46.177] [UhkHidDevice] reenumeration devices []
[09:44:46.178] [UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[09:44:46.281] [UhkHidDevice] reenumeration devices [ { vendorId: 7504, productId: 24864, path: '/dev/hidraw0', serialNumber: '', manufacturer: 'Ultimate Gadget Laboratories', product: 'UHK Bootloader', release: 2, interface: 0, usagePage: 40960, usage: 43687 } ]
[09:44:46.282] [UhkHidDevice] reenumeration devices up
[09:44:46.282] [UhkHidDevice] Device communication closing.
[09:44:46.283] [UhkHidDevice] Device communication closed.
[09:44:46.285] [blhost] RUN: /tmp/.mount_uhkF1Dlm6/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[09:44:46.392] [blhost] STDOUT: Error: UsbHidPeripheral() cannot open USB HID device (vid=0x1d50, pid=0x6120, sn=).
[09:44:46.394] [blhost] EXIT_CODE: 1
[09:44:46.394] [blhost] FINISHED: 1
[09:44:46.396] [DeviceService] updateFirmware error { message: 'blhost error code:1', stack: 'Error: blhost error code:1\n at u (/tmp/.mount_uhkF1Dlm6/resources/app.asar/electron-main.js:92:289375)\n at ChildProcess.<anonymous> (/tmp/.mount_uhkF1Dlm6/resources/app.asar/electron-main.js:92:289690)\n at ChildProcess.emit (events.js:194:13)\n at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)' }
[09:44:46.398] [UhkHidDevice] Available devices:
[09:44:46.398] {"vendorId":7504,"productId":24864,"path":"/dev/hidraw0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":0}
[09:44:46.398] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected at /tmp/.mount_uhkF1Dlm6/resources/app.asar/electron-main.js:92:299056 at new Promise (<anonymous>) at t.UhkHidDevice.<anonymous> (/tmp/.mount_uhkF1Dlm6/resources/app.asar/electron-main.js:92:298996) at Generator.next (<anonymous>) at /tmp/.mount_uhkF1Dlm6/resources/app.asar/electron-main.js:46:1584 at new Promise (<anonymous>) at Module.l (/tmp/.mount_uhkF1Dlm6/resources/app.asar/electron-main.js:46:1361) at t.UhkHidDevice.write (/tmp/.mount_uhkF1Dlm6/resources/app.asar/electron-main.js:92:298948) at t.UhkHidDevice.<anonymous> (/tmp/.mount_uhkF1Dlm6/resources/app.asar/electron-main.js:92:300221) at Generator.next (<anonymous>)
[09:44:46.399] [blhost] CLOSE_CODE: 1
blhost error code:1
```

I found #955 which looks similar to mine, but 1) I did let it setup the udev rules, and 2) I tried running with sudo and it nagged at me to use `--no-sandbox`. I ran with that option and I have the same error (but at that point I had other USB devices connected).

Here are my udev rules for good measure:
```
➜  ~ l /etc/udev/rules.d 
total 12K
drwxr-xr-x 2 root root 4.0K Sep 19 16:25 .
drwxr-xr-x 4 root root 4.0K Sep  9 02:30 ..
lrwxrwxrwx 1 root root   52 Apr  5 18:15 10-local.rules -> /home/james/dotfiles/etc/udev/rules.d/10-local.rules
-rw-r--r-- 1 root root  432 Sep 24 00:45 50-uhk60.rules
➜  ~ cat /etc/udev/rules.d/50-uhk60.rules 
# Ultimate Hacking Keyboard rules
# These are the udev rules for accessing the USB interfaces of the UHK as non-root users.
# Copy this file to /etc/udev/rules.d and physically reconnect the UHK afterwards.
SUBSYSTEM=="input", GROUP="input", MODE="0666"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"
KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"
➜  ~ 
```

**Comment by mondalaci** [comment]
Could you update your firmware via Agent 1.2.12? I don't think you could because it looks like your [udev rules](https://github.com/UltimateHackingKeyboard/agent/blob/master/rules/50-uhk60_v2.rules) are not set up correctly.

**Comment by mondalaci** [comment]
Just seen that you updated this issue. Let me read the new content you posted...

**Comment by mondalaci** [comment]
Please retry with Agent 1.2.12 and let me know if firmware update works.

Please also build Agent from source, and let's see if the firmware update works when Agent is executed with `npm run electron:kboot`.

**Comment by FatBoyXPC** [comment]
I'll try with agent 1.2.12 first. I noticed my udev rule is slightly different than you linked, is that okay? When I loaded up 1.2.13 it showed that they needed updated and I clicked to update them. I didn't update them myself (was I supposed to?).

**Comment by mondalaci** [comment]
I'm not quite sure whether the updated udev rules would make any difference. Please try the new udev rules, but only try one thing at a time to be able to isolate the root cause.

**Comment by FatBoyXPC** [comment]
With agent 1.2.12:

```
Start flashing firmware
[10:10:58.686] Agent version: 1.2.12
[10:10:58.711] [UhkHidDevice] Available devices unchanged
[10:10:58.767] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"/dev/hidraw5","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":50}
[10:10:58.768] [UhkHidDevice] USB[W]: 09
[10:10:58.776] [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[10:10:58.777] [DeviceOperation] USB[T]: Read left module version information
[10:10:58.778] [UhkHidDevice] USB[W]: 0e 01 00
[10:10:58.784] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[10:10:58.785] [DeviceOperation] USB[T]: Read right module version information
[10:10:58.786] [UhkHidDevice] USB[W]: 00 01
[10:10:58.792] [UhkHidDevice] USB[R]: 00 08 00 00 00 00 00 04 00 01 00 00 00 04 00 00 00 00 00 04 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[10:10:58.793] Device right firmware version: 8.0.0
[10:10:58.793] Device left firmware version: 8.0.0
[10:10:58.795] New firmware version: 8.5.3
[10:10:58.798] [UhkOperations] Operating system: Linux 5.3.1-arch1-1-ARCH x64
[10:10:58.798] [UhkOperations] Start flashing right firmware
[10:10:58.799] [UhkHidDevice] Start reenumeration, mode: Bootloader
[10:10:58.909] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[10:10:58.910] [UhkHidDevice] USB[W]: 01 00 88 13 00 00
[10:10:59.172] [DeviceService] updateFirmware error { message: 'Cannot write to HID device', stack: 'Error: Cannot write to HID device\n at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.Agec09Xh/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:199:1)\n at Generator.next (<anonymous>)\n at fulfilled (/tmp/.mount_UHK.Agec09Xh/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:4:42)\n at <anonymous>' }
[10:10:59.174] [UhkHidDevice] USB[W]: 09
[10:10:59.175] [DeviceService] Read hardware modules information failed Error: Cannot write to HID device at Promise (/tmp/.mount_UHK.Agec09Xh/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:124:1) at Promise (<anonymous>) at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.Agec09Xh/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:104:1) at Generator.next (<anonymous>) at /tmp/.mount_UHK.Agec09Xh/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1 at Promise (<anonymous>) at __awaiter (/tmp/.mount_UHK.Agec09Xh/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1) at UhkHidDevice.write (/tmp/.mount_UHK.Agec09Xh/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:103:1) at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.Agec09Xh/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:155:1) at Generator.next (<anonymous>)
[10:10:59.176] [UhkHidDevice] Transfer error: Error: could not read from HID device
[10:10:59.177] [UhkHidDevice] Device communication closing.
[10:10:59.177] [UhkHidDevice] Device communication closed.
Cannot write to HID device
```

**Comment by FatBoyXPC** [comment]
Built from source:
```
Start flashing firmware
[10:18:48.101] Agent version: 1.2.13
[10:18:48.102] [UhkHidDevice] USB[W]: 09
[10:18:48.110] [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[10:18:48.111] [DeviceOperation] USB[T]: Read left module version information
[10:18:48.111] [UhkHidDevice] USB[W]: 0e 01 00
[10:18:48.119] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[10:18:48.120] [DeviceOperation] USB[T]: Read right module version information
[10:18:48.121] [UhkHidDevice] USB[W]: 00 01
[10:18:48.155] [UhkHidDevice] USB[W]: 09
[10:18:48.158] [UhkHidDevice] USB[R]: 00 08 00 00 00 00 00 04 00 01 00 00 00 04 00 00 00 00 00 04 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[10:18:48.160] Device right firmware version: 8.0.0
[10:18:48.160] Device left firmware version: 8.0.0
[10:18:48.164] [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[10:18:48.264] New firmware version: 8.6.0
[10:18:48.265] [UhkOperations] Operating system: Linux 5.3.1-arch1-1-ARCH x64
[10:18:48.266] [UhkOperations] Start flashing right firmware
[10:18:48.267] [UhkOperations] Reenumerate bootloader
[10:18:48.268] [UhkHidDevice] Start reenumeration, mode: Bootloader
[10:18:48.296] [UhkHidDevice] reenumeration devices [ { vendorId: 6127, productId: 12384, path: '/dev/hidraw0', serialNumber: '0001', manufacturer: 'Cypress Semiconductor', product: 'ThinkPad USB-C Dock', release: 0, interface: 1 }, { vendorId: 4152, productId: 5904, path: '/dev/hidraw2', serialNumber: '', manufacturer: 'SteelSeries', product: 'SteelSeries Rival 300 Gaming Mouse', release: 104, interface: 0 }, { vendorId: 4152, productId: 5904, path: '/dev/hidraw3', serialNumber: '', manufacturer: 'SteelSeries', product: 'SteelSeries Rival 300 Gaming Mouse', release: 104, interface: 1 }, { vendorId: 4152, productId: 5904, path: '/dev/hidraw4', serialNumber: '', manufacturer: 'SteelSeries', product: 'SteelSeries Rival 300 Gaming Mouse', release: 104, interface: 2 }, { vendorId: 7504, productId: 24866, path: '/dev/hidraw5', serialNumber: '', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 0, usagePage: 50 }, { vendorId: 7504, productId: 24866, path: '/dev/hidraw6', serialNumber: '', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 1, usagePage: 48 }, { vendorId: 7504, productId: 24866, path: '/dev/hidraw7', serialNumber: '', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 2, usagePage: 49 }, { vendorId: 7504, productId: 24866, path: '/dev/hidraw8', serialNumber: '', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 3, usagePage: 50 }, { vendorId: 7504, productId: 24866, path: '/dev/hidraw9', serialNumber: '', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 4, usagePage: 51 }, { vendorId: 6127, productId: 12387, path: '/dev/hidraw1', serialNumber: '000000000000', manufacturer: 'Lenovo', product: 'ThinkPad USB-C Dock Audio', release: 2306, interface: 3 } ]
[10:18:48.300] [UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[10:18:48.401] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[10:18:48.402] [UhkHidDevice] USB[W]: 01 00 88 13 00 00
[10:18:48.410] [DeviceService] updateFirmware error { message: 'Cannot write to HID device', stack: 'Error: Cannot write to HID device\n at t.UhkHidDevice.<anonymous> (/home/james/dev/agent/packages/uhk-agent/dist/electron-main.js:92:301437)\n at Generator.next (<anonymous>)\n at s (/home/james/dev/agent/packages/uhk-agent/dist/electron-main.js:46:1417)' }
[10:18:48.413] [UhkHidDevice] USB[W]: 09
[10:18:48.418] [DeviceService] Read hardware modules information failed Error: Cannot write to HID device at /home/james/dev/agent/packages/uhk-agent/dist/electron-main.js:92:299506 at new Promise (<anonymous>) at t.UhkHidDevice.<anonymous> (/home/james/dev/agent/packages/uhk-agent/dist/electron-main.js:92:298996) at Generator.next (<anonymous>) at /home/james/dev/agent/packages/uhk-agent/dist/electron-main.js:46:1584 at new Promise (<anonymous>) at Module.l (/home/james/dev/agent/packages/uhk-agent/dist/electron-main.js:46:1361) at t.UhkHidDevice.write (/home/james/dev/agent/packages/uhk-agent/dist/electron-main.js:92:298948) at t.UhkHidDevice.<anonymous> (/home/james/dev/agent/packages/uhk-agent/dist/electron-main.js:92:300221) at Generator.next (<anonymous>)
[10:18:48.615] [UhkHidDevice] Transfer error: Error: could not read from HID device
[10:18:48.616] [UhkHidDevice] Device communication closing.
[10:18:48.617] [UhkHidDevice] Device communication closed.
Cannot write to HID device
```

**Comment by FatBoyXPC** [comment]
I updated the udev rules accordingly and I have the same issue when using Agent 1.2.13.

**Comment by mondalaci** [comment]
Your issue persists regardless of Agent versions and wheher blhost or the native kboot implementation is used, because it's a permission issue.

Arch in general, or your Arch installation in specific may have some strange permission related issues. Did you reload the udev rules? Please also reconnect your UHK.

**Comment by FatBoyXPC** [comment]
I reconnected the keyboard but I forgot to reload the udev rules. I ran `sudo udevadm control --reload-rules && sudo udevadm trigger` then reconnected the keyboard, and I have the same failure.

How can I run it with `--no-sandbox` with the build from source?

**Comment by FatBoyXPC** [comment]
Well, I finally got it to work, but I'm not sure how. I've rebooted since the udev rules and I made sure nothing else was connected to the laptop. I feel like I had tried that already, so I'm not sure what's going on.

I was able to get `sudo uhk --no-sandbox` to work. I've renamed the AppImage to `uhk` and placed it in my path.
