### ISSUE TITLE
Firmware upgrade failed on 2020 MacBook Pro via Thunderbolt dock and Apple usb - usb c dongle

### ISSUE THREAD

**Issue by solarmist** [UltimateHackingKeyboard/agent#1261]
```
Start flashing firmware
Agent version: 1.4.5
[UhkHidDevice] USB[W]: 09
[UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DeviceOperation] USB[T]: Read left module version information
[UhkHidDevice] USB[W]: 0e 01 00
[UhkHidDevice] USB[R]: 00 01 04 00 01 00 00 00 08 00 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DeviceOperation] USB[T]: Read right module version information
[UhkHidDevice] USB[W]: 00 01
[UhkHidDevice] USB[R]: 00 08 00 06 00 00 00 04 00 05 00 00 00 04 00 01 00 00 00 04 00 01 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Device right firmware version: 8.6.0
Device left firmware version: 8.6.0
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
New firmware version: 8.9.3
[UhkOperations] Operating system: Darwin 19.5.0 x64
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader
[UhkHidDevice] USB[T]: Enumerated device, mode: Bootloader
[UhkHidDevice] USB[W]: 01 00 88 13 00 00
[DeviceService] updateFirmware error {"message":"Cannot write to HID device","stack":"Error: Cannot write to HID device
 at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:101:29343)
 at Generator.next (<anonymous>)
 at s (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1740)"}
[UhkHidDevice] USB[W]: 09
[UhkHidDevice] Transfer error: Error: Cannot write to HID device at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:101:27094) at Generator.next (<anonymous>) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1938 at new Promise (<anonymous>) at Object.l [as __awaiter] (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1683) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:101:26846 at new Promise (<anonymous>) at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:101:26825) at Generator.next (<anonymous>) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1938
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceService] Read hardware modules information failed Error: Cannot write to HID device at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:101:27094) at Generator.next (<anonymous>) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1938 at new Promise (<anonymous>) at Object.l [as __awaiter] (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1683) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:101:26846 at new Promise (<anonymous>) at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:101:26825) at Generator.next (<anonymous>) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1938
[DeviceService] start poll UHK Device
Cannot write to HID device
```

**Comment by mondalaci** [comment]
What happens if you run Agent as root and retry?

**Comment by mondalaci** [comment]
Closing issue due to the lack of replies.
