### ISSUE TITLE
Unable to update uhk

### ISSUE THREAD

**Issue by Fliko** [UltimateHackingKeyboard/agent#1306]
I haven't updated my uhk firmware in a while because it works. I want to use it now on my home linux machine, but it doesn't connect. it's amd so I saw that I might need to update the firmware to fix it.

Agent 1.5.0
firmware 8.5.3
mac catalina 10.15.5

I tried flashing it and got an error, then I tried the steps in #1059 and got another error, then tried flashing again.

### Flash Log

```
Start flashing firmware
Agent version: 1.5.0
Device right firmware version: 8.5.3
Device left firmware version: 8.5.3
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
New firmware version: 8.10.1
[UhkOperations] Operating system: Darwin 19.5.0 x64
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader
[DeviceService] updateFirmware error {"message":"Cannot write to HID device","stack":"Error: Cannot write to HID device\n at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:30070)\n at Generator.next (<anonymous>)\n at s (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1740)"}
[UhkHidDevice] Transfer error: Error: Cannot write to HID device at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:27834) at Generator.next (<anonymous>) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1938 at new Promise (<anonymous>) at Object.l [as __awaiter] (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1683) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:27588 at new Promise (<anonymous>) at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:27567) at Generator.next (<anonymous>) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1938
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceService] Read hardware modules information failed Error: Cannot write to HID device at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:27834) at Generator.next (<anonymous>) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1938 at new Promise (<anonymous>) at Object.l [as __awaiter] (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1683) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:27588 at new Promise (<anonymous>) at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:27567) at Generator.next (<anonymous>) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1938
[DeviceService] start poll UHK Device
Cannot write to HID device
```

### Fix Device Log
```
 Fix device
Your device seems to be broken. No worries, Agent can fix it.

 

[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
[UhkOperations] Operating system: Darwin 19.5.0 x64
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader
[UhkHidDevice] Available devices:
{"vendorId":1452,"productId":636,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@3/AppleUserUSBHostHIDDevice","serialNumber":"FM7821300UJHYYMAT+ENZ","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":2343,"interface":3,"usagePage":65280,"usage":13}
{"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS04@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/Ultimate Hacking Keyboard@14410000/IOUSBHostInterface@0/AppleUserUSBHostHIDDevice","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":65280,"usage":1}
{"vendorId":1452,"productId":636,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@2/AppleUserUSBHostHIDDevice","serialNumber":"FM7821300UJHYYMAT+ENZ","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":2343,"interface":2,"usagePage":1,"usage":2}
{"vendorId":1452,"productId":636,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@2/AppleUserUSBHostHIDDevice","serialNumber":"FM7821300UJHYYMAT+ENZ","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":2343,"interface":2,"usagePage":1,"usage":1}
{"vendorId":1452,"productId":636,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@2/AppleUserUSBHostHIDDevice","serialNumber":"FM7821300UJHYYMAT+ENZ","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":2343,"interface":2,"usagePage":13,"usage":5}
{"vendorId":1452,"productId":636,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@2/AppleUserUSBHostHIDDevice","serialNumber":"FM7821300UJHYYMAT+ENZ","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":2343,"interface":2,"usagePage":65280,"usage":12}
{"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS04@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/Ultimate Hacking Keyboard@14410000/IOUSBHostInterface@3/AppleUserUSBHostHIDDevice","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":3,"usagePage":1,"usage":128}
{"vendorId":1452,"productId":33538,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80600000/Touch Bar Display@80600000/HID Relay@0/AppleUserUSBHostHIDDevice","serialNumber":"0000000000000000","manufacturer":"Apple Inc.","product":"Touch Bar Display","release":513,"interface":0,"usagePage":13,"usage":5}
{"vendorId":1452,"productId":33538,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80600000/Touch Bar Display@80600000/HID Relay@0/AppleUserUSBHostHIDDevice","serialNumber":"0000000000000000","manufacturer":"Apple Inc.","product":"Touch Bar Display","release":513,"interface":0,"usagePage":65280,"usage":35}
{"vendorId":1452,"productId":33538,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80600000/Touch Bar Display@80600000/HID Relay@0/AppleUserUSBHostHIDDevice","serialNumber":"0000000000000000","manufacturer":"Apple Inc.","product":"Touch Bar Display","release":513,"interface":0,"usagePage":65280,"usage":22}
{"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS04@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/Ultimate Hacking Keyboard@14410000/IOUSBHostInterface@4/AppleUserUSBHostHIDDevice","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":4,"usagePage":1,"usage":2}
{"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS04@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/Ultimate Hacking Keyboard@14410000/IOUSBHostInterface@4/AppleUserUSBHostHIDDevice","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":4,"usagePage":1,"usage":1}
{"vendorId":1452,"productId":636,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@0/AppleUserUSBHostHIDDevice","serialNumber":"FM7821300UJHYYMAT+ENZ","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":2343,"interface":0,"usagePage":65280,"usage":11}
{"vendorId":1452,"productId":636,"path":"IOService:/IOResources/IOHIDResource/IOHIDResourceDeviceUserClient/IOHIDUserDevice","serialNumber":"","manufacturer":"","product":"Keyboard Backlight","release":0,"interface":-1,"usagePage":65280,"usage":15}
{"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS04@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/Ultimate Hacking Keyboard@14410000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":1,"usagePage":1,"usage":6}
{"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS04@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/Ultimate Hacking Keyboard@14410000/IOUSBHostInterface@2/AppleUserUSBHostHIDDevice","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":2,"usagePage":12,"usage":1}
{"vendorId":1452,"productId":33026,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80700000/Touch Bar Backlight@80700000/HID Relay@0/AppleUserUSBHostHIDDevice","serialNumber":"0000000000000000","manufacturer":"Apple Inc.","product":"Touch Bar Backlight","release":513,"interface":0,"usagePage":65298,"usage":1}
{"vendorId":1452,"productId":636,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@4/AppleUserUSBHostHIDDevice","serialNumber":"FM7821300UJHYYMAT+ENZ","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":2343,"interface":4,"usagePage":65280,"usage":3}
{"vendorId":1452,"productId":33378,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80300000/Ambient Light Sensor@80300000/HID Relay@0/AppleUserUSBHostHIDDevice","serialNumber":"000000000000","manufacturer":"Apple Inc.","product":"Ambient Light Sensor","release":513,"interface":0,"usagePage":32,"usage":65}
{"vendorId":1452,"productId":636,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@1/AppleUserUSBHostHIDDevice","serialNumber":"FM7821300UJHYYMAT+ENZ","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":2343,"interface":1,"usagePage":1,"usage":6}
{"vendorId":1452,"productId":636,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@1/AppleUserUSBHostHIDDevice","serialNumber":"FM7821300UJHYYMAT+ENZ","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":2343,"interface":1,"usagePage":12,"usage":1}
{"vendorId":1452,"productId":636,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@1/AppleUserUSBHostHIDDevice","serialNumber":"FM7821300UJHYYMAT+ENZ","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":2343,"interface":1,"usagePage":65280,"usage":6}
{"vendorId":1452,"productId":636,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@1/AppleUserUSBHostHIDDevice","serialNumber":"FM7821300UJHYYMAT+ENZ","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":2343,"interface":1,"usagePage":65280,"usage":15}
{"vendorId":1452,"productId":33027,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80400000/Headset@80400000/HID Relay@0/AppleUserUSBHostHIDDevice","serialNumber":"000000000000","manufacturer":"Apple","product":"Headset","release":515,"interface":0,"usagePage":12,"usage":1}
{"vendorId":1452,"productId":34304,"path":"IOService:/IOResources/IOHIDResource/IOHIDResourceDeviceUserClient/IOHIDUserDevice","serialNumber":"","manufacturer":"","product":"","release":0,"interface":-1,"usagePage":1,"usage":6}
[UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS04@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/Ultimate Hacking Keyboard@14410000/IOUSBHostInterface@0/AppleUserUSBHostHIDDevice","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":65280,"usage":1}
[DeviceService] updateFirmware error {"message":"Cannot write to HID device","stack":"Error: Cannot write to HID device\n at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:30070)\n at Generator.next (<anonymous>)\n at s (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1740)"}
[UhkHidDevice] Transfer error: Error: Cannot write to HID device at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:27834) at Generator.next (<anonymous>) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1938 at new Promise (<anonymous>) at Object.l [as __awaiter] (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1683) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:27588 at new Promise (<anonymous>) at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:27567) at Generator.next (<anonymous>) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1938
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceService] Read hardware modules information failed Error: Cannot write to HID device at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:27834) at Generator.next (<anonymous>) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1938 at new Promise (<anonymous>) at Object.l [as __awaiter] (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1683) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:27588 at new Promise (<anonymous>) at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:27567) at Generator.next (<anonymous>) at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:43:1938
Cannot write to HID device
```

#### Linux Error
Just in case ya'll might be able to help with my linux error

Artix Linux
AMD cpu

dmesg output
```
[ 9725.995345] usb 3-4: new full-speed USB device number 19 using xhci_hcd
[ 9726.157389] usb 3-4: New USB device found, idVendor=1d50, idProduct=6122, bcdDevice= 1.01
[ 9726.157392] usb 3-4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 9726.157394] usb 3-4: Product: Ultimate Hacking Keyboard
[ 9726.157395] usb 3-4: Manufacturer: Ultimate Gadget Laboratories
[ 9726.157632] usb 3-4: Not enough bandwidth for new device state.
[ 9726.157687] usb 3-4: can't set config #1, error -28
```

**Comment by mondalaci** [comment]
Are you connecting your UHK via a docking station to your Mac? Maybe that's the culprit and the update would work without it or via a hub.

As for your Ryzen PC, it'd be worth to connect your UHK via a hub, and then you could probably update the firmware on it. Afterward, the hub wouldn't be necessary.

**Comment by Fliko** [comment]
Connecting to the linux machine with a hub worked great. After following steps for [unbricking keyboard](https://ultimatehackingkeyboard.com/repair-and-modding/unbricking-the-right-keyboard-half) on both halves I got it working! Feels great, thank you @mondalaci
