### ISSUE TITLE
osx firmware update fail

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [UltimateHackingKeyboard/agent#1363]
Start flashing firmware
Agent version: 1.5.4
Device right firmware version: 8.9.3
Device left firmware version: 8.9.3
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
New firmware version: 8.10.1
[UhkOperations] Operating system: Darwin 19.6.0 x64
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader, timeout: 5000ms
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices:
{"vendorId":1452,"productId":657,"path":"IOService:/IOResources/IOHIDResource/IOHIDResourceDeviceUserClient/IOHIDUserDevice","serialNumber":"","manufacturer":"","product":"Keyboard Backlight","release":0,"interface":-1,"usagePage":65280,"usage":15}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Trackpad / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":1,"usage":2}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Trackpad / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":1,"usage":1}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Trackpad / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":13,"usage":5}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Trackpad / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":65280,"usage":12}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Device Management/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":0,"usagePage":65280,"usage":11}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Keyboard / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":1,"usage":6}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Keyboard / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":12,"usage":1}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Keyboard / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":65280,"usage":6}
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Reenumerating devices
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkOperations] Waiting for bootloader
[UhkOperations] Flash security disable
[DeviceService] updateFirmware error {"message":"USB device can not be found","stack":"Error: USB device can not be found\n    at t.UsbPeripheral.open (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:64304)\n    at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:64543\n    at new Promise (<anonymous>)\n    at t.UsbPeripheral.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:64514)\n    at Generator.next (<anonymous>)\n    at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:57:1957\n    at new Promise (<anonymous>)\n    at Object.l [as __awaiter] (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:57:1702)\n    at t.UsbPeripheral.sendCommand (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:64465)\n    at t.KBoot.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:100:49133)"}
[UhkHidDevice] Available devices:
{"vendorId":1452,"productId":657,"path":"IOService:/IOResources/IOHIDResource/IOHIDResourceDeviceUserClient/IOHIDUserDevice","serialNumber":"","manufacturer":"","product":"Keyboard Backlight","release":0,"interface":-1,"usagePage":65280,"usage":15}
{"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14200000/Ultimate Hacking Keyboard@14200000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":1,"usagePage":1,"usage":6}
{"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14200000/Ultimate Hacking Keyboard@14200000/IOUSBHostInterface@0/AppleUserUSBHostHIDDevice","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":65280,"usage":1}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Keyboard / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":1,"usage":6}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Keyboard / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":12,"usage":1}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Keyboard / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":65280,"usage":6}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Trackpad / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":1,"usage":2}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Trackpad / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":1,"usage":1}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Trackpad / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":13,"usage":5}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Trackpad / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":-1,"usagePage":65280,"usage":12}
{"vendorId":1452,"productId":657,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Device Management/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":369,"interface":0,"usagePage":65280,"usage":11}
[UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14200000/Ultimate Hacking Keyboard@14200000/IOUSBHostInterface@0/AppleUserUSBHostHIDDevice","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":65280,"usage":1}
Keyboard is busy, wait...
[DeviceService] start poll UHK Device
USB device can not be found

**Comment by BebeSparkelSparkel** [comment]
unplugged and then plugged it in and now works for some reason. however it was typing just fine previously
