### ISSUE TITLE
Latest Agent does not find Keyboard

### ISSUE THREAD

**Issue by trappitsch** [UltimateHackingKeyboard/agent#1449]
Until Agent 1.5.9 came out I ran on Agent 1.5.8 with firmware 8.10.2, model UHK60PR. Updating to the Agent v1.5.9 the keyboard was not recognized anymore, all it did was tell me to plug the UHK in. I downgraded again to Agent v1.5.8 and upgraded the keyboard firmware to 8.10.5. Still the same issue with Agent v1.5.9, the keyboard even with the latest firmware is not recognized. Agent v1.5.8 continues working great. 
Tried USB Hub and direct connection.
Using the Linux AppImage version.

**Comment by mondalaci** [comment]
I've just tried to reproduce the reported issue with the Agent 1.5.9 AppImage, and I couldn't.

Please attach the Agent log outputted to the terminal.

**Comment by trappitsch** [comment]
Here's some of the output from the beginning. It continues in the same way until my patience runs out ;)
Thanks for your help!

```
(node:59985) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
15:06:52.971 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.vgQRMt)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:06:53.230 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.vgQRMt)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:06:53.488 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.vgQRMt)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:06:53.741 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.vgQRMt)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:06:53.993 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.vgQRMt)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
(node:59985) UnhandledPromiseRejectionWarning: Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.vgQRMt)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
(node:59985) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:59985) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
15:06:54.246 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.vgQRMt)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:06:54.498 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.vgQRMt)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:06:54.751 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.vgQRMt)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:06:55.003 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.vgQRMt)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_1.5.9.rKhiWv/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
```

**Comment by mondalaci** [comment]
@ert78gb Any ideas?

**Comment by ert78gb** [comment]
@trappitsch please try the https://drive.google.com/file/d/15OTDB6fsmZcb9lLZzffKDE9RyrOe2t8S/view?usp=sharing version.

**Comment by trappitsch** [comment]
@ert78gb tried the rebuild version, pretty similar behavior. Some of the console output below - still not finding the UHK

```
[...] ./UHK.Agent-1.5.9-linux-x86_64-rebuild.AppImage 
15:45:25.642 › [Electron Main] init services.
15:45:25.647 › [Electron Main] packagesDir: /tmp/.mount_UHK.Ag0i4d86/resources
15:45:25.921 › [Electron Main] Create new window.
15:45:25.922 › [WindowState] load settings
15:45:25.924 › [WindowState] loaded settings {
  x: 3006,
  y: 397,
  width: 1024,
  height: 768,
  isMaximized: false,
  isFullScreen: false
}
15:45:25.927 › [WindowState] loaded settings is visible false
15:45:25.928 › [WindowState] return with default settings
15:45:26.239 › [DeviceService] start poll UHK Device
15:45:26.371 › [DeviceService] init success
15:45:26.372 › [AppUpdateService] init success
15:45:26.373 › [AppService] init success
15:45:26.373 › [SudoService] App root dir:  /tmp/.mount_UHK.Ag0i4d86/resources
(node:27140) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
15:45:26.390 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.GTDVEd)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:45:26.393 › [WindowState] save settings: {
  x: 448,
  y: 553,
  width: 1024,
  height: 768,
  isMaximized: false,
  isFullScreen: false
}
15:45:26.395 › [WindowState] save settings success
15:45:26.422 › [WindowState] load settings
15:45:26.423 › [WindowState] loaded settings {
  x: 448,
  y: 553,
  width: 1024,
  height: 768,
  isMaximized: false,
  isFullScreen: false
}
15:45:26.425 › [WindowState] loaded settings is visible true
15:45:26.426 › [WindowState] return with loaded settings
15:45:26.426 › [WindowState] save settings: {
  x: 448,
  y: 553,
  width: 1024,
  height: 768,
  isMaximized: true,
  isFullScreen: false
}
15:45:26.428 › [WindowState] save settings success
15:45:26.430 › [WindowState] load settings
15:45:26.430 › [WindowState] loaded settings {
  x: 448,
  y: 553,
  width: 1024,
  height: 768,
  isMaximized: true,
  isFullScreen: false
}
15:45:26.431 › [WindowState] loaded settings is visible true
15:45:26.432 › [WindowState] return with loaded settings
15:45:26.432 › [WindowState] save settings: {
  x: 448,
  y: 553,
  width: 1024,
  height: 768,
  isMaximized: true,
  isFullScreen: false
}
15:45:26.434 › [WindowState] save settings success
15:45:26.474 › [DeviceService] Udev info: Ok
15:45:26.644 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.GTDVEd)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:45:26.896 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.GTDVEd)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:45:27.149 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.GTDVEd)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:45:27.297 › [AppRendererService] init success 
15:45:27.324 › [DeviceRendererService] init success 
15:45:27.329 › Renderer appStart effect start
15:45:27.330 › [AppUpdateService] check for update at startup: { checkForUpdateOnStartUp: false }
15:45:27.330 › [AppRendererService] getAppStartInfo
15:45:27.331 › [AppService] getAppStartInfo
(node:27140) UnhandledPromiseRejectionWarning: Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.GTDVEd)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
(node:27140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:27140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
15:45:27.330 › Renderer appStart effect end
15:45:27.401 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.GTDVEd)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:45:27.653 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.GTDVEd)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:45:27.905 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.GTDVEd)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
15:45:28.159 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.GTDVEd)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_UHK.Ag0i4d86/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)
[...]
```

**Comment by ert78gb** [comment]
What is your OS?

**Comment by trappitsch** [comment]
PureOS (based on Debian), Kernel 4.19.0-14-amd64.

**Comment by ert78gb** [comment]
@trappitsch Can you check the new build https://drive.google.com/file/d/1pYYGb66r05IZx0_9l2jNebEbJwTT2Ooq/view?usp=sharing

I tested it in the virtual machine with the latest PureOS 9, but I would like to know is it working on your machine or not.
thx

**Comment by trappitsch** [comment]
@ert78gb This version (rebuild2) works on my machine now. Thanks for the fast help with this!

**Comment by ert78gb** [comment]
thx for the confirmation. On this week we will release a new "official" version.

**Comment by trappitsch** [comment]
Perfect thanks, I guess that all closes this issue.
