### ISSUE TITLE
Cannot assign keymap switching action

### ISSUE THREAD

**Issue by bodograumann** [UltimateHackingKeyboard/agent#1452]
With the latest version 1.5.9 it is not possible to use the select input for choosing a keymap to switch to.
When a key is already designated as keymap switching key, the select opens up upon clicking.
For all other keys the select can only be opened with the arrow keys.
In any case it is impossible to change the assigned value or designate a new key for keymap switching.

When trying to use the select, a lot of these errors appear in the console:

```
19:04:50.508 › TypeError: Cannot read property 'areHalvesMerged' of undefined
    at template (file:///tmp/.mount_UHK.AgiCJRD4/resources/app.asar/renderer/main-es2015.59da763dc4112e46baa3.js:1:995300)
    at $r (file:///tmp/.mount_UHK.AgiCJRD4/resources/app.asar/renderer/main-es2015.59da763dc4112e46baa3.js:1:1535853)
    at Vr (file:///tmp/.mount_UHK.AgiCJRD4/resources/app.asar/renderer/main-es2015.59da763dc4112e46baa3.js:1:1534495)
    at fo (file:///tmp/.mount_UHK.AgiCJRD4/resources/app.asar/renderer/main-es2015.59da763dc4112e46baa3.js:1:1541517)
    at file:///tmp/.mount_UHK.AgiCJRD4/resources/app.asar/renderer/main-es2015.59da763dc4112e46baa3.js:1:1535357
    at Vr (file:///tmp/.mount_UHK.AgiCJRD4/resources/app.asar/renderer/main-es2015.59da763dc4112e46baa3.js:1:1535368)
    at file:///tmp/.mount_UHK.AgiCJRD4/resources/app.asar/renderer/main-es2015.59da763dc4112e46baa3.js:1:1534922
    at Vr (file:///tmp/.mount_UHK.AgiCJRD4/resources/app.asar/renderer/main-es2015.59da763dc4112e46baa3.js:1:1534947)
    at file:///tmp/.mount_UHK.AgiCJRD4/resources/app.asar/renderer/main-es2015.59da763dc4112e46baa3.js:1:1534922
    at Vr (file:///tmp/.mount_UHK.AgiCJRD4/resources/app.asar/renderer/main-es2015.59da763dc4112e46baa3.js:1:1534947)
```

**Comment by mondalaci** [comment]
Thanks for reporting! I can clearly reproduce this issue, and we'll fix it as soon as possible.
