### ISSUE TITLE
Flashing problems - collision of uhkv1 and uhkv2

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1456]
What I have done:

- I have tried to flash UHKv2 firmware onto UHKv2 via `make flash`, while having both the UHKv1 and UHKv2 connected. Unfortunately, the script picked the wrong keyboard, and the UHKv1 ended up flashed with UHKv2 firmware.

What the state of affairs is now:

- The UHKv1 is bricked.

- Agent 1.5.8 doesn't see the UHKv1.

- Agent 1.5.9 sees the device, but lists it as UHKv2 -
[agentlog.txt](https://github.com/UltimateHackingKeyboard/agent/files/6092812/agentlog.txt)

- Flashing default firmware file from the 1.5.9 Agent does not work - 
[uhkv1log.txt](https://github.com/UltimateHackingKeyboard/agent/files/6092816/uhkv1log.txt)

- Flashing via `make flash` ends up with:

```
Updating right firmware from build_make/uhk60v1.hex ...
[UhkHidDevice] Could not find reenumerated device: Bootloader. Timeout
Error: Could not reenumerate as Bootloader
    at UhkHidDevice.<anonymous> (/opt/firmware/lib/agent/packages/uhk-usb/src/uhk-hid-device.ts:247:15)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/firmware/lib/agent/packages/uhk-usb/node_modules/tslib/tslib.js:111:62)
```

Expected behaviour:

- Ideally ("nice to have") the flashing scripts should pick correct keyboard when flashing. E.g., when flashing uhkv2 firmware, it should pick the first find uhkv2 device.

- In any case ("must have") Agent should be able to flash correct firmware and therefore unbrick such device.

**Comment by mondalaci** [comment]
@kareltucek Thanks for reporting!

@ert78gb Currently, when updating the firmware and the v2 UHK USB PID is detected, Agent reenumerates it and waits for the v2 bootloader USB PID. Agent should rather wait for any bootloader USB PID, then based on the bootloader PID, flash the correct firmware.

**Comment by mondalaci** [comment]
@kareltucek Until this gets fixed, Agent should be able to [unbrick your UHK](https://ultimatehackingkeyboard.com/repair/unbricking-the-right-keyboard-half).

**Comment by kareltucek** [comment]
Well, actually, the keyboard is *not* bricked. It continues to function fine, except for dead LEDs (due to which it *looks* bricked). But I cannot flash it.

Here are two logs from the "unbricking procedure" / "fix your device" 1.5.8.:

- only right half connected: 
[unbricklog1.txt](https://github.com/UltimateHackingKeyboard/agent/files/6093162/unbricklog1.txt)

- both halves connected 
[unbricklog2.txt](https://github.com/UltimateHackingKeyboard/agent/files/6093167/unbricklog2.txt)

But I think I can live with this state of affairs for the time being quite easily. It is going to block me from writing UHKv2-non-related stuff from home, but that's not a big deal at the moment.

**Comment by mondalaci** [comment]
Give a try to Agent 1.5.9 despite currently being in a pre-release state.

**Comment by kareltucek** [comment]
What exactly should I try with it? As stated above, flashing from there does not work either. 

(Apart from flashing, it seems to work fine.)

**Comment by mondalaci** [comment]
According to your description, you used Agent 1.5.8, not 1.5.9. I think the latter will work when manually triggering the bootloader.

**Comment by kareltucek** [comment]
("Fix your device" procedure does not do anything new with 1.5.9 either - 
[unbricklog3.txt](https://github.com/UltimateHackingKeyboard/agent/files/6093244/unbricklog3.txt))

**Comment by kareltucek** [comment]
Or actually, it does something new since the log is different, but it does not fix the device.

**Comment by mondalaci** [comment]
@kareltucek Please activate the bootloader of your UHK 60 v2 by shorting the pins according to the unbricking instructions, then paste the part of `dmesg` which shows the newly enumerated bootloader device.

**Comment by kareltucek** [comment]
(You sure you are asking about v2? Posting both...)

```
#reset pins on UHKv1
[22283.859954] usb 1-2: USB disconnect, device number 87
[22284.729950] usb 1-2: new full-speed USB device number 88 using xhci_hcd
[22284.879954] usb 1-2: New USB device found, idVendor=1d50, idProduct=6120, bcdDevice= 0.02
[22284.879961] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[22284.879965] usb 1-2: Product: UHK Bootloader
[22284.879968] usb 1-2: Manufacturer: Ultimate Gadget Laboratories
[22284.883657] hid-generic 0003:1D50:6120.00FA: hiddev3,hidraw5: USB HID v1.00 Device [Ultimate Gadget Laboratories UHK Bootloader] on usb-0000:00:14.0-2/input0
[22289.451738] usb 1-2: USB disconnect, device number 88
[22289.762195] usb 1-2: new full-speed USB device number 89 using xhci_hcd
[22289.915324] usb 1-2: New USB device found, idVendor=1d50, idProduct=6124, bcdDevice= 1.01
[22289.915330] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[22289.915333] usb 1-2: Product: UHK 60 v2
[22289.915336] usb 1-2: Manufacturer: Ultimate Gadget Laboratories
[22289.921653] hid-generic 0003:1D50:6124.00FB: hiddev3,hidraw5: USB HID v1.10 Device [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-2/input0
[22289.923133] input: Ultimate Gadget Laboratories UHK 60 v2 as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.1/0003:1D50:6124.00FC/input/input217
[22289.982776] hid-generic 0003:1D50:6124.00FC: input,hidraw10: USB HID v1.10 Keyboard [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-2/input1
[22289.984195] input: Ultimate Gadget Laboratories UHK 60 v2 as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2/0003:1D50:6124.00FD/input/input218
[22290.042615] hid-generic 0003:1D50:6124.00FD: input,hidraw11: USB HID v1.10 Device [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-2/input2
[22290.043665] input: Ultimate Gadget Laboratories UHK 60 v2 as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.3/0003:1D50:6124.00FE/input/input219
[22290.102338] hid-generic 0003:1D50:6124.00FE: input,hidraw12: USB HID v1.10 Device [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-2/input3
[22290.104370] input: Ultimate Gadget Laboratories UHK 60 v2 as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.4/0003:1D50:6124.00FF/input/input220
[22290.104783] hid-generic 0003:1D50:6124.00FF: input,hidraw13: USB HID v1.10 Mouse [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-2/input4

#reset pins on UHKv2
[22306.969629] usb 1-4: USB disconnect, device number 86
[22307.557417] usb 1-4: new full-speed USB device number 90 using xhci_hcd
[22307.707069] usb 1-4: New USB device found, idVendor=1d50, idProduct=6123, bcdDevice= 0.02
[22307.707075] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[22307.707079] usb 1-4: Product: UHK 60 v2 Bootloader
[22307.707082] usb 1-4: Manufacturer: Ultimate Gadget Laboratories
[22307.710495] hid-generic 0003:1D50:6123.0100: hiddev1,hidraw0: USB HID v1.00 Device [Ultimate Gadget Laboratories UHK 60 v2 Bootloader] on usb-0000:00:14.0-4/input0
[22312.189586] usb 1-4: USB disconnect, device number 90
[22312.497520] usb 1-4: new full-speed USB device number 91 using xhci_hcd
[22312.647405] usb 1-4: New USB device found, idVendor=1d50, idProduct=6124, bcdDevice= 1.01
[22312.647411] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[22312.647414] usb 1-4: Product: UHK 60 v2
[22312.647417] usb 1-4: Manufacturer: Ultimate Gadget Laboratories
[22312.654031] hid-generic 0003:1D50:6124.0101: hiddev1,hidraw0: USB HID v1.10 Device [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-4/input0
[22312.655254] input: Ultimate Gadget Laboratories UHK 60 v2 as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.1/0003:1D50:6124.0102/input/input221
[22312.718111] hid-generic 0003:1D50:6124.0102: input,hidraw1: USB HID v1.10 Keyboard [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-4/input1
[22312.719433] input: Ultimate Gadget Laboratories UHK 60 v2 as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.2/0003:1D50:6124.0103/input/input222
[22312.778116] hid-generic 0003:1D50:6124.0103: input,hidraw2: USB HID v1.10 Device [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-4/input2
[22312.779229] input: Ultimate Gadget Laboratories UHK 60 v2 as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.3/0003:1D50:6124.0104/input/input223
[22312.837711] hid-generic 0003:1D50:6124.0104: input,hidraw3: USB HID v1.10 Device [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-4/input3
[22312.839837] input: Ultimate Gadget Laboratories UHK 60 v2 as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.4/0003:1D50:6124.0105/input/input224
[22312.840337] hid-generic 0003:1D50:6124.0105: input,hidraw4: USB HID v1.10 Mouse [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-4/input4
```

**Comment by mondalaci** [comment]
I'm getting confused. According to the last logs, your UHK 60 v2 contains the UHK 60 v2 bootloader as expected. But in [unbricklog3.txt](https://github.com/UltimateHackingKeyboard/agent/files/6093244/unbricklog3.txt), the UHK 60 v1 bootloader is visible.

Did you create unbricklog3.txt when only your UHK 60 v2 was connected? If not, please retry with only your UHK 60 v2 connected.

**Comment by kareltucek** [comment]
I see. This issue is about the UHKv1, not about the UHKv2. I.e.:

- UHKv2 is fine and has always been fine. 
- UHKv1 now contains UHKv2 firmware, and Agent or it's scripts refuse to flash it anymore.

**Comment by mondalaci** [comment]
I couldn't reproduce this issue. I started up Agent 1.5.9. Then I only connected my UHK 60 v1. Next up, I shorted the reset and ground pins of the right half. The recovery screen appeared, then I clicked on the "Fix device" button, and the firmware update procedure was executed successfully.

Is there anything I'm missing?

**Comment by kareltucek** [comment]
> Is there anything I'm missing?

Well, is your v1 running v2 firmware?

**Comment by mondalaci** [comment]
It doesn't matter because the recovery screen only watches the bootloader USB PID, not the firmware USB PID. Would you please retry with a single UHK 60 v1 with no other UHKs attached via USB?

**Comment by kareltucek** [comment]
Sure, will retry again when I get home...

**Comment by kareltucek** [comment]
Hooray! 

No ides what has been different this time, but it worked!
