### ISSUE TITLE
Release script fails

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1475]
Just FYI (since it would be great if these things worked out of box): 

```
/opt/firmware/scripts$ ./make-release.js
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'shelljs/global'
Require stack:
- /opt/firmware/scripts/make-release.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/firmware/scripts/make-release.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/firmware/scripts/make-release.js' ]
}

```

Fixed by globally installing shelljs and exporting NODE_PATH. (`export NODE_PATH=/usr/local/lib/node_modules`, `sudo npm install -g shelljs`, then build within same terminal).

**Comment by ert78gb** [comment]
The folder contains a `package.json` file that [contains](https://github.com/UltimateHackingKeyboard/firmware/blob/741ba1adf82a5826fab78b40e9eb930c205a9003/scripts/package.json#L17) the `shelljs` as dependency. 

Did you run the `$ npm i` before ran the `make-release.js` script?

**Comment by kareltucek** [comment]
Oh, I see.

I assumed that the dependency is built agent, and did not run npm i again in scripts.
