### ISSUE TITLE
Updating Firmware fails

### ISSUE THREAD

**Issue by PyroDevil** [UltimateHackingKeyboard/agent#1521]
I just updated the UHK agent to 1.5.13 and updating the firmware to 8.10.9 fails:

```
Start flashing firmware
New firmware version: 8.10.9
Agent version: 1.5.13
[DeviceService] updateFirmware error {"message":"Communications error with UHK. Response code: undefined","stack":"Error: Communications error with UHK. Response code: undefined\n    at t.UhkHidDevice.<anonymous> (C:\\Users\\ch\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1239132)\n    at Generator.next (<anonymous>)\n    at s (C:\\Users\\ch\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1302211)"}
[DeviceService] Read hardware modules information failed Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (C:\Users\ch\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1239132)
    at Generator.next (<anonymous>)
    at s (C:\Users\ch\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1302211)
[DeviceService] start poll UHK Device
Communications error with UHK. Response code: undefined
```

And this on the console out (I started the agent with `--log=all`):

```
23:20:31.069 > New firmware version: 8.10.9
23:20:31.356 > Agent version: 1.5.13
23:20:31.082 > [DeviceRendererService] dispatch action [device] update firmware JSON
23:20:32.649 > [DeviceService] updateFirmware error {
  message: 'Communications error with UHK. Response code: undefined',
  stack: 'Error: Communications error with UHK. Response code: undefined\n' +
    '    at t.UhkHidDevice.<anonymous> (C:\\Users\\ch\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1239132)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at s (C:\\Users\\ch\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1302211)'
}
23:20:33.957 > [DeviceService] Read hardware modules information failed Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (C:\Users\ch\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1239132)
    at Generator.next (<anonymous>)
    at s (C:\Users\ch\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1302211)
23:20:34.469 > [DeviceService] start poll UHK Device
23:20:34.470 > [DeviceRendererService] dispatch action [device] update firmware reply
```

I tried two different USB cables on three different USB ports that are directly connected to the mainboard while both halves of the UHK are joined.

**Comment by mondalaci** [comment]
Please let me know your operating system and its version.

**Comment by PyroDevil** [comment]
Windows 10 Enterprise, Version 2004, OS build 19041.985

I restarted the system today. Still have the same issue.

**Comment by mondalaci** [comment]
@ert78gb Any ideas?

**Comment by ert78gb** [comment]
I think USB communication is slow and it cause race condition. The #1521 fix the race condition problem.

**Comment by PyroDevil** [comment]
@mondalaci @ert78gb: With Agent 1.5.14 I no longer have this issue.
