### ISSUE TITLE
Cluster module died after trying flush the 8.10.11 firmware

### ISSUE THREAD

**Issue by ssolid2014** [UltimateHackingKeyboard/agent#1590]
Hi  UHK team,

Sorry to bother you again, and thank you first for recall my dead left half and make it alive again, I just received it yesterday. 
And unfortunate thing happened again.........
So when I attached the cluster module and the trackpoint module to the keyboard this time, the trackpoint module works fine, but the left and right button on the cluster module doesn't work. And I saw that you have flush the 8.10.11 firmware to the keyboard, and the firmware of the cluster module and the trackpoint module is still 8.10.9, so I did something that I think is stupid, I downloaded the 8.10.11 firmware and tried to flush it to the cluster module and the trackpoint module. And during the flush process, the cluster module died............

Below is the log
```
Start flashing firmware
[DeviceService] Operating system: Windows_NT 10.0.19043 x64
[DeviceService] Agent version: 1.5.15
[DeviceService] New firmware version: 8.10.11
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
[DeviceOperation] Read "leftHalf" version information
[DeviceOperation] Read "leftModule" version information
[DeviceOperation] Read "rightModule" version information
[DeviceService] UHK Device firmware upgrade starts: {"id":1,"name":"UHK 60 v1","vendorId":"0x1D50","keyboardPid":"0x6122","bootloaderPid":"0x6120","buspalPid":"0x6121"}
[DeviceService] Device right firmware version: 8.10.11
Skip right firmware upgrade.
[DeviceService] Left module firmware version: 8.10.11
[DeviceService] Skip left firmware upgrade.
[DeviceService] "Key cluster" firmware version: 8.10.9
[UhkOperations] Start flashing "Key cluster" module firmware
[UhkHidDevice] Start reenumeration, mode: NormalKeyboard, timeout: 5000ms
[UhkHidDevice] Reenumerating devices
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#a&12792480&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#a&12792480&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkHidDevice] Start reenumeration, mode: Buspal, timeout: 5000ms
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#a&12792480&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Could not find reenumerated device: Buspal. Waiting...
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#a&12792480&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_01#a&2a3cb0c5&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":1,"usagePage":1,"usage":6}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_02#a&6657303&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":2,"usagePage":12,"usage":1}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_03#a&1d71cabf&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":3,"usagePage":1,"usage":128}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_04#a&5ae3e7a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":4,"usagePage":1,"usage":2}
[UhkHidDevice] Could not find reenumerated device: Buspal. Waiting........
[UhkHidDevice] Reenumerating devices
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkOperations] Waiting for buspal
[UhkOperations] Try to connect to the "Key cluster"
[UhkOperations] Waiting 1s to prevent node-hid race condition
[UhkOperations] Flash erase all on "Key cluster" keyboard
[UhkOperations] Read "Key cluster" firmware from file
[UhkOperations] Write memory
[DeviceService] updateFirmware error {"message":"Invalid response length!","stack":"Error: Invalid response length!\n at Object.t.decodeCommandResponse (C:\\Users\\xiaobinshe\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:612975)\n at t.UsbPeripheral.<anonymous> (C:\\Users\\xiaobinshe\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:610192)\n at Generator.next (<anonymous>)\n at s (C:\\Users\\xiaobinshe\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:630710)"}
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6121","path":"\\\\?\\hid#vid_1d50&pid_6121#9&10eca22e&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK BusPal Proxy","release":2,"interface":-1,"usagePage":65280,"usage":1}
[DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected at t.UhkHidDevice.<anonymous> (C:\Users\xiaobinshe\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1242893) at Generator.next (<anonymous>) at C:\Users\xiaobinshe\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1307458 at new Promise (<anonymous>) at Module.l (C:\Users\xiaobinshe\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1307203) at C:\Users\xiaobinshe\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1242811 at new Promise (<anonymous>) at t.UhkHidDevice.<anonymous> (C:\Users\xiaobinshe\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1242789) at Generator.next (<anonymous>) at C:\Users\xiaobinshe\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1307458
[DeviceService] start poll UHK Device
Invalid response length!
```

Is there anything I did wrong and anything I can do?

Thanks.

**Comment by ssolid2014** [comment]
> Hi there! You should be able to unbrick the key cluster module by right-clicking on the Flash Firmware button and then clicking on the Unbrick Key Cluster Module menu item.

Hi @mondalaci , thank you for the reply, I don't know the right-clicking before, but I tried and it still failed to recover the key cluster module, the log said that it can't connect to the bootloader, just like the dead left half before.
And what's even worse is that when I tried to right click the "flush fireware" button and do it again, I left-clicked the button by mistake, and my mind is kind of stucked at that time and I just watched the agent flushed the fireware to the keyboard itself, and again, the left half died as last time...........

I think I made some big mistakes after the keyboard was sent back by you, I should not tried to flush the firmware anymore, and now the left half and the key cluster module are both bricked. You alrealy recall my keyboard once and I appreciate that, and this time I don't want to trouble you anymore.

You mentioned last time that I can unbrick the dead left half by using a J-Link, I will buy one (you don't need to reimburse it as you said last time), and could you please provide some detailed instructions on how to fix the left half and the key cluster module? Although I don't have experience with embeded programming and J-Link but I just built a corne keyboard by myself like 2 weeks ago, I think I should be able to do it by myself if I have the instructions.

Also do you know why the things on the left side (the left half and the key cluster module) died after the flush of the firmware basd on what you found when you are fixing the recalled keyboard? Should I not flush the firmware anymore or is there anything I did wrong when I flush the firmware?

Thanks and sorry for the troubles.
