### ISSUE TITLE
Firmware update failed

### ISSUE THREAD

**Issue by morkai** [UltimateHackingKeyboard/agent#1677]
Hi,

This week I'm in a process of setting up a new PC by trying to remember what needs to be installed and then installing it. Today I wanted to check my UHK v1 layout so installed the latest version of the Agent.

Very soon after the Agent started all 5 of my connected USB devices stopped responding (Windows showing notifications for not recognized devices). I can reproduce it by starting the Agent after PC restart.

I've found that I had everything connected to USB 3.2 ports and after switching the UHK to an USB 2.0 port all USB devices keep working with the Agent running.

Then I've tried to find similar issues here and found that I have firmware v8.10.10 and v8.10.11 has some USB fixes so I tried to update but it failed:

```
Start flashing firmware
[DeviceService] Operating system: Windows_NT 10.0.22000 x64
[DeviceService] Agent version: 1.5.17
[DeviceService] New firmware version: 8.10.12
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
[DeviceOperation] Read "leftHalf" version information
[DeviceService] UHK Device firmware upgrade starts: {"id":1,"name":"UHK 60 v1","vendorId":"0x1D50","keyboardPid":"0x6122","bootloaderPid":"0x6120","buspalPid":"0x6121"}
[DeviceService] Device right firmware version: 8.10.10
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader, timeout: 5000ms
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_02#7&1537382a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":2,"usagePage":12,"usage":1}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_04#7&3277435a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":4,"usagePage":1,"usage":2}
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_01#7&390e75ec&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":1,"usagePage":1,"usage":6}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_03#7&ea00598&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":3,"usagePage":1,"usage":128}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&214ae9a7&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...............................................................................................................................................................................................
[UhkHidDevice] Could not find reenumerated device: Bootloader. Timeout
[DeviceService] updateFirmware error {"message":"Could not reenumerate as Bootloader","stack":"Error: Could not reenumerate as Bootloader\n at t.UhkHidDevice.<anonymous> (C:\\Users\\lukas\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1300721)\n at Generator.next (<anonymous>)\n at s (C:\\Users\\lukas\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1364255)"}
[UhkHidDevice] Transfer error: TypeError: Cannot write to closed device at t.UhkHidDevice.<anonymous> (C:\Users\lukas\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1298863) at Generator.next (<anonymous>) at C:\Users\lukas\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1364453 at new Promise (<anonymous>) at l (C:\Users\lukas\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1364198) at C:\Users\lukas\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1298618 at new Promise (<anonymous>) at t.UhkHidDevice.<anonymous> (C:\Users\lukas\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1298583) at Generator.next (<anonymous>) at C:\Users\lukas\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1364453
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceService] Read hardware modules information failed TypeError: Cannot write to closed device at t.UhkHidDevice.<anonymous> (C:\Users\lukas\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1298863) at Generator.next (<anonymous>) at C:\Users\lukas\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1364453 at new Promise (<anonymous>) at l (C:\Users\lukas\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1364198) at C:\Users\lukas\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1298618 at new Promise (<anonymous>) at t.UhkHidDevice.<anonymous> (C:\Users\lukas\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1298583) at Generator.next (<anonymous>) at C:\Users\lukas\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1364453
[DeviceService] start poll UHK Device
Could not reenumerate as Bootloader
```

UHK works fine a few seconds after the failed update.

This is on Windows 11 with i9-12900k. I've tried rear and front USB ports and running normally and as an admin.
I didn't have these problems for 1.5 years on the previous PC running Windows 10 with i7-9900k (and it had USB 2.0-3.1).

**Comment by mondalaci** [comment]
Hi there,

The firmware update process is currently not bulletproof, and we'll make it more reliable.

As for the interference with other devices you experienced, it can be due to the UHK, your USB host controller, or USB hub. In any case, it's worth trying firmware 8.10.12, 8.10.9, and [uhk-firmware-8.10.12-usb-fix.tar.gz](https://github.com/UltimateHackingKeyboard/firmware/files/7725857/uhk-firmware-8.10.12-usb-fix.tar.gz)

Please make sure to test your UHK with every one of the USB ports directly without using any hubs, docking stations, or KVM switches.

Looking forward to your findings!

**Comment by morkai** [comment]
I've successfully updated the firmware to v8.10.12 using a UP board running Ubuntu Focal, then reconnected everything back to USB 3.2 ports on the new PC and the issue is no longer present!
