### ISSUE TITLE
Left half bricked when trying to update firmware

### ISSUE THREAD

**Issue by james-langille** [UltimateHackingKeyboard/agent#1775]
Hello, I updated agent to 1.5.17 and attempted to flash the latest version of firmware (8.10.12, bundled with agent) on to my UHK 60 v1 (no modules). My right half updates fine, but my left half was briked (maybe because I mistakenly tried to update through a KVM switch?). I tried to follow the instructions to disconnect/reconnect during the update (without the KVM switch), prior firmware versions, etc., but nothing worked.

Any advice? I have no experience hacking with hardware (only software), so I'm wondering what I should do next.

<details>
<summary>Example firmware log</summary>

```
Start flashing firmware
[DeviceService] Operating system: Windows_NT 10.0.19043 x64
[DeviceService] Agent version: 1.5.17
[DeviceService] New firmware version: 8.10.12
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
[DeviceService] UHK Device firmware upgrade starts: {"id":1,"name":"UHK 60 v1","vendorId":"0x1D50","keyboardPid":"0x6122","bootloaderPid":"0x6120","buspalPid":"0x6121"}
[DeviceService] Device right firmware version: 8.10.8
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader, timeout: 5000ms
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_01#7&640d134&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":1,"usagePage":1,"usage":6}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_02#7&2a180ef6&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":2,"usagePage":12,"usage":1}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_03#7&3adb1f3a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":3,"usagePage":1,"usage":128}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_04#7&1703e178&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":4,"usagePage":1,"usage":2}
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting....
[UhkHidDevice] Reenumerating devices
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkOperations] Waiting for bootloader
[UhkOperations] Flash security disable
[UhkOperations] Flash erase region
[UhkOperations] Read RIGHT firmware from file
[UhkOperations] Write memory
[UhkOperations] Reset bootloader
[UhkOperations] Close communication channels
[UhkOperations] Right firmware successfully flashed
[DeviceService] Left module firmware version:  null
[UhkOperations] Start flashing "Left keyboard half" module firmware
[UhkHidDevice] Start reenumeration, mode: NormalKeyboard, timeout: 5000ms
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6120","path":"\\\\?\\hid#vid_1d50&pid_6120#6&161e8bdf&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":-1,"usagePage":65280,"usage":1}
[UhkHidDevice] Available devices unchanged..............................
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6120","path":"\\\\?\\hid#vid_1d50&pid_6120#6&161e8bdf&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":-1,"usagePage":65280,"usage":1}
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_01#7&640d134&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":1,"usagePage":1,"usage":6}
[UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_02#7&2a180ef6&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":2,"usagePage":12,"usage":1}
[UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_03#7&3adb1f3a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":3,"usagePage":1,"usage":128}
[UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_04#7&1703e178&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":4,"usagePage":1,"usage":2}
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Reenumerating devices
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkOperations] Couldn't connect to the "Left keyboard half".
[DeviceService] updateFirmware error {"message":"[UhkOperations] Couldn't connect to the \"Left keyboard half\".","stack":"Error: [UhkOperations] Couldn't connect to the \"Left keyboard half\".\n    at t.UhkOperations.<anonymous> (C:\\Users\\Jamie\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1307226)\n    at Generator.next (<anonymous>)\n    at s (C:\\Users\\Jamie\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1364255)"}
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&1e045d79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[DeviceService] start poll UHK Device
[UhkOperations] Couldn't connect to the "Left keyboard half".
```
</details>

**Comment by mondalaci** [comment]
Hi there! Please retry a few times and try it with another computer, too.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Is it possible to try it in a VMware Workstation virtual machine?

**Comment by mondalaci** [comment]
I don't think it'd make much practical sense to use a virtual machine. A different physical machine is much preferred.

**Comment by james-langille** [comment]
Tried on both Windows and Macbook M1 - results are the same :(

**Comment by mondalaci** [comment]
@james-langille Sorry to hear! Please shoot an email to support at ultimatehackingkeyboard dot com, and we'll replace your module.
