### ISSUE TITLE
Troubles importing configs

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1806]
When I load someone else's config, the keymap/macro pane often doesn't refresh and continues to show the old stuff. As a result, I have to save the config, and then restart the Agent.

Terminal shows:

```
17:05:59.758 › TypeError: Cannot read properties of undefined (reading 'layers')
    at tV (file:///opt/agent/packages/uhk-agent/dist/renderer/main.ae50aea17e299238.js:1:1112768)
    at zh (file:///opt/agent/packages/uhk-agent/dist/renderer/main.ae50aea17e299238.js:1:1125079)
    at pde (file:///opt/agent/packages/uhk-agent/dist/renderer/main.ae50aea17e299238.js:1:1145069)
    at file:///opt/agent/packages/uhk-agent/dist/renderer/main.ae50aea17e299238.js:1:1889426
    at file:///opt/agent/packages/uhk-agent/dist/renderer/main.ae50aea17e299238.js:1:1889756
    at computeNextEntry (file:///opt/agent/packages/uhk-agent/dist/renderer/main.ae50aea17e299238.js:1:1874471)
    at recomputeStates (file:///opt/agent/packages/uhk-agent/dist/renderer/main.ae50aea17e299238.js:1:1874783)
    at file:///opt/agent/packages/uhk-agent/dist/renderer/main.ae50aea17e299238.js:1:1877801
    at p.V.k.pipe.state [as accumulator] (file:///opt/agent/packages/uhk-agent/dist/renderer/main.ae50aea17e299238.js:1:1883169)
    at p._tryNext (file:///opt/agent/packages/uhk-agent/dist/renderer/main.ae50aea17e299238.js:1:1673669)
```

(This is a development agent build, some weeks old. I can retest with fresh if needed.)

I have also been noticing weird glitches in the "Macros" pane section for some time now. Things like a click opening different macro that the one which was clicked. I never found a way to reproduce it though. I import/export my configs often, so the above might be the ultimate cause.

**Comment by mondalaci** [comment]
@kareltucek I'm unable to reproduce this issue. Please try to find a way to reproduce it reliably, list the exact steps, and attach the related configurations.

**Comment by kareltucek** [comment]
Actually, nevermind. Seems like I cannot reproduce it.

**Comment by mondalaci** [comment]
Sure thing; Feel free to share my user config, and reopen this issue later.
