### ISSUE TITLE
v2.0.1 - Firmwareupgrade to 9.1.2 fails

### ISSUE THREAD

**Issue by highend** [UltimateHackingKeyboard/agent#1900]
v2.0.0 worked fine, upgraded the firmware to 9.1.1 with it but installed v2.0.1 a few minutes ago and trying to upgrade to 9.1.2 delivers this log

```
Start flashing firmware
[DeviceService] Operating system: Windows_NT 10.0.20348 x64
[DeviceService] Agent version: 2.0.1
[DeviceService] New firmware version: 9.1.2
[DeviceService] New firmware user config version: 5.1.0
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
[DeviceOperation] Read "leftHalf" version information
[DeviceOperation] Read "leftHalf" repo information
[DeviceOperation] Read "leftModule" version information
[DeviceOperation] Read "leftModule" repo information
[DeviceService] UHK Device firmware upgrade starts: {"id":1,"name":"UHK 60 v1","vendorId":"0x1D50","keyboardPid":"0x6122","bootloaderPid":"0x6120","buspalPid":"0x6121"}
[DeviceService] Device right firmware version: 9.1.1
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader, timeout: 5000ms
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_01#9&10c83908&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":1,"usagePage":1,"usage":6}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_02#9&349f76ca&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":2,"usagePage":12,"usage":1}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_03#9&1cdbea85&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":3,"usagePage":1,"usage":128}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#9&130f04ba&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_04#9&5185e40&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":4,"usagePage":1,"usage":2}
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting........................................................................................................................................................
[UhkHidDevice] Could not find reenumerated device: Bootloader. Timeout
[DeviceService] updateFirmware error {"message":"Could not reenumerate as Bootloader","stack":"Error: Could not reenumerate as Bootloader\n    at Object.reenumerate (D:\\Tools\\UHK Agent_x64\\resources\\app.asar\\electron-main.js:2:621799)\n    at async Object.updateRightFirmwareWithKboot (D:\\Tools\\UHK Agent_x64\\resources\\app.asar\\electron-main.js:2:625678)\n    at async Fr.updateFirmware (D:\\Tools\\UHK Agent_x64\\resources\\app.asar\\electron-main.js:2:528905)\n    at async ar.process (D:\\Tools\\UHK Agent_x64\\resources\\app.asar\\electron-main.js:2:519787)"}
[UhkHidDevice] Transfer error:  TypeError: Cannot write to closed device
    at D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:620140
    at new Promise (<anonymous>)
    at Object.write (D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:619939)
    at Object.getDeviceState (D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:622822)
    at Object.waitUntilKeyboardBusy (D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:632084)
    at Fr.getHardwareModules (D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:526001)
    at Fr.updateFirmware (D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:530614)
    at async ar.process (D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:519787)
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceService] Read hardware modules information failed TypeError: Cannot write to closed device
    at D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:620140
    at new Promise (<anonymous>)
    at Object.write (D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:619939)
    at Object.getDeviceState (D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:622822)
    at Object.waitUntilKeyboardBusy (D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:632084)
    at Fr.getHardwareModules (D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:526001)
    at Fr.updateFirmware (D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:530614)
    at async ar.process (D:\Tools\UHK Agent_x64\resources\app.asar\electron-main.js:2:519787)
[DeviceService] start poll UHK Device
Could not reenumerate as Bootloader

```

**Comment by mondalaci** [comment]
Please proceed according to https://ultimatehackingkeyboard.com/knowledgebase/what-to-do-after-a-failed-firmware-update and [contact us](https://ultimatehackingkeyboard.com/contact-us) if the issue persists.
