### ISSUE TITLE
Reenumeration error during upgrading

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [UltimateHackingKeyboard/agent#1901]
Could anyone help me to take a look this issue? I'm not able to save anything in the configuration right now. Thanks.

```
Start flashing firmware
[DeviceService] Operating system: Windows_NT 10.0.21313 x64
[DeviceService] Agent version: 2.0.1
[DeviceService] New firmware version: 9.1.2
[DeviceService] New firmware user config version: 5.1.0
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
[DeviceOperation] Read "leftHalf" version information
[DeviceService] UHK Device firmware upgrade starts: {"id":1,"name":"UHK 60 v1","vendorId":"0x1D50","keyboardPid":"0x6122","bootloaderPid":"0x6120","buspalPid":"0x6121"}
[DeviceService] Device right firmware version: 8.10.12
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader, timeout: 5000ms
[UhkHidDevice] Reenumeration error. We hope it would not break the process TypeError: Cannot write to hid device
    at Object.reenumerate (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:621482)
    at async Object.updateRightFirmwareWithKboot (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:625678)
    at async Fr.updateFirmware (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:528905)
    at async ar.process (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:519787)
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#8&8f23e5&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_01#8&28f9d1ae&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":1,"usagePage":1,"usage":6}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_02#8&15c9b570&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":2,"usagePage":12,"usage":1}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_03#8&2999932&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":3,"usagePage":1,"usage":128}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_04#8&2b0446fb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":4,"usagePage":1,"usage":2}
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting........................................................................................................................................................................................................
[UhkHidDevice] Could not find reenumerated device: Bootloader. Timeout
[DeviceService] updateFirmware error {"message":"Could not reenumerate as Bootloader","stack":"Error: Could not reenumerate as Bootloader\n    at Object.reenumerate (C:\\Users\\user1\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:621799)\n    at async Object.updateRightFirmwareWithKboot (C:\\Users\\user1\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:625678)\n    at async Fr.updateFirmware (C:\\Users\\user1\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:528905)\n    at async ar.process (C:\\Users\\user1\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:519787)"}
[UhkHidDevice] Transfer error:  TypeError: Cannot write to hid device
    at C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:620140
    at new Promise (<anonymous>)
    at Object.write (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:619939)
    at Object.getDeviceState (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:622822)
    at Object.waitUntilKeyboardBusy (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:632084)
    at Fr.getHardwareModules (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:526001)
    at Fr.updateFirmware (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:530614)
    at async ar.process (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:519787)
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceService] Read hardware modules information failed TypeError: Cannot write to hid device
    at C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:620140
    at new Promise (<anonymous>)
    at Object.write (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:619939)
    at Object.getDeviceState (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:622822)
    at Object.waitUntilKeyboardBusy (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:632084)
    at Fr.getHardwareModules (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:526001)
    at Fr.updateFirmware (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:530614)
    at async ar.process (C:\Users\user1\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:519787)
[DeviceService] start poll UHK Device
Could not reenumerate as Bootloader

```

**Comment by mondalaci** [comment]
Please follow https://ultimatehackingkeyboard.com/knowledgebase/what-to-do-after-a-failed-firmware-update and email us to support@ultimatehackingkeyboard.com if the problem persists.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Hi, I got the problem solved finally. I did many tests and finally I found that it's the VMware Workstation interfered USB devices on my computer. Sometimes it pops up to ask where should the USB device to be connected to, the host or the guest VM. After I stopped VMware Workstation, I can upgrade without any issue. You can add this to the support page if necessary. 
Btw, is there any documentation about the multi layers new feature? Thanks.

**Comment by mondalaci** [comment]
@0x7FFFFFFFFFFFFFFF Glad you got it solved!

The multiple layers feature should be quite simple to use in the latest Agent. In any case, I plan to write a dedicated blog post about it in mid-November.
