### ISSUE TITLE
Update fails - cannot open device with path hidraw10

### ISSUE THREAD

**Issue by sashs** [UltimateHackingKeyboard/agent#1903]
Hello, 

I use the current version of the agent (2.0.1) and I get the error `cannot open device with path /dev/hidraw10` when I try to update the firmware of the keyboard.

The following excerpt shows the output of the agent during the update process. 

```
Start flashing firmware
[DeviceService] Operating system: Linux 6.0.3-gentoo x64
[DeviceService] Agent version: 2.0.1
[DeviceService] New firmware version: 9.1.2
[DeviceService] New firmware user config version: 5.1.0
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
[DeviceOperation] Read "leftHalf" version information
[DeviceOperation] Read "leftModule" version information
[DeviceOperation] Read "rightModule" version information
[DeviceService] UHK Device firmware upgrade starts: {"id":2,"name":"UHK 60 v2","vendorId":"0x1D50","keyboardPid":"0x6124","bootloaderPid":"0x6123","buspalPid":"0x6121"}
[DeviceService] Device right firmware version: 8.10.12
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader, timeout: 5000ms
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting.....
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw6","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw10","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":1,"usagePage":1,"usage":6}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw11","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":2,"usagePage":12,"usage":1}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw12","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":3,"usagePage":1,"usage":128}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw13","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":1,"usage":2}
[UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw12","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":-1}
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw12","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":-1}
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Reenumerating devices
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkOperations] Waiting for bootloader
[UhkOperations] Flash security disable
[DeviceService] updateFirmware error {"message":"cannot open device with path /dev/hidraw10","stack":"TypeError: cannot open device with path /dev/hidraw10\n at new HID (/tmp/.mount_uhkpL4PkV/resources/app.asar/node_modules/node-hid/nodehid.js:49:17)\n at tr.open (/tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:516390)\n at /tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:516531\n at new Promise (<anonymous>)\n at tr.sendCommand (/tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:516501)\n at qt.flashSecurityDisable (/tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:513116)\n at Object.updateRightFirmwareWithKboot (/tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:626049)\n at async Fr.updateFirmware (/tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:528905)\n at async ar.process (/tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:519787)"}
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6123","path":"/dev/hidraw10","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2 Bootloader","release":2,"interface":0,"usagePage":65280,"usage":1}
[DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected at /tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:620005 at new Promise (<anonymous>) at Object.write (/tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:619939) at Object.getDeviceState (/tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:622822) at Object.waitUntilKeyboardBusy (/tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:632084) at Fr.getHardwareModules (/tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:526001) at Fr.updateFirmware (/tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:530614) at async ar.process (/tmp/.mount_uhkpL4PkV/resources/app.asar/electron-main.js:2:519787)
[DeviceService] start poll UHK Device
cannot open device with path /dev/hidraw10
```

**Comment by mondalaci** [comment]
@ert78gb Any ideas?

**Comment by ert78gb** [comment]
Looks like the bootloader can't accept the connection while Agent tried to disable the flash write protection. My assumption is Agent did not start the communication with the bootloader within 5 sec.
Agent does not show timestamp but the logs contain.

@sashs could you send the agent logs from the `~/.config/uhk-agent/logs/` folder.

**Comment by sashs** [comment]
Sure, email?

**Comment by ert78gb** [comment]
you could send to ert78gb@gmail.com

**Comment by sashs** [comment]
Done

**Comment by ert78gb** [comment]
Something else the issue because Agent starts the communication with the UHK within 2 sec.

I need the kboot communication logs too.
You have to start the agent from terminal. The `kboot` component will log to the standard output and error so please run the `DEBUG=kboot* ./UHK-Agent-filename 2>&1 > agent.log` command please replace the `./UHK-Agent-filename` with your Agent file name

**Comment by sashs** [comment]
done

**Comment by ert78gb** [comment]
sorry, I shared a wrong command please use the `&>` instead of `2>&1`

**Comment by ert78gb** [comment]
I got it. Everything looks good from the logs. Agent can't communicate with the bootloader.

Earlier we experienced it when the UHK did not connect directly to the workstation.
Does UHK directly connect to your notebook?

Please try with other USB port and try to restart your machine. We don't now why but few times it helps even if you use Linux :)

**Comment by sashs** [comment]
I tried several ports. I will try it again after a reboot. "Have you tried turn it off and on again" :)

**Comment by ert78gb** [comment]
If the above things don't help please try to remove every other USB device too. I know it cumbersome but we have to exclude interferences. And please close every keyboard monitoring/manipulator software if you use

**Comment by sashs** [comment]
Rebooting the system solved the problem. Thank you!
