### ISSUE TITLE
Agent 2.1.1 is not working on RHEL 8 and clones

### ISSUE THREAD

**Issue by rf-triegel** [UltimateHackingKeyboard/agent#1961]
Something in the build or in its pre-built dependencies is requiring a libstdc++ that's newer than what's available on RHEL 8 and clones.  Starting Agent fails to find the keyboard and shows this error message:

[DeviceService] Device connection state query error Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.WkQkgE)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/tmp/.mount_UHK.AgtCaFi7/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_UHK.AgtCaFi7/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)

3.4.25 is the latest that libstdc++ on RHEL8 has.  Agent 1.8.something did work.
I've also tried building Agent on my distro, but this leads to a similar error, so maybe it's picking up a binary dependency that is built for newer distros only.

**Comment by ert78gb** [comment]
yes, node-hid has been built with newer glibc.

If you would like to build agent from source then follow the following steps

- install node 16.17.1
Run the following commandin the root folder of the repository
- `npm run clean` 
- `npm install`
- `npm run build`
- `npm rebuild`
- `cd packages/uhk-agent && npm rebuild && cd -`
- `npm run electron`

I can't guaranteed it will work, but `npm rebuild` is the command that (re)build binary dependencies from source

**Comment by rf-triegel** [comment]
Thanks, but this yields the same error: [DeviceService] Device connection state query error Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by <...snip...>/agent/packages/uhk-agent/dist/node_modules/node-hid/build/Release/HID_hidraw.node)
