### ISSUE TITLE
UHK 60 V1: Couldn't connect to the "Left keyboard half".

### ISSUE THREAD

**Issue by migxmac** [UltimateHackingKeyboard/agent#2001]
While attempting to update my UHK 60 V1 firmware to 9.2.2 with the latest version of agent (2.1.2) the left hand side stopped updating and I saw the following in the firmware console:

```
Start flashing firmware
[DeviceService] Operating system: Linux 6.2.6-76060206-generic x64
[DeviceService] Agent version: 2.1.2
[DeviceService] New firmware version: 9.2.2
[DeviceService] New firmware user config version: 5.1.0
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
[DeviceService] UHK Device firmware upgrade starts: {"id":1,"name":"UHK 60 v1","vendorId":"0x1D50","keyboardPid":"0x6122","bootloaderPid":"0x6120","buspalPid":"0x6121"}
[DeviceService] Device right firmware version: 9.2.2
Skip right firmware upgrade.
[DeviceService] Left module firmware version:  null
[UhkOperations] Start flashing "Left keyboard half" module firmware
[UhkHidDevice] Start reenumeration, mode: NormalKeyboard, timeout: 5000ms
[UhkHidDevice] Reenumerating devices
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Left keyboard half" module, and keep reconnecting it until you see this message.
[UhkOperations] Couldn't connect to the "Left keyboard half".
[DeviceService] updateFirmware error {"message":"[UhkOperations] Couldn't connect to the \"Left keyboard half\".","stack":"Error: [UhkOperations] Couldn't connect to the \"Left keyboard half\".\n    at Object.updateModuleWithKboot (/tmp/.mount_UHK.AgtDi0Ny/resources/app.asar/electron-main.js:2:596880)\n    at async Xr.updateFirmware (/tmp/.mount_UHK.AgtDi0Ny/resources/app.asar/electron-main.js:2:497745)\n    at async mr.process (/tmp/.mount_UHK.AgtDi0Ny/resources/app.asar/electron-main.js:2:485912)"}
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
[DeviceService] start poll UHK Device
[UhkOperations] Couldn't connect to the "Left keyboard half".

```
I reviewed and attempted the recovery steps documented [here](https://ultimatehackingkeyboard.com/knowledgebase?q=brick) to no avail.

I reviewed previous issues in github and attempted the recommendations there as well, including disconnecting the cable and placing the keyboard halves together, then repeatedly removing and connecting the halves during the firmware update. I partially disassembled the left hand side so that I could short the reset pins, tried different cables, different locations, different operating systems (MacOS, Linux). 

Any other suggestions?

**Comment by mondalaci** [comment]
Please contact us at support at ultimatehackingkeyboard dot com
