### ISSUE TITLE
UHK Agent doesn't detect UHK after update

### ISSUE THREAD

**Issue by dndln** [UltimateHackingKeyboard/agent#2148]
Hi there,

After updating to "UHK.Agent-3.2.2-linux-x86_64.AppImage" on Ubuntu 20.04, the keyboard is no longer detected.

I get:

12:39:18.762 › [DeviceService] Device connection state query error Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.org.chromium.Chromium.0GoqWJ)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2131)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2358)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at bindings (/tmp/.mount_UHK.Ag8oW57J/resources/[app.asar/node_modules/bindings/bindings.js:112:48](http://app.asar/node_modules/bindings/bindings.js:112:48))
    at loadBinding (/tmp/.mount_UHK.Ag8oW57J/resources/[app.asar/node_modules/node-hid/nodehid.js:19:46](http://app.asar/node_modules/node-hid/nodehid.js:19:46))

My GLIBC version is 2.31:
ldd (Ubuntu GLIBC 2.31-0ubuntu9.14) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

How would I update my glibc, or can I downgrade to the previous version of Agent?

**Comment by mondalaci** [comment]
@ert78gb Would you look into this?

**Comment by ert78gb** [comment]
The reason is the `GLIBCXX_3.4.26 not found`. 

More details: https://github.com/UltimateHackingKeyboard/agent/issues/1961

Glibc is the "core" of the  operation system. Very risky to change it so I don't recommend any way to do it. I recommend to upgrade your operating system.

You can download earlier version of the Agent from the release [page](https://github.com/UltimateHackingKeyboard/agent/releases).

You can also try to build agent on your machine as described in https://github.com/UltimateHackingKeyboard/agent/issues/1961#issuecomment-1400898136. The comment is old but still relevant. You can find the required node.js version in the `.nvmrc` file in the root directory of the git repo.

**Comment by mondalaci** [comment]
I'm closing this issue, but feel free to follow up.

**Comment by ert78gb** [comment]
@dndln `node-hid`  released a new version that maybe support older version of GLIBC. If you have time please test the https://github.com/UltimateHackingKeyboard/agent/actions/runs/7533700761?pr=2162 version?

**Comment by dndln** [comment]
@ert78gb Hi, I just tested and it works, thanks! I was using 3.2.1 before but now can use 3.2.2 :)

**Comment by ert78gb** [comment]
thank you for the quick feedback
