### ISSUE TITLE
Unable to Recover Bricked Key Cluster

### ISSUE THREAD

**Issue by Jeremy-Gebhart** [UltimateHackingKeyboard/agent#2271]
Per the instructions in Agent, after trying many times to recover my unusable Key Cluster (instructions followed from https://ultimatehackingkeyboard.com/repair/unbricking-module) directly connected via both USB and USB-C to the laptop, I'm creating a github issue with the logs from the update attempt included. Using current Agent version, and keyobard halves are up to date.

```
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
[DeviceService] UHK Module recovery starts: {"id":2,"name":"UHK 60 v2","vendorId":"0x1D50","keyboardPid":"0x6124","bootloaderPid":"0x6123","buspalPid":"0x6121"}
[DeviceService] UHK Module:  {"id":2,"name":"Key cluster","configPath":"/add-on/key-cluster","slotId":2,"i2cAddress":32,"firmwareUpgradeSupported":true}
[UhkOperations] Start flashing "Key cluster" module firmware
[UhkHidDevice] Start reenumeration, mode: NormalKeyboard, timeout: 5000ms
[UhkHidDevice] Reenumerating devices
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceOperation] Cannot ping the bootloader. Please remove the "Key cluster" module, and keep reconnecting it until you see this message.
[UhkOperations] Couldn't connect to the "Key cluster".
[DeviceService] Module recovery error {"message":"[UhkOperations] Couldn't connect to the \"Key cluster\".","stack":"Error: [UhkOperations] Couldn't connect to the \"Key cluster\".\n    at Object.updateModuleWithKboot (C:\\Users\\gebha\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:611647)\n    at async li.recoveryModule (C:\\Users\\gebha\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:508388)\n    at async Cr.process (C:\\Users\\gebha\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:477965)"}
[UhkHidDevice] Available devices unchanged
[UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"\\\\?\\HID#VID_1D50&PID_6124&MI_04#7&523f451&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":65280,"usage":1}
[DeviceOperation] right module deviceProtocolVersion: 4.10.0
[DeviceOperation] Read "leftHalf" version information
[DeviceOperation] Read "leftHalf" repo information
[DeviceOperation] Read "leftHalf" firmware checksum
[DeviceService] start poll UHK Device
```

**Comment by mondalaci** [comment]
I'm afraid we have to recall your key cluster module. Please [contact us](https://ultimatehackingkeyboard.com/contact-us).
