### ISSUE TITLE
Negative values in "Trigger safety margin" breaks saving to keyboard

### ISSUE THREAD

**Issue by jay7x** [UltimateHackingKeyboard/agent#2317]
When "Trigger safety margin" is negative on the "Typing behavior" page, UHK Agent doesn't show "Save to keyboard" button (Ctrl+S doesn't work also). Saving cannot be recovered with making it positive again. Agent restart helps though.

Console output:
```
08:11:13.586 › RangeError: "value" argument is out of bounds
    at mt (file:///tmp/.mount_uhk-agO3EFMr/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:40010)
    at h.writeUint16LE.h.writeUInt16LE (file:///tmp/.mount_uhk-agO3EFMr/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:45441)
    at t.writeUInt16 (file:///tmp/.mount_uhk-agO3EFMr/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:677107)
    at Jt.toBinary (file:///tmp/.mount_uhk-agO3EFMr/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:717597)
    at Jt.recalculateConfigurationLength (file:///tmp/.mount_uhk-agO3EFMr/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:718651)
    at file:///tmp/.mount_uhk-agO3EFMr/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:1988853
    at ve (file:///tmp/.mount_uhk-agO3EFMr/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:2180988)
    at ge (file:///tmp/.mount_uhk-agO3EFMr/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:2180914)
    at E._next (file:///tmp/.mount_uhk-agO3EFMr/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:2157587)
    at ve.next (file:///tmp/.mount_uhk-agO3EFMr/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:2129587)
```

**Comment by mondalaci** [comment]
Thanks for reporting! I can reproduce this issue, and we'll fix it.
