### ISSUE TITLE
Agent fails to update firmware on ArchLinux

### ISSUE THREAD

**Issue by opie4624** [UltimateHackingKeyboard/agent#539]
From Agent v1.0.3
```
Start flashing firmware
[23:10:00.814] [UhkOperations] Start flashing right firmware
[23:10:00.815] [UhkHidDevice] Start reenumeration, mode: Bootloader
[23:10:00.925] [UhkHidDevice] Available devices: [ { vendorId: 7504, productId: 24866, path: '0003:003b:00', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 0 }, { vendorId: 7504, productId: 24866, path: '0003:003b:01', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 1 }, { vendorId: 7504, productId: 24866, path: '0003:003b:02', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 2 }, { vendorId: 7504, productId: 24866, path: '0003:003b:03', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 3 }, { vendorId: 7504, productId: 24866, path: '0003:003b:04', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 4 }, { vendorId: 8526, productId: 4, path: '0003:0036:00', release: 260, interface: 0 }, { vendorId: 8526, productId: 4, path: '0003:0036:01', release: 260, interface: 1 }, { vendorId: 8526, productId: 4, path: '0003:0036:02', release: 260, interface: 2 }, { vendorId: 8526, productId: 4, path: '0003:0036:03', release: 260, interface: 3 } ]
[23:10:00.933] [UhkHidDevice] Used device: { vendorId: 7504, productId: 24866, path: '0003:003b:00', manufacturer: 'Ultimate Gadget Laboratories', product: 'Ultimate Hacking Keyboard', release: 257, interface: 0 }
[23:10:00.933] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[23:10:00.934] [UhkHidDevice] USB[W]: 01 00 88 13 00 00
[23:10:02.194] [UhkHidDevice] reenumeration devices up
[23:10:02.194] [UhkHidDevice] Device communication closing.
[23:10:02.194] [UhkHidDevice] Device communication closed.
[23:10:02.195] [blhost] RUN: /tmp/.mount_UHK.AguGy9ad/app/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[23:10:02.230] [blhost] STDOUT: Error: UsbHidPeripheral() cannot open USB HID device (vid=0x1d50, pid=0x6120, sn=).
[23:10:02.234] [blhost] EXIT_CODE: 1
[23:10:02.235] [blhost] FINISHED: 1
[23:10:02.241] [DeviceService] updateFirmware error { message: 'blhost error code:1', stack: 'Error: blhost error code:1\n at finish (/tmp/.mount_UHK.AguGy9ad/app/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n at ChildProcess.childProcess.on.code (/tmp/.mount_UHK.AguGy9ad/app/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n at emitTwo (events.js:106:13)\n at ChildProcess.emit (events.js:194:7)\n at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)' }
[23:10:02.243] [blhost] CLOSE_CODE: 1
blhost error code:1
```

**Comment by mondalaci** [comment]
Please specify your exact OS to solve this.

**Comment by mondalaci** [comment]
Sorry, I totally missed the title. Let me figure this out.

**Comment by mondalaci** [comment]
Do you have the [UHK udev rule](https://github.com/UltimateHackingKeyboard/agent/blob/216793bbb8e53e8489228cba32b985ab5d0d5ce9/rules/50-uhk60.rules) installed in `/etc/udev/rules.d`? If no, please copy it, and reload udev according to [setup-rules.sh](https://github.com/UltimateHackingKeyboard/agent/blob/216793bbb8e53e8489228cba32b985ab5d0d5ce9/rules/setup-rules.sh).

If it's still not working, can you see the bootloader appearing in your `dmesg` log? You should see something like this:

```
[29594.379256] usb 2-4.4.4.4.4: new full-speed USB device number 48 using xhci_hcd
[29594.492495] usb 2-4.4.4.4.4: New USB device found, idVendor=1d50, idProduct=6120
[29594.492498] usb 2-4.4.4.4.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[29594.492499] usb 2-4.4.4.4.4: Product: UHK Bootloader
[29594.492500] usb 2-4.4.4.4.4: Manufacturer: Ultimate Gadget Laboratories
[29594.494171] hid-generic 0003:1D50:6120.0069: hiddev6,hidraw10: USB HID v1.00 Device [Ultimate Gadget Laboratories UHK Bootloader] on usb-0000:00:14.0-4.4.4.4.4/input0
```

**Comment by mondalaci** [comment]
@opie4624 Please let me know whether you managed to resolve this.

**Comment by opie4624** [comment]
I had the udev rule setup when I reported this, but I'm on hold for further testing due to #546

**Comment by opie4624** [comment]
dmesg logs from an update:
```
[262966.318573] usb 3-2: USB disconnect, device number 12
[262966.815182] usb 3-2: new full-speed USB device number 13 using xhci_hcd
[262966.957328] hid-generic 0003:1D50:6120.002A: hiddev2,hidraw4: USB HID v1.00 Device [Ultimate Gadget Laboratories UHK Bootloader] on usb-0000:00:14.0-2/input0
[262971.328354] usb 3-2: USB disconnect, device number 13
[262971.621797] usb 3-2: new full-speed USB device number 14 using xhci_hcd
[262971.764969] hid-generic 0003:1D50:6122.002B: hiddev2,hidraw4: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-2/input0
[262971.766338] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.1/0003:1D50:6122.002C/input/input43
[262971.822751] hid-generic 0003:1D50:6122.002C: input,hidraw5: USB HID v1.10 Keyboard [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-2/input1
[262971.823774] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.2/0003:1D50:6122.002D/input/input44
[262971.879227] hid-generic 0003:1D50:6122.002D: input,hidraw6: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-2/input2
[262971.880372] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.3/0003:1D50:6122.002E/input/input45
[262971.935865] hid-generic 0003:1D50:6122.002E: input,hidraw7: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-2/input3
[262971.937890] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.4/0003:1D50:6122.002F/input/input46
[262971.992520] hid-generic 0003:1D50:6122.002F: input,hidraw8: USB HID v1.10 Mouse [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-2/input4
[262979.157500] usb 3-2: USB disconnect, device number 14
[262980.808241] usb 3-2: new full-speed USB device number 15 using xhci_hcd
[262980.953523] hid-generic 0003:1D50:6122.0030: hiddev2,hidraw4: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-2/input0
[262980.954961] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.1/0003:1D50:6122.0031/input/input47
[262981.013363] hid-generic 0003:1D50:6122.0031: input,hidraw5: USB HID v1.10 Keyboard [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-2/input1
[262981.014761] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.2/0003:1D50:6122.0032/input/input48
[262981.069094] hid-generic 0003:1D50:6122.0032: input,hidraw6: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-2/input2
[262981.070308] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.3/0003:1D50:6122.0033/input/input49
[262981.125789] hid-generic 0003:1D50:6122.0033: input,hidraw7: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-2/input3
[262981.127626] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.4/0003:1D50:6122.0034/input/input50
[262981.182258] hid-generic 0003:1D50:6122.0034: input,hidraw8: USB HID v1.10 Mouse [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-2/input4
```

**Comment by mondalaci** [comment]
So does the update work well now the your left half has been unbricked? (We'll integrate the unbricking part to Agent.) If so, I'll close this issue.

**Comment by mondalaci** [comment]
Obsoleted by #556.
