### ISSUE TITLE
Handle privilege escalation gracefully even without PolicyKit

### ISSUE THREAD

**Issue by FatBoyXPC** [UltimateHackingKeyboard/agent#544]
When I try to run the agent, I get this thing about using permissions. I click "Set up permissions" and it appears as though the error in the red alert at the top right is trying to output a javascript object, rather than a string: 
![image](https://user-images.githubusercontent.com/744962/34595764-5fa535ce-f1a8-11e7-8c2c-7cfa01e9043f.png)

**Comment by mondalaci** [comment]
Thanks for reporting! Just checked Agent 1.0.4 on Linux mint 18.3 and it works as expected.

1. Which distribution are you using?
2. Can you see a privilege escalation window popping up when clicking on the "Set up premissions" button?
3. Would you attach the output of the console?

**Comment by FatBoyXPC** [comment]
Hmm, that's interesting.

1) Arch linux, updated my OS before running agent.
2) I don't, maybe that's what is causing this problem? I'm using XMonad as my window manager, this might have something to do with it.
3) Thanks for reminding me to look at that ,I just needed sudo!

**Comment by mondalaci** [comment]
I'm reopening this, because it should always work out of the box. Would you please share your console output? Using sudo is not a secure way, and after setting this up, you shouldn't need it anymore.

**Comment by FatBoyXPC** [comment]
Here's my terminal while I run the appimage/script:

```
➜  ~ ./Downloads/UHK.Agent-1.0.4-linux-x86_64.AppImage
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_UHK.AghRCY0d/AppRun.
[22:33:13.013] [info] [Electron Main] Create new window.
[22:33:13.017] [info] [Electron Main] packagesDir: /tmp/.mount_UHK.AghRCY0d/app/resources
[22:33:13.123] [debug] [UhkHidDevice] Available devices: [ { vendorId: 7504,
    productId: 24866,
    path: '0001:0007:00',
    release: 257,
    interface: 0 },
  { vendorId: 7504,
    productId: 24866,
    path: '0001:0007:01',
    release: 257,
    interface: 1 },
  { vendorId: 7504,
    productId: 24866,
    path: '0001:0007:02',
    release: 257,
    interface: 2 },
  { vendorId: 7504,
    productId: 24866,
    path: '0001:0007:03',
    release: 257,
    interface: 3 },
  { vendorId: 7504,
    productId: 24866,
    path: '0001:0007:04',
    release: 257,
    interface: 4 } ]
[22:33:13.128] [error] [UhkHidDevice] Can not create device: Error: cannot open device with path 0001:0007:00
    at new HID (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/node_modules/node-hid/nodehid.js:24:17)
    at UhkHidDevice.connectToDevice (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:212:1)
    at UhkHidDevice.getDevice (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:193:1)
    at UhkHidDevice.hasPermission (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:38:1)
    at SafeSubscriber.pollTimer$.Observable_1.Observable.interval.startWith.map.distinctUntilChanged.do [as _next] (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/src/services/device.service.ts:149:48)
    at SafeSubscriber.__tryOrSetError (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/~/rxjs/Subscriber.js:247:1)
    at SafeSubscriber.next (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/~/rxjs/Subscriber.js:187:1)
    at Subscriber._next (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/~/rxjs/Subscriber.js:125:1)
    at Subscriber.next (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/~/rxjs/Subscriber.js:89:1)
    at DoSubscriber._next (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/~/rxjs/operator/do.js:83:1)
    at DoSubscriber.Subscriber.next (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/~/rxjs/Subscriber.js:89:1)
    at DistinctUntilChangedSubscriber._next (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/~/rxjs/operator/distinctUntilChanged.js:103:1)
    at DistinctUntilChangedSubscriber.Subscriber.next (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/~/rxjs/Subscriber.js:89:1)
    at MapSubscriber._next (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/~/rxjs/operator/map.js:83:1)
    at MapSubscriber.Subscriber.next (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/~/rxjs/Subscriber.js:89:1)
    at MergeAllSubscriber.OuterSubscriber.notifyNext (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/~/rxjs/OuterSubscriber.js:19:1)

[22:33:13.131] [debug] [UhkHidDevice] Device communication closing.
[22:33:13.131] [info] [DeviceService] Device connection state changed to: { connected: true, hasPermission: false }
[22:33:13.133] [debug] [DeviceService] init success
[22:33:13.134] [info] [AppUpdateService] init success
[22:33:13.134] [info] [AppService] init success
[22:33:13.134] [info] [SudoService] App root dir:  /tmp/.mount_UHK.AghRCY0d/app/resources
[22:33:13.830] [info] [ '[AppRendererService] init success ' ]
[22:33:13.853] [info] [ '[DeviceRendererService] init success ' ]
[22:33:13.856] [info] [ 'Renderer appStart effect start' ]
[22:33:13.858] [debug] [AppUpdateService] check for update at startup: { checkForUpdate: false,
  autoUpdateSettings: { checkForUpdateOnStartUp: false, usePreReleaseUpdate: false } }
[22:33:13.859] [info] [ '[AppRendererService] getAppStartInfo' ]
[22:33:13.860] [info] [AppService] getAppStartInfo
[22:33:13.861] [info] [ 'Renderer appStart effect end' ]
[22:33:13.862] [debug] [UhkHidDevice] Available devices: [ { vendorId: 7504,
    productId: 24866,
    path: '0001:0007:00',
    release: 257,
    interface: 0 },
  { vendorId: 7504,
    productId: 24866,
    path: '0001:0007:01',
    release: 257,
    interface: 1 },
  { vendorId: 7504,
    productId: 24866,
    path: '0001:0007:02',
    release: 257,
    interface: 2 },
  { vendorId: 7504,
    productId: 24866,
    path: '0001:0007:03',
    release: 257,
    interface: 3 },
  { vendorId: 7504,
    productId: 24866,
    path: '0001:0007:04',
    release: 257,
    interface: 4 } ]
[22:33:13.864] [error] [UhkHidDevice] Can not create device: Error: cannot open device with path 0001:0007:00
    at new HID (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/node_modules/node-hid/nodehid.js:24:17)
    at UhkHidDevice.connectToDevice (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:212:1)
    at UhkHidDevice.getDevice (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:193:1)
    at UhkHidDevice.hasPermission (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:38:1)
    at AppService.<anonymous> (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/src/services/app.service.ts:35:53)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/electron-main.js:23704:58)
    at <anonymous>

[22:33:13.865] [debug] [UhkHidDevice] Device communication closing.
[22:33:13.865] [info] [AppService] getAppStartInfo response: { commandLineArgs: { addons: false, autoWriteConfig: false },
  deviceConnected: true,
  hasPermission: false,
  agentVersionInfo: 
   { version: '1.0.4',
     firmwareVersion: '8.0.0',
     deviceProtocolVersion: '4.0.0',
     moduleProtocolVersion: undefined,
     userConfigVersion: '4.0.0',
     hardwareConfigVersion: '1.0.0' } }
[22:33:13.971] [info] [ '[AppRendererService] dispatch action',
  ProcessAppStartInfoAction {
    payload: 
     { agentVersionInfo: [Object],
       commandLineArgs: [Object],
       deviceConnected: true,
       hasPermission: false },
    type: '[app] process start info' } ]
[22:33:13.971] [debug] [ '[AppEffect][processStartInfo] payload:',
  { agentVersionInfo: 
     { deviceProtocolVersion: '4.0.0',
       firmwareVersion: '8.0.0',
       hardwareConfigVersion: '1.0.0',
       userConfigVersion: '4.0.0',
       version: '1.0.4' },
    commandLineArgs: { addons: false, autoWriteConfig: false },
    deviceConnected: true,
    hasPermission: false } ]
[22:33:17.510] [debug] [SudoService] Copy rules dir { src: '/tmp/.mount_UHK.AghRCY0d/app/resources/rules',
  dst: '/tmp/tmp-30317rsu18VHMQkOp' }
[22:33:17.511] [debug] [SudoService] Set privilege command:  sh /tmp/tmp-30317rsu18VHMQkOp/setup-rules.sh
[22:33:17.546] [error] [SudoService] Error when set privilege:  Error: No polkit authentication agent found.
    at /tmp/.mount_UHK.AghRCY0d/app/resources/app.asar/webpack:/~/sudo-prompt/index.js:132:1
    at ChildProcess.exithandler (child_process.js:224:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)

[22:33:17.550] [info] [ '[DeviceRendererService] dispatch action',
  '{"payload":{"error":{},"success":false},"type":"[device] set privilege on linux reply"}' ]
```

**Comment by mondalaci** [comment]
Thanks for the info! The

> [22:33:17.546] [error] [SudoService] Error when set privilege:  Error: No polkit authentication agent found.

message suggests that PolicyKit Authentication Agent is not present on your system. Normally, it's present on the vast majority of distributions, but Arch is clearly an exception.

@ert78gb Can we detect this failure from Agent? If so, I'll specify how to handle this case.

**Comment by FatBoyXPC** [comment]
@mondalaci so I just installed `polkit` on my system and now it works fine :) I wasn't sure what that authentication agent was when I saw it, which is why I ended up hitting sudo. A quick google search and I found that package I could install!

**Comment by mondalaci** [comment]
@FatBoyXPC Thanks for the follow-up! It's nice to see it working when polkit is installed. :) We'll handle this case regardless to make it work smoothly on all distributions.

**Comment by ert78gb** [comment]
@mondalaci Agent could catch the error message `No polkit authentication agent found.` and could do any action that you specify

**Comment by mondalaci** [comment]
@ert78gb Ok, thanks! Please add the following content below the "Set up permissions" button:
 
> Link styled text: "What will this do?" *<--- Make this link disappear if clicked or if permission setup failed.*
> 
> Agent wasn't able to set up permissions. Please run the following as root to manually set up permissions: *<--- Only show the "Agent wasn't able to set up permissions. " part if permission setup failed.*
> 
> *Only show the following if permission setup failed or the "What will this do" link was clicked.*
> 
> ```
> cat <<EOF >/etc/udev/rules.d/50-uhk60.rules
> # Ultimate Hacking Keyboard rules
> # These are the udev rules for accessing the USB interfaces of the UHK as non-root users.
> # Copy this file to /etc/udev/rules.d and physically reconnect the UHK afterwards.
> SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", MODE:="0666"
> EOF
> udevadm trigger
> udevadm settle
> ```
>
> "Copy to clipboard" button
> "Retry" button

**Comment by ert78gb** [comment]
Does the Agent any feedback when "Copy to Clipboard" success?

**Comment by mondalaci** [comment]
Reopening because there's a single case to be tested: when policykit is not installed on the system. I can't uninstall it because it's a hard dependency on Linux Mint.

**Comment by mondalaci** [comment]
@FatBoyXPC The freshly released [Agent 1.1.4](https://github.com/UltimateHackingKeyboard/agent/releases/tag/v1.1.4) should have this fixed.

The problem is, I can't test this because I use Linux Mint, and policykit is a hard dependency of many system packages. Looks like you'd be able to test it on Arch Linux. Would you be able to uninstall policykit and give it a try, please?

**Comment by FatBoyXPC** [comment]
@mondalaci I can't :( Apparently I had a bunch of unmet dependencies before I installed this, which is strange:

```sh
➜  ~ _ pacman -R polkit 
[sudo] password for james: 
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: colord: removing polkit breaks dependency 'polkit'
:: gconf: removing polkit breaks dependency 'polkit'
:: networkmanager: removing polkit breaks dependency 'polkit'
:: rtkit: removing polkit breaks dependency 'polkit'
:: udisks2: removing polkit breaks dependency 'polkit'
➜  ~ 
```

I'll talk to a friend with an almost identical arch install and see if he has polkit installed, and if not, what I can do to remove it.

**Comment by mondalaci** [comment]
@FatBoyXPC Much appreciated!

**Comment by FatBoyXPC** [comment]
Well, my friend also has `polkit` installed and it's a dependency of one of his packages he has installed. So, I'm guessing one of the above (or all?) packages changed to depend on `polkit` at some time. Hard to tell at this point :disappointed:

**Comment by mondalaci** [comment]
Ok, thanks for looking into it! I think it Linux distributions that do not depend heavily on policykit should be very rare nowadays, so I'm closing this issue now. Chances are high the fix works in all environments.
