### ISSUE TITLE
Agent isn't recovering a bricked left half

### ISSUE THREAD

**Issue by opie4624** [UltimateHackingKeyboard/agent#546]
Agent log attached
[log.log](https://github.com/UltimateHackingKeyboard/agent/files/1609592/log.log)

**Comment by mondalaci** [comment]
Please clone and build the latest Agent, then disconnect the halves, merge them, and execute the following from the Agent root directory:

```
cd packages/usb
wget https://github.com/UltimateHackingKeyboard/firmware/releases/download/8.0.1/uhk-firmware-8.0.1-current-kboot-command.tar.bz2
./update-all-firmwares.js ./uhk-firmware-8.0.1-current-kboot-command.tar.bz2
```

This should unbrick your left half. Please let me know if it works, and if no, what is the output of the command.

**Comment by opie4624** [comment]
```
> ./update-all-firmwares.js ./uhk-firmware-8.0.1-current-kboot-command.tar.bz2
exec /Users/akraut/Code/uhk-agent/packages/usb/update-device-firmware.js /var/folders/sh/f5hyn4d14b1b996ms18mdxgm0000gn/T/tmp-205833aiPkANawkJ9/devices/uhk60-right/firmware.hex
exec /Users/akraut/Code/uhk-agent/packages/usb/reenumerate.js bootloader
Trying to reenumerate as bootloader...
UHK found, reenumerating as bootloader
bootloader is up
exec /Users/akraut/Code/uhk-agent/packages/usb/blhost/mac/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
Inject command 'flash-security-disable'
Successful generic response to command 'flash-security-disable'
Response status = 0 (0x0) Success.
exec /Users/akraut/Code/uhk-agent/packages/usb/blhost/mac/blhost --usb 0x1d50,0x6120 flash-erase-region 0xc000 475136
Inject command 'flash-erase-region'
Successful generic response to command 'flash-erase-region'
Response status = 0 (0x0) Success.
exec /Users/akraut/Code/uhk-agent/packages/usb/blhost/mac/blhost --usb 0x1d50,0x6120 flash-image /var/folders/sh/f5hyn4d14b1b996ms18mdxgm0000gn/T/tmp-205833aiPkANawkJ9/devices/uhk60-right/firmware.hex
Inject command 'flash-image'
Wrote 47896 bytes to address 0xc000
Successful generic response to command 'write-memory'
(1/2)100% Completed!
Successful generic response to command 'write-memory'
Wrote 32704 bytes to address 0x20000000
Successful generic response to command 'write-memory'
(2/2)100% Completed!
Successful generic response to command 'write-memory'
Response status = 0 (0x0) Success.
exec /Users/akraut/Code/uhk-agent/packages/usb/blhost/mac/blhost --usb 0x1d50,0x6120 reset
Inject command 'reset'
Successful generic response to command 'reset'
Response status = 0 (0x0) Success.
Firmware updated successfully.
exec /Users/akraut/Code/uhk-agent/packages/usb/reenumerate.js normalKeyboard
Trying to reenumerate as normalKeyboard...
UHK found, reenumerating as normalKeyboard
normalKeyboard is up
exec /Users/akraut/Code/uhk-agent/packages/usb/update-module-firmware.js leftHalf /var/folders/sh/f5hyn4d14b1b996ms18mdxgm0000gn/T/tmp-205833aiPkANawkJ9/modules/uhk60-left.bin
exec /Users/akraut/Code/uhk-agent/packages/usb/send-kboot-command-to-module.js ping leftHalf
exec /Users/akraut/Code/uhk-agent/packages/usb/jump-to-module-bootloader.js leftHalf
exec /Users/akraut/Code/uhk-agent/packages/usb/reenumerate.js buspal
Trying to reenumerate as buspal...
UHK found, reenumerating as buspal
buspal is up
exec /Users/akraut/Code/uhk-agent/packages/usb/blhost/mac/blhost --usb 0x1d50,0x6121 --buspal i2c,0x10,100k get-property 1
Inject pre-config command 'i2c'
Successful generic response to command 'i2c'
Response status = 0 (0x0) Success.
Inject command 'get-property'
sendCommandGetResponse.readPacket error 5.
Response status = 10004 (0x2714) No response packet from target device.
Retrying /Users/akraut/Code/uhk-agent/packages/usb/blhost/mac/blhost --usb 0x1d50,0x6121 --buspal i2c,0x10,100k get-property 1
exec /Users/akraut/Code/uhk-agent/packages/usb/blhost/mac/blhost --usb 0x1d50,0x6121 --buspal i2c,0x10,100k get-property 1
Inject pre-config command 'i2c'
Successful generic response to command 'i2c'
Response status = 0 (0x0) Success.
Inject command 'get-property'
sendCommandGetResponse.readPacket error 5.
Response status = 10004 (0x2714) No response packet from target device.
Retrying /Users/akraut/Code/uhk-agent/packages/usb/blhost/mac/blhost --usb 0x1d50,0x6121 --buspal i2c,0x10,100k get-property 1
exec /Users/akraut/Code/uhk-agent/packages/usb/blhost/mac/blhost --usb 0x1d50,0x6121 --buspal i2c,0x10,100k get-property 1
Inject pre-config command 'i2c'
Successful generic response to command 'i2c'
Response status = 0 (0x0) Success.
Inject command 'get-property'
sendCommandGetResponse.readPacket error 5.
Response status = 10004 (0x2714) No response packet from target device.
exec /Users/akraut/Code/uhk-agent/packages/usb/blhost/mac/blhost --usb 0x1d50,0x6121 --buspal i2c,0x10,100k flash-erase-all-unsecure
Inject pre-config command 'i2c'
Successful generic response to command 'i2c'
Response status = 0 (0x0) Success.
Inject command 'flash-erase-all-unsecure'
sendCommandGetResponse.readPacket error 5.
Response status = 10004 (0x2714) No response packet from target device.
/Users/akraut/Code/uhk-agent/packages/usb/node_modules/shelljs/src/common.js:417
      if (config.fatal) throw e;
                        ^

Error: exec: internal error
    at Object.error (/Users/akraut/Code/uhk-agent/packages/usb/node_modules/shelljs/src/common.js:128:27)
    at _exec (/Users/akraut/Code/uhk-agent/packages/usb/node_modules/shelljs/src/exec.js:292:12)
    at /Users/akraut/Code/uhk-agent/packages/usb/node_modules/shelljs/src/common.js:350:23
    at Object.<anonymous> (/Users/akraut/Code/uhk-agent/packages/usb/update-module-firmware.js:29:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
exec: internal error
```

**Comment by mondalaci** [comment]
You seem to be running an older Agent version because the script doesn't call `wait-for-kboot-idle.js`. Please pull and retry.

**Comment by opie4624** [comment]
My bad. I wasn't on `master`.

That recovered it successfully.

**Comment by opie4624** [comment]
Three times, I believe. It might have actually worked on the second one, but took a minute to reflect that. In the agent, maybe it makes sense to prompt each reconnection attempt?

**Comment by mondalaci** [comment]
It'd make sense to prompt upon every reconnection attempt, indeed, but that'd be a workaround. I'd rather like to make this bulletproof, so the update process will work on the first reconnection attempt.

This has been a definite step forward. Now the command line update scripts can unbrick bricked modules. I'll create relevant issues, and close this one.

**Comment by mondalaci** [comment]
Just created #556 and https://github.com/UltimateHackingKeyboard/firmware/issues/88 to further improve upon this one. Closing this issue.
