### ISSUE TITLE
Can't write config on Windows right after firmware update

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#596]
On Windows if I upgrade the firmware and right after that I try to save the configuration I get the following error:

```
[09:02:38.349] [debug] [DeviceOperation] USB[T]: Apply user configuration to keyboard
[09:02:38.350] [debug] [UhkHidDevice] USB[W]: 07
[09:02:38.362] [debug] [UhkHidDevice] USB[R]: 00 3e 11 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[09:02:38.362] [debug] [DeviceOperation] USB[T]: Write user configuration to EEPROM
[09:02:38.363] [debug] [UhkHidDevice] USB[W]: 08 01 02
[09:02:38.369] [debug] [UhkHidDevice] USB[R]: 04 4c 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[09:02:38.370] [error] [DeviceOperation] Transferring error Error: Communications error with UHK. Response code: 4
    at device.read (C:\Users\user\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:80:1)
 
[09:02:38.575] [debug] [UhkHidDevice] Device communication closing.
[09:02:38.577] [debug] [UhkHidDevice] Device communication closed.
[09:02:38.579] [error] [DeviceService] Transferring error Error: Communications error with UHK. Response code: 4
    at device.read (C:\Users\user\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:80:1)
 
[09:02:38.580] [debug] [UhkHidDevice] Device communication closing.
[09:02:38.584] [info] [ '[DeviceRendererService] dispatch action',
  '{"payload":{"error":{"message":"Communications error with UHK. Response code: 4"}},"type":"[device] save configuration reply"}' ]
```

If I restart Agent the rotating progress icon also goes forever. I have to disconnect USB and reconnect it to fix it.

This is only an issue on Windows. I only tested it on Windows 10 but probably other Windows versions are also affected.

**Comment by sad2project** [comment]
This bug is preventing me from saving changes. The only change so far that hasn't spun forever is just a copy of a keymap. Every step I take to alter that keymap won't save. Including just renaming it.

**Comment by mondalaci** [comment]
I've just tried to reproduce this issue with Agent 1.2.10 on Windows 10 multiple times by updating to firmware 8.4.5, and then saving my configuration. It worked every time, so I think it's resolved. If not, I'll reopen this issue.
