### ISSUE TITLE
Error on build with uhk-common/index.ts

### ISSUE THREAD

**Issue by stphnlwlsh** [UltimateHackingKeyboard/agent#609]
Just tried building fresh on my Mac.

```
> uhk-agent@1.1.4 build:electron /Users/stphnlwlsh/Development/3rdParty/agent
> cross-env AOT_BUILD=true run-s -sn build:electron:renderer build:electron:main


> uhk-agent@1.1.4 build:electron:renderer /Users/stphnlwlsh/Development/3rdParty/agent/package.json
> lerna exec --scope uhk-web npm run build:renderer 

lerna info version 2.9.0
lerna info scope uhk-web
Hash: f5758e2776ca48de0569                                                              
Version: webpack 3.11.0
Time: 41961ms
 22 assets
[./node_modules/raw-loader/index.js!./node_modules/postcss-loader/lib/index.js??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss] ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss 45.8 kB {styles} [built]
[./src/app/services/datastorage-repository.service.ts] ./src/app/services/datastorage-repository.service.ts 1.56 kB {main} [built]
[./src/app/services/ipc-common-renderer.ts] ./src/app/services/ipc-common-renderer.ts 454 bytes {main} [built]
[./src/app/shared.module.ts] ./src/app/shared.module.ts 10 kB {main} [built]
[./src/app/store/effects/index.ts] ./src/app/store/effects/index.ts 660 bytes {main} [built]
[./src/environments/environment.ts] ./src/environments/environment.ts 386 bytes {main} [built]
   [0] multi ./src/main-renderer.ts 28 bytes {main} [built]
[./src/main-renderer.ts] ./src/main-renderer.ts 365 bytes {main} [built]
[./src/polyfills.ts] ./src/polyfills.ts 2.7 kB {polyfills} [built]
[./src/renderer/services/electron-log.service.ts] ./src/renderer/services/electron-log.service.ts 3.46 kB {main} [built]
[./src/renderer/services/ipc-uhk-renderer.ts] ./src/renderer/services/ipc-uhk-renderer.ts 560 bytes {main} [built]
   [1] multi ./src/polyfills.ts 28 bytes {polyfills} [built]
   [2] multi ./node_modules/bootstrap/dist/css/bootstrap.min.css ./node_modules/nouislider/distribute/nouislider.min.css ./src/styles.scss 52 bytes {styles} [built]
[./src/renderer/uhk-renderer.module.ts] ./src/renderer/uhk-renderer.module.ts 2.67 kB {main} [built]
[./src/styles.scss] ./src/styles.scss 1.33 kB {styles} [built]
    + 826 hidden modules

ERROR in ../uhk-common/index.ts
Module build failed: Error: /Users/stphnlwlsh/Development/3rdParty/agent/packages/uhk-common/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/stphnlwlsh/Development/3rdParty/agent/packages/uhk-web/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/stphnlwlsh/Development/3rdParty/agent/packages/uhk-web/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
 @ ./src/renderer/uhk-renderer.module.ts 9:0-40
 @ ./src/main-renderer.ts
 @ multi ./src/main-renderer.ts
Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 1.06 kB {0} [built]
lerna ERR! exec Errored while executing 'npm run build:renderer' in 'uhk-web'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run build:renderer
lerna ERR!     at Promise.all.then.arr (/Users/stphnlwlsh/Development/3rdParty/agent/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: npm run build:renderer
    at Promise.all.then.arr (/Users/stphnlwlsh/Development/3rdParty/agent/node_modules/lerna/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  code: 2,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'npm run build:renderer',
  timedOut: false,
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uhk-agent@1.1.4 build:electron: `cross-env AOT_BUILD=true run-s -sn build:electron:renderer build:electron:main`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uhk-agent@1.1.4 build:electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stphnlwlsh/.npm/_logs/2018-04-12T18_35_33_542Z-debug.log
```

**Comment by ert78gb** [comment]
Is it the response of the ‘npm run build’ command ? After the npm install pls always build a whole repo and not just one package

**Comment by stphnlwlsh** [comment]
Sorry about that. Should have included the command as well. 

```
$ npm install

> uhk-agent@1.1.4 postinstall /Users/stphnlwlsh/Development/3rdParty/agent
> lerna bootstrap

lerna info version 2.9.0
lerna info Bootstrapping 6 packages
lerna info lifecycle preinstall
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna success Bootstrapped 6 packages
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.2.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-linux@1.8.3 (node_modules/app-builder-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-linux@1.8.3: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-win@1.8.3 (node_modules/app-builder-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-win@1.8.3: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-linux@1.7.2 (node_modules/dmg-builder/node_modules/app-builder-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-linux@1.7.2: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-win@1.7.2 (node_modules/dmg-builder/node_modules/app-builder-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-win@1.7.2: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
```

Then the next step on the instructions is `npm run build:electron`.

```
$ npm run build:electron

> uhk-agent@1.1.4 build:electron /Users/stphnlwlsh/Development/3rdParty/agent
> cross-env AOT_BUILD=true run-s -sn build:electron:renderer build:electron:main


> uhk-agent@1.1.4 build:electron:renderer /Users/stphnlwlsh/Development/3rdParty/agent/package.json
> lerna exec --scope uhk-web npm run build:renderer 

lerna info version 2.9.0
lerna info scope uhk-web
Hash: f5758e2776ca48de0569                                                              
Version: webpack 3.11.0
Time: 42672ms
 22 assets
[./node_modules/raw-loader/index.js!./node_modules/postcss-loader/lib/index.js??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss] ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss 45.8 kB {styles} [built]
[./src/app/services/datastorage-repository.service.ts] ./src/app/services/datastorage-repository.service.ts 1.56 kB {main} [built]
[./src/app/services/ipc-common-renderer.ts] ./src/app/services/ipc-common-renderer.ts 454 bytes {main} [built]
[./src/app/shared.module.ts] ./src/app/shared.module.ts 10 kB {main} [built]
[./src/app/store/effects/index.ts] ./src/app/store/effects/index.ts 660 bytes {main} [built]
[./src/environments/environment.ts] ./src/environments/environment.ts 386 bytes {main} [built]
   [0] multi ./src/main-renderer.ts 28 bytes {main} [built]
[./src/main-renderer.ts] ./src/main-renderer.ts 365 bytes {main} [built]
[./src/polyfills.ts] ./src/polyfills.ts 2.7 kB {polyfills} [built]
[./src/renderer/services/electron-log.service.ts] ./src/renderer/services/electron-log.service.ts 3.46 kB {main} [built]
[./src/renderer/services/ipc-uhk-renderer.ts] ./src/renderer/services/ipc-uhk-renderer.ts 560 bytes {main} [built]
   [1] multi ./src/polyfills.ts 28 bytes {polyfills} [built]
   [2] multi ./node_modules/bootstrap/dist/css/bootstrap.min.css ./node_modules/nouislider/distribute/nouislider.min.css ./src/styles.scss 52 bytes {styles} [built]
[./src/renderer/uhk-renderer.module.ts] ./src/renderer/uhk-renderer.module.ts 2.67 kB {main} [built]
[./src/styles.scss] ./src/styles.scss 1.33 kB {styles} [built]
    + 826 hidden modules

ERROR in ../uhk-common/index.ts
Module build failed: Error: /Users/stphnlwlsh/Development/3rdParty/agent/packages/uhk-common/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/stphnlwlsh/Development/3rdParty/agent/packages/uhk-web/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/stphnlwlsh/Development/3rdParty/agent/packages/uhk-web/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
 @ ./src/renderer/uhk-renderer.module.ts 9:0-40
 @ ./src/main-renderer.ts
 @ multi ./src/main-renderer.ts
Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 1.06 kB {0} [built]
lerna ERR! exec Errored while executing 'npm run build:renderer' in 'uhk-web'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run build:renderer
lerna ERR!     at Promise.all.then.arr (/Users/stphnlwlsh/Development/3rdParty/agent/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: npm run build:renderer
    at Promise.all.then.arr (/Users/stphnlwlsh/Development/3rdParty/agent/node_modules/lerna/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  code: 2,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'npm run build:renderer',
  timedOut: false,
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uhk-agent@1.1.4 build:electron: `cross-env AOT_BUILD=true run-s -sn build:electron:renderer build:electron:main`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uhk-agent@1.1.4 build:electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stphnlwlsh/.npm/_logs/2018-04-13T12_34_22_480Z-debug.log
```

@ert78gb are you saying to just do `npm run build` without specifying `electron` ? 

That worked, so maybe an addition to the instructions to help nodejs newbies like me? 😄

**Comment by ert78gb** [comment]
Ok Thx we will fix the introduction

**Comment by stphnlwlsh** [comment]
Thanks!
