### ISSUE TITLE
Issue Building uhk-web On Ubuntu 16.04

### ISSUE THREAD

**Issue by maxywb** [UltimateHackingKeyboard/agent#622]
I'm trying to build the 1.2.0 release on my Ubuntu 16.04 machine and I'm getting `npm run build` failures from the `uhk-web` package. This is a released version so I'm wondering if my version of `node` is maybe out of date? Is there a dependency on a particular version of `node`? The build instructions are unclear on this.

Source version:
```
 $ git branch -vvv
* (HEAD detached at cac1115) cac1115 Update firmware version to 8.2.0
  master c815de0 [origin/master] Edit phrasing: "... layer by *tapping* this key"
```
Npm version:
```
 $ npm --version
3.10.10
```
Node version:
```
 $ node --version
v6.14.2
```
Build output:
```
 $ npm run build

> uhk-agent@1.2.0 build /home/max/prog/src/agent
> run-s build:common build:usb build:web build:electron


> uhk-agent@1.2.0 build:common /home/max/prog/src/agent
> lerna exec --scope uhk-common npm run build

lerna info version 2.9.0
lerna info scope uhk-common

> uhk-common@1.0.0 build /home/max/prog/src/agent/packages/uhk-common
> run-s tsc copy:*


> uhk-common@1.0.0 tsc /home/max/prog/src/agent/packages/uhk-common
> tsc


> uhk-common@1.0.0 copy:scancodes /home/max/prog/src/agent/packages/uhk-common
> copyfiles ./src/config-serializer/config-items/scancodes.json dist


> uhk-common@1.0.0 copy:secondary-roles /home/max/prog/src/agent/packages/uhk-common
> copyfiles ./src/config-serializer/config-items/secondaryRole.json dist


> uhk-agent@1.2.0 build:usb /home/max/prog/src/agent
> lerna exec --scope uhk-usb npm run build

lerna info version 2.9.0
lerna info scope uhk-usb

> uhk-usb@1.0.0 build /home/max/prog/src/agent/packages/uhk-usb
> tsc


> uhk-agent@1.2.0 build:web /home/max/prog/src/agent
> lerna exec --scope uhk-web npm run build

lerna info version 2.9.0
lerna info scope uhk-web

> uhk-web@1.0.0 build /home/max/prog/src/agent/packages/uhk-web
> ng build --prod --aot --base-href=""

Date: 2018-05-01T19:18:00.964Z                                                       
Hash: 9c50730b35966af7d320
Time: 8823ms
chunk {scripts} scripts.5d86a87e7ec2063c3d78.bundle.js (scripts) 135 kB [initial] [rendered]
chunk {0} styles.6f05252de6722e46563b.bundle.css (styles) 154 kB [initial] [rendered]
chunk {1} polyfills.997d8cc03812de50ae67.bundle.js (polyfills) 84 bytes [initial] [rendered]
chunk {2} main.a445506a31041b598841.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in node_modules/ng2-select2/ng2-select2.component.d.ts(12,14): error TS2304: Cannot find name 'Select2Options'.
src/app/components/popover/tab/keypress/keypress-tab.component.ts(25,14): error TS2304: Cannot find name 'Select2Options'.


npm ERR! Linux 4.4.0-121-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! uhk-web@1.0.0 build: `ng build --prod --aot --base-href=""`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uhk-web@1.0.0 build script 'ng build --prod --aot --base-href=""'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uhk-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build --prod --aot --base-href=""
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uhk-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uhk-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/max/prog/src/agent/packages/uhk-web/npm-debug.log
lerna ERR! exec Errored while executing 'npm run build' in 'uhk-web'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run build
lerna ERR!     at Promise.all.then.arr (/home/max/prog/src/agent/node_modules/lerna/node_modules/execa/index.js:236:11)
{ Error: Command failed: npm run build
    at Promise.all.then.arr (/home/max/prog/src/agent/node_modules/lerna/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 1,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'npm run build',
  timedOut: false,
  exitCode: 1 }

npm ERR! Linux 4.4.0-121-generic
npm ERR! argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "build:web"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! uhk-agent@1.2.0 build:web: `lerna exec --scope uhk-web npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uhk-agent@1.2.0 build:web script 'lerna exec --scope uhk-web npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uhk-agent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna exec --scope uhk-web npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uhk-agent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uhk-agent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/max/prog/src/agent/npm-debug.log
ERROR: "build:web" exited with 1.

npm ERR! Linux 4.4.0-121-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! uhk-agent@1.2.0 build: `run-s build:common build:usb build:web build:electron`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uhk-agent@1.2.0 build script 'run-s build:common build:usb build:web build:electron'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uhk-agent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     run-s build:common build:usb build:web build:electron
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uhk-agent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uhk-agent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/max/prog/src/agent/npm-debug.log

```

**Comment by mondalaci** [comment]
@maxywb Hi there! Your node version might be the cuplrit. Please check out the master branch and try to build it. We've just implemented a node version check and the bulild process should provide relevant error messages which should enable you to resolve them. Please let me know how it works for you.

**Comment by maxywb** [comment]
Thanks! The node version is definitely the issue and there's a better error message now (below). What distros do you know to work out of the box? Or if you develop primarily on Windows/Mac can you share your node version? The default node version on ubuntu 16.04 doesn't work either, which I should have expected since it's way older than the one I'd had previously.

```
 $ nodejs --version
v4.2.6
```

New error message:
```
 $ npm run build

> uhk-agent@1.2.0 prebuild /home/max/prog/src/agent
> check-node-version --package

sh: 1: check-node-version: not found

npm ERR! Linux 4.4.0-121-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! uhk-agent@1.2.0 prebuild: `check-node-version --package`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the uhk-agent@1.2.0 prebuild script 'check-node-version --package'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uhk-agent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     check-node-version --package
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uhk-agent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uhk-agent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/max/prog/src/agent/npm-debug.log
```

**Comment by maxywb** [comment]
The node website has very clear instructions for installing versions 8.x and 10.x, so as soon as you let me know which is appropriate I'm happy to post a pr for the readme for that.

**Comment by maxywb** [comment]
Looks like I have a solution.
- navigate here: https://nodejs.org/en/download/package-manager/
- install 8.x for your distro

**Comment by mondalaci** [comment]
Please run `npm i` to install the new `check-node-version` dependency, then retry the build process.

**Comment by maxywb** [comment]
Sorry if my last comment was unclear, but I got everything settled.

**Comment by mondalaci** [comment]
Ah, great, glad to hear! Closing the issue then. Have fun! :)
