### ISSUE TITLE
Unable to update firmware

### ISSUE THREAD

**Issue by linduxed** [UltimateHackingKeyboard/agent#691]
The following output comes from using Agent version `1.2.4`, although versions `1.2.1` and `1.2.2` exhibit similar behaviour, with less output in the terminal and/or Agent.

When trying to update the firmware from `8.2.0` to `8.2.5`, the following gets printed to the terminal:
```
[12:42:48.949] [debug] [UhkOperations] Operating system: Linux 4.17.2-1-zen x64
[12:42:48.950] [debug] [UhkOperations] Start flashing right firmware
[12:42:48.951] [debug] [UhkHidDevice] Start reenumeration, mode: Bootloader
[12:42:49.061] [debug] [UhkHidDevice] Available devices:
[12:42:49.061] [debug] {"vendorId":4152,"productId":4966,"path":"0005:0003:00","release":150,"interface":0}
[12:42:49.061] [debug] {"vendorId":4152,"productId":4966,"path":"0005:0003:01","release":150,"interface":1}
[12:42:49.061] [debug] {"vendorId":7504,"productId":24866,"path":"0005:0018:00","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
[12:42:49.062] [debug] {"vendorId":7504,"productId":24866,"path":"0005:0018:01","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":1}
[12:42:49.062] [debug] {"vendorId":7504,"productId":24866,"path":"0005:0018:02","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":2}
[12:42:49.062] [debug] {"vendorId":7504,"productId":24866,"path":"0005:0018:03","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":3}
[12:42:49.062] [debug] {"vendorId":7504,"productId":24866,"path":"0005:0018:04","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":4}
[12:42:49.063] [debug] {"vendorId":6226,"productId":20688,"path":"0005:0005:00","release":1,"interface":0}
[12:42:49.063] [debug] {"vendorId":46478,"productId":40580,"path":"0003:0003:03","release":256,"interface":3}
[12:42:49.064] [debug] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"0005:0018:00","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
[12:42:49.064] [debug] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[12:42:49.064] [debug] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[12:42:49.232] [error] [DeviceService] updateFirmware error { message: 'Cannot write to HID device',
  stack: 'Error: Cannot write to HID device\n    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:177:1)\n    at Generator.next (<anonymous>)\n    at fulfilled (/tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:4:42)\n    at <anonymous>' }
[12:42:49.233] [debug] [UhkHidDevice] USB[W]: 09 
[12:42:49.312] [error] [DeviceService] Read hardware modules information failed Error: Cannot write to HID device
    at Promise (/tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:108:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at /tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:133:1)
    at Generator.next (<anonymous>)

[12:42:49.314] [error] [UhkHidDevice] Transfer error:  Error: could not read from HID device

[12:42:49.816] [info] [DeviceService] Device connection state changed to: { bootloaderActive: true, connected: false, hasPermission: true }
[12:42:49.817] [info] [ '[DeviceRendererService] dispatch action',
  '{"payload":{"bootloaderActive":true,"connected":false,"hasPermission":true},"type":"[device] connection state changed"}' ]
[12:42:49.822] [info] [ '[DeviceRendererService] dispatch action',
  '{"payload":{"error":{"message":"Cannot write to HID device","stack":"Error: Cannot write to HID device\\n    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:177:1)\\n    at Generator.next (<anonymous>)\\n    at fulfilled (/tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:4:42)\\n    at <anonymous>"}},"type":"[device] update firmware reply"}' ]


---


[12:42:49.823] [error] [ { TypeError: Cannot read property 'leftModuleInfo' of undefined
      at Object.eval [as updateRenderer] (ng:///SharedModule/DeviceFirmwareComponent.ngfactory.js:93:40)
      at Object.debugUpdateRenderer [as updateRenderer] (file:///tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/renderer/vendor.bundle.js:64895:21)
      at checkAndUpdateView (file:///tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/renderer/vendor.bundle.js:64009:14)
      at callViewAction (file:///tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/renderer/vendor.bundle.js:64355:21)
      at execComponentViewsAction (file:///tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/renderer/vendor.bundle.js:64287:13)
      at checkAndUpdateView (file:///tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/renderer/vendor.bundle.js:64010:5)
      at callViewAction (file:///tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/renderer/vendor.bundle.js:64355:21)
      at execEmbeddedViewsAction (file:///tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/renderer/vendor.bundle.js:64313:17)
      at checkAndUpdateView (file:///tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/renderer/vendor.bundle.js:64005:5)
      at callViewAction (file:///tmp/.mount_UHK.AgudfNnB/app/resources/app.asar/renderer/vendor.bundle.js:64355:21)
    ngDebugContext: 
     DebugContext_ {
       view: [Object],
       nodeIndex: 15,
       nodeDef: [Object],
       elDef: [Object],
       elView: [Object] },
    ngErrorLogger: [Function: bound ] } ]
```
The addition of separating whitespace and `---` is mine, to highlight the lower portion of the message. This lower portion gets repeated at a very rapid rate indefinitely, hanging the Agent interface while it keeps going.

The output from Agent is the following:
```
Start flashing firmware
[12:40:08.582] [UhkOperations] Operating system: Linux 4.17.2-1-zen x64
[12:40:08.583] [UhkOperations] Start flashing right firmware
[12:40:08.585] [UhkHidDevice] Start reenumeration, mode: Bootloader
[12:40:08.696] [UhkHidDevice] Available devices:
[12:40:08.696] {"vendorId":4152,"productId":4966,"path":"0005:0003:00","release":150,"interface":0}
[12:40:08.696] {"vendorId":4152,"productId":4966,"path":"0005:0003:01","release":150,"interface":1}
[12:40:08.697] {"vendorId":7504,"productId":24866,"path":"0005:0012:00","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
[12:40:08.697] {"vendorId":7504,"productId":24866,"path":"0005:0012:01","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":1}
[12:40:08.697] {"vendorId":7504,"productId":24866,"path":"0005:0012:02","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":2}
[12:40:08.698] {"vendorId":7504,"productId":24866,"path":"0005:0012:03","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":3}
[12:40:08.698] {"vendorId":7504,"productId":24866,"path":"0005:0012:04","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":4}
[12:40:08.698] {"vendorId":6226,"productId":20688,"path":"0005:0005:00","release":1,"interface":0}
[12:40:08.698] {"vendorId":46478,"productId":40580,"path":"0003:0003:03","release":256,"interface":3}
[12:40:08.699] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"0005:0012:00","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
[12:40:08.700] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[12:40:08.700] [UhkHidDevice] USB[W]: 01 00 88 13 00 00
[12:40:08.858] [DeviceService] updateFirmware error { message: 'Cannot write to HID device', stack: 'Error: Cannot write to HID device\n at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgCOSpXb/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:177:1)\n at Generator.next (<anonymous>)\n at fulfilled (/tmp/.mount_UHK.AgCOSpXb/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:4:42)\n at <anonymous>' }
[12:40:08.859] [UhkHidDevice] USB[W]: 09
[12:40:09.051] [DeviceService] Read hardware modules information failed Error: Cannot write to HID device at Promise (/tmp/.mount_UHK.AgCOSpXb/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:108:1) at Promise (<anonymous>) at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgCOSpXb/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1) at Generator.next (<anonymous>) at /tmp/.mount_UHK.AgCOSpXb/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1 at Promise (<anonymous>) at __awaiter (/tmp/.mount_UHK.AgCOSpXb/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1) at UhkHidDevice.write (/tmp/.mount_UHK.AgCOSpXb/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1) at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgCOSpXb/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:133:1) at Generator.next (<anonymous>)
[12:40:09.054] [UhkHidDevice] Transfer error: Error: could not read from HID device
[12:40:09.556] [DeviceService] Device connection state changed to: { bootloaderActive: true, connected: false, hasPermission: true }
```

**Comment by linduxed** [comment]
As the keyboard is in a useable state with the currrent firmware version, I'll wait with doing a factory reset, to retain the possibility of debugging the current state.

**Comment by mondalaci** [comment]
Please paste the entire log.

**Comment by mondalaci** [comment]
Thank you for the log!

This is a very strange bug. When starting the firmware update process Agent sends a USB command to your UHK which should make it jump to the bootloader, but for some reason Agent can't send this command. The reason why this is very strange is because at this point Agent had already written and read your UHK over USB, otherwise Agent would have failed before.

1. What kind of Linux do you use?
2. Please disconnect every USB device but the UHK and retry.
3. Please try to update the firmware on another Linux distribution.
4. Please try to update the firmware on a non-Linux OS.

Please let me know about your findings.

**Comment by linduxed** [comment]
I'm running Arch Linux.

Unplugging everything except the keyboard helped: my keyboard is now running `8.2.5` on both halves.

Unfortunately, I remembered too late that you might be interested in the log from the successful update: I closed the window and terminal soon after it succeeding. Sorry about that, hope that not much of value was lost.

**Comment by mondalaci** [comment]
No problem. Recent Agent version already mention that everything should be unplugged except the UHK in case of firmware update failures and this notification will be even more pronounced going forward.

**Comment by linduxed** [comment]
I have to admit that I did see the instruction, but didn't make use of the advice. I think I might be scarred by completely useless troubleshooting guides and help sections in other applications.

My guess is that I would have needed it to be more attention grabbing for me to have believed that the text is of relevance.

**Comment by mondalaci** [comment]
Thanks for the feedback! Yep, the plan is to make it more attention grabbing.

**Comment by vinipsmaker** [comment]
> No problem. Recent Agent version already mention that everything should be unplugged except the UHK in case of firmware update failures and this notification will be even more pronounced going forward.

I use a laptop as my main PC, and the laptop itself has some “virtual USB devices” which I cannot unplug (mainly hubs):

```
$ lsusb
Bus 003 Device 002: ID 05c8:022a Cheng Uei Precision Industry Co., Ltd (Foxlink)
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Will the recent replacement of `blhost` command help me somehow or will I have to find a different PC just to flash a newer firmware version?

**Comment by mondalaci** [comment]
@vinipsmaker Yes, the replacement of blhost should help. Please wait for the new Agent release, give it a try as soon as we release it, and feel free to open a new issue if it won't work with your PC.
