### ISSUE TITLE
The new Agent pre-release throws an error upon startup

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#737]
laci@spark ~/apps $ ./UHK.Agent-1.2.6-linux-x86_64.AppImage
module.js:487
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_UHK.Agtd2Qe8/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3

**Comment by ert78gb** [comment]
The error in the electron builder electron-userland/electron-builder#2958

PR opended
