### ISSUE TITLE
blhost segfaults on Mac

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#747]
The firmware update procedure of Agent executes a command line utility called blhost. This utility is critical for the firmware update to be successful. On some Macs blhost segfaults, making the firmware update unsuccesful.

You can easily tell if blhost is the culprit. Consider the following firmware update log snippet:

```
[09:57:45.078] [blhost] RUN: /Applications/UHK Agent.app/Contents/Resources/packages/blhost/mac/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[09:57:45.171] [blhost] EXIT_CODE: null
[09:57:45.171] [blhost] FINISHED: null
```

blhost should never return with null. If it does, it has most likely segfaulted.

On Linux, we encountered the same issue, and concluded that blhost must be recompiled statically, and must not contain special processor instructions. These were achievable via [compiler flags on Linux](https://github.com/UltimateHackingKeyboard/bootloader/commit/85892581f7568b7831376de21f385913485ea24f) and solved the issue.

A similar solution should likely work on Mac. To fix this, try to build blhost on your Mac, instead of using the binary provided by Agent.

Clone the [UHK booltloader repo](https://github.com/UltimateHackingKeyboard/bootloader), then open the XCode project in its `validation/blhost.xcodeproj` directory. You should probably add complier options to make blhost statically compile and not contain special processor instructions, then build blhost.

Then according to your firmware update log, overwrite the blhost binary provided by Agent with your compiled version. In the above example blhost is located at `/Applications/UHK Agent.app/Contents/Resources/packages/blhost/mac/blhost`. Then retry the firmware update to see if it succeeds this time.

I'm not familiar with XCode or the Mac, so we could use some help. Whoever is reading this issue, please feel free to contribute!

See the related Linux issue at #681.

See the original Mac blhost segfault issue at #718.

**Comment by ert78gb** [comment]
my compiled mac blhost 
[blhost.zip](https://github.com/UltimateHackingKeyboard/agent/files/2303717/blhost.zip)

**Comment by mondalaci** [comment]
@MyDogTom Can you give the attached blhost binary a try to see if firmware update works this time? (Plug in your UHK via your monitor, just as you most recently did.)

**Comment by MyDogTom** [comment]
I accessed location mentioned in the ticket (via "show package contents" command) and replaced file with the one from this thread. I'm not sure if that's enough or not.
 Unfortunately, there is an error again :(
```
Start flashing firmware
[15:16:12.500] [UhkHidDevice] Available devices unchanged
[15:16:12.501] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/IOUSBHostDevice@14410000/AppleUSB20Hub@14410000/AppleUSB20HubPort@14411000/Ultimate Hacking Keyboard@14411000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14411000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":-1,"usagePage":65280,"usage":1}
[15:16:12.502] [UhkHidDevice] USB[W]: 09 
[15:16:12.507] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[15:16:12.507] [DeviceOperation] USB[T]: Read left module version information
[15:16:12.507] [UhkHidDevice] USB[W]: 0e 01 00 
[15:16:12.515] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 02 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[15:16:12.516] [DeviceOperation] USB[T]: Read right module version information
[15:16:12.516] [UhkHidDevice] USB[W]: 00 01 
[15:16:12.523] [UhkHidDevice] USB[R]: 00 08 00 02 00 05 00 04 00 03 00 01 00 04 00 00 00 00 00 04 00 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[15:16:12.523] Device right firmware version: 8.2.5
[15:16:12.523] Device left firmware version: 8.2.5
[15:16:12.533] New firmware version: 8.4.0
[15:16:12.534] [UhkOperations] Operating system: Darwin 17.7.0 x64
[15:16:12.534] [UhkOperations] Start flashing right firmware
[15:16:12.534] [UhkHidDevice] Start reenumeration, mode: Bootloader
[15:16:12.647] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[15:16:12.647] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[15:16:13.103] [UhkHidDevice] reenumeration devices up
[15:16:13.103] [UhkHidDevice] Device communication closing.
[15:16:13.103] [UhkHidDevice] Device communication closed.
[15:16:13.104] [blhost] RUN: /Applications/UHK Agent.app/Contents/Resources/packages/blhost/mac/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[15:16:13.187] [blhost] EXIT_CODE: null
[15:16:13.187] [blhost] FINISHED: null
[15:16:13.188] [DeviceService] updateFirmware error { message: 'blhost error code:null',
  stack: 'Error: blhost error code:null\n    at finish (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[15:16:13.195] [UhkHidDevice] Available devices:
[15:16:13.196] {"vendorId":5824,"productId":10203,"path":"IOService:/IOResources/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_v060800/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_UserClient_v060800/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v060800","serialNumber":"pqrs.org:org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v060800","manufacturer":"pqrs.org","product":"Karabiner VirtualHIDKeyboard","release":0,"interface":-1,"usagePage":1,"usage":6}
[15:16:13.196] {"vendorId":7504,"productId":24864,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/IOUSBHostDevice@14410000/AppleUSB20Hub@14410000/AppleUSB20HubPort@14411000/UHK Bootloader@14411000/MCU HID GENERIC DEVICE@0/IOUSBHostHIDDevice@14411000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":-1,"usagePage":65280,"usage":1}
[15:16:13.196] {"vendorId":1452,"productId":632,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@1E,3/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Actuator/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":2198,"interface":-1,"usagePage":65280,"usage":13}
[15:16:13.196] {"vendorId":1452,"productId":34304,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS03@14200000/iBridge@14200000/IOUSBHostInterface@2/IOUSBHostHIDDevice@14200000,2","serialNumber":"","manufacturer":"Apple Inc.","product":"iBridge","release":257,"interface":-1,"usagePage":13,"usage":5}
[15:16:13.196] {"vendorId":1452,"productId":632,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@1E,3/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Accelerometer/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":2198,"interface":-1,"usagePage":65280,"usage":3}
[15:16:13.196] {"vendorId":1452,"productId":34304,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS03@14200000/iBridge@14200000/IOUSBHostInterface@6/IOUSBHostHIDDevice@14200000,6","serialNumber":"","manufacturer":"Apple Inc.","product":"iBridge","release":257,"interface":-1,"usagePage":32,"usage":65}
[15:16:13.196] {"vendorId":1452,"productId":34304,"path":"IOService:/IOResources/IOHIDResource/IOHIDResourceDeviceUserClient/IOHIDUserDevice","serialNumber":"","manufacturer":"","product":"","release":0,"interface":-1,"usagePage":1,"usage":6}
[15:16:13.196] {"vendorId":1452,"productId":632,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@1E,3/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Trackpad / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":2198,"interface":-1,"usagePage":1,"usage":2}
[15:16:13.197] {"vendorId":1452,"productId":632,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@1E,3/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Device Management/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":2198,"interface":-1,"usagePage":65280,"usage":11}
[15:16:13.197] {"vendorId":1452,"productId":632,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@1E,3/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Keyboard / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":2198,"interface":-1,"usagePage":1,"usage":6}
[15:16:13.197] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:92:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:140:1)
    at Generator.next (<anonymous>)
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.waitUntilKeyboardBusy (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:138:1)
    at DeviceService.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/src/services/device.service.ts:137:31)
    at Generator.next (<anonymous>)

[15:16:13.199] [blhost] CLOSE_CODE: null
[15:16:13.706] [DeviceService] Device connection state changed to: { bootloaderActive: true, connected: false, hasPermission: true }
blhost error code:null

```

I double checked. Keyboard is connected and works.

**Comment by ert78gb** [comment]
@MyDogTom what is your device os version? Is it a iMac or MacBook ?

**Comment by ert78gb** [comment]
is it has USB-C ports if I know well, am I right?
I have older model USB-A connector and everything is working fine. What is the transformer that u use?

**Comment by MyDogTom** [comment]
@ert78gb Yes, it has only USB-C. 
Please, take a look into that issue https://github.com/UltimateHackingKeyboard/agent/issues/746 for additional information about adapter etc.

**Comment by ttscoff** [comment]
I had a similar issue, solved by quitting Karabiner Elements (open preferences, use the quit button under the Misc tab).

**Comment by ert78gb** [comment]
ok thx. sry I did not see the linked issues.

**Comment by mondalaci** [comment]
@MyDogTom Please run the new blhost binary from the command line and share its output.

**Comment by MyDogTom** [comment]
@ert78gb No worries. I'm glad to help as much as I can.
@ttscoff That helped me. Thank you!
@mondalaci 
I was able to update firmware via monitor after quitting Karabiner Elements. My bad, I did it with  blhost from current issue. I should have tried that with old blhost first.

Do you still need output from command line?

**Comment by MyDogTom** [comment]
The only difference between last log, that I posted, and successful update is `Carabiner Elements`.

**Comment by mondalaci** [comment]
Then the answer is yes. I have no idea how on earth Carabiner Elements can possibly affect blhost. I guess Agent should check whether Carabiner Elements is running, and if so, instruct the user to close it upon a failed firmware update.

Please make sure that Carabiner Elements is not running, and your UHK is connected to your monitor, and then retry the firmware update with the old blhost vs the new blhost. I'm wondering whether the new blhost binary makes any difference.

**Comment by MyDogTom** [comment]
With old blhost update also works. I did downgrade from 8.4.4 to 8.4.0 and afterwards back to 8.4.4. Everything went fine.

**Comment by mondalaci** [comment]
@MyDogTom Thanks so much for all your feedback! Closing this issue in favor of #755 which will be a proper fix.

@ert78gb Please attach the changed Xcode project file here. We might need it later.

**Comment by mondalaci** [comment]
The new blhost binary and Xcode file was put into the [chore-change-xcode-project-settings branch of the bootloader repo](https://github.com/UltimateHackingKeyboard/bootloader/tree/chore-change-xcode-project-settings).

**Comment by conorpp** [comment]
Hello from [SoloKeys](https://github.com/solokeys)!

I was still having problems with blhost on MacOS and patched it here, in case anyone is still having issues:
https://github.com/conorpp/blhost-macos/releases/tag/2.7.1.1

**Comment by mondalaci** [comment]
Thanks for sharing! As far as we're concerned, it's a non issue since #1042 was implemented.
