### ISSUE TITLE
Error upgrading firmware 8.2.5 -> 8.4.0 using Agent 1.2.7 on macos

### ISSUE THREAD

**Issue by EkstraOst** [UltimateHackingKeyboard/agent#758]
Here is the log:

Start flashing firmware
[03:47:31.181] [UhkHidDevice] Available devices unchanged
[03:47:31.182] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14200000/Ultimate Hacking Keyboard@14200000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14200000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":-1,"usagePage":65280,"usage":1}
[03:47:31.182] [UhkHidDevice] USB[W]: 09 
[03:47:31.188] [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[03:47:31.189] [DeviceOperation] USB[T]: Read left module version information
[03:47:31.189] [UhkHidDevice] USB[W]: 0e 01 00 
[03:47:31.196] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 02 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[03:47:31.196] [DeviceOperation] USB[T]: Read right module version information
[03:47:31.197] [UhkHidDevice] USB[W]: 00 01 
[03:47:31.204] [UhkHidDevice] USB[R]: 00 08 00 02 00 05 00 04 00 03 00 01 00 04 00 00 00 00 00 04 00 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[03:47:31.205] Device right firmware version: 8.2.5
[03:47:31.206] Device left firmware version: 8.2.5
[03:47:31.211] New firmware version: 8.4.0
[03:47:31.211] [UhkOperations] Operating system: Darwin 17.7.0 x64
[03:47:31.211] [UhkOperations] Start flashing right firmware
[03:47:31.211] [UhkHidDevice] Start reenumeration, mode: Bootloader
[03:47:31.324] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[03:47:31.324] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[03:47:31.720] [UhkHidDevice] reenumeration devices up
[03:47:31.720] [UhkHidDevice] Device communication closing.
[03:47:31.720] [UhkHidDevice] Device communication closed.
[03:47:31.721] [blhost] RUN: /Applications/UHK Agent.app/Contents/Resources/packages/blhost/mac/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[03:47:31.737] [blhost] EXIT_CODE: null
[03:47:31.737] [blhost] FINISHED: null
[03:47:31.738] [blhost] CLOSE_CODE: null
[03:47:31.739] [DeviceService] updateFirmware error { message: 'blhost error code:null',
  stack: 'Error: blhost error code:null\n    at finish (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[03:47:31.746] [UhkHidDevice] Available devices:
[03:47:31.747] {"vendorId":1452,"productId":602,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14400000/Apple Internal Keyboard / Trackpad@14400000/Apple Internal Keyboard@0/AppleUSBTCKeyboard@14400000,0","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":548,"interface":-1,"usagePage":1,"usage":6}
[03:47:31.747] {"vendorId":1452,"productId":602,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14400000/Apple Internal Keyboard / Trackpad@14400000/Touchpad@2/AppleUSBTCButtons@14400000,2","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":548,"interface":-1,"usagePage":1,"usage":2}
[03:47:31.747] {"vendorId":1452,"productId":602,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14400000/Apple Internal Keyboard / Trackpad@14400000/Touchpad@1/AppleUSBMultitouchDriver@14400000,1","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":548,"interface":-1,"usagePage":65280,"usage":1}
[03:47:31.747] {"vendorId":5824,"productId":10203,"path":"IOService:/IOResources/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_v060800/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_UserClient_v060800/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v060800","serialNumber":"pqrs.org:org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v060800","manufacturer":"pqrs.org","product":"Karabiner VirtualHIDKeyboard","release":0,"interface":-1,"usagePage":1,"usage":6}
[03:47:31.747] {"vendorId":7504,"productId":24864,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14200000/UHK Bootloader@14200000/MCU HID GENERIC DEVICE@0/IOUSBHostHIDDevice@14200000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":-1,"usagePage":65280,"usage":1}
[03:47:31.748] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:92:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:140:1)
    at Generator.next (<anonymous>)

[03:47:32.260] [DeviceService] Device connection state changed to: { bootloaderActive: true, connected: false, hasPermission: true }
blhost error code:null

**Comment by mondalaci** [comment]
Do you use a USB hub or docking station? If so, which one? Please try to connect your UHK directly to your Mac or via another hub, and let me know how it goes.

**Comment by EkstraOst** [comment]
No other peripherals are connected. The keyboard is connected directly to my mac.

**Comment by mondalaci** [comment]
Please take a look at #747, grab the blhost binary from blhost.zip, overwrite the default blhost as described, give the firmware update another try, and let me know if it works for you.

**Comment by EkstraOst** [comment]
Thank you for pointing me in the right direction. The issue was fixed by quitting Karabiner Elements as suggested by one of the commenters. No other steps were needed. The upgrade has now completed successfully.

**Comment by fugufish** [comment]
@mondalaci didn't know if it was worth opening a separate ticket, but after spending a few looking for an answer here, I figured it out on my own, posting for posterity.  karabiner elements also hijacks the caps lock light (shifting it over to the Macbook's built in light. If your caps light doesn't indicate on and you are running karabiner elements that is likely why.
