### ISSUE TITLE
Firmware Update Failed

### ISSUE THREAD

**Issue by millerjl2** [UltimateHackingKeyboard/agent#763]
I'm using a Microsoft Surfacebook 2 with nothing connected except for power and the UHK.  Issue occurs when using agent 1.2.5 and 1.2.8 when trying to flash from 8.1.5 to 8.2.5 and 8.4.5.  See log below for my attempt to upgrade from 8.1.5 to 8.2.5 using agent 1.2.8.

```
Start flashing firmware
[09:12:24.766] [UhkHidDevice] Available devices:
[09:12:24.766] {"vendorId":1118,"productId":2386,"path":"\\\\?\\hid#ven_8086&dev_9d3e&subsys_00000000&rev_21&col09#4&f87ce30&0&0008#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"001","manufacturer":"Intel","product":"Precise Touch","release":4,"interface":-1,"usagePage":65535,"usage":1}
[09:12:24.766] {"vendorId":1118,"productId":2338,"path":"\\\\?\\hid#vid_045e&pid_0922&col05#7&36425755&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Microsoft","product":"Surface Keyboard","release":2817,"interface":-1,"usagePage":65285,"usage":2}
[09:12:24.766] {"vendorId":1118,"productId":2338,"path":"\\\\?\\hid#vid_045e&pid_0922&col06#7&36425755&0&0005#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Microsoft","product":"Surface Keyboard","release":2817,"interface":-1,"usagePage":13,"usage":5}
[09:12:24.766] {"vendorId":1118,"productId":2338,"path":"\\\\?\\hid#vid_045e&pid_0922&col0a#7&36425755&0&0009#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Microsoft","product":"Surface Keyboard","release":2817,"interface":-1,"usagePage":65285,"usage":80}
[09:12:24.767] {"vendorId":1118,"productId":2338,"path":"\\\\?\\hid#vid_8087&pid_0ac2#6&29ec12c5&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","release":2817,"interface":-1}
[09:12:24.767] {"vendorId":1118,"productId":2338,"path":"\\\\?\\hid#vid_045e&pid_0922&col07#7&36425755&0&0006#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Microsoft","product":"Surface Keyboard","release":2817,"interface":-1,"usagePage":13,"usage":14}
[09:12:24.767] {"vendorId":1118,"productId":2338,"path":"\\\\?\\hid#vid_045e&pid_0922&col08#7&36425755&0&0007#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Microsoft","product":"Surface Keyboard","release":2817,"interface":-1,"usagePage":65287,"usage":1}
[09:12:24.767] {"vendorId":1118,"productId":2386,"path":"\\\\?\\hid#ven_8086&dev_9d3e&subsys_00000000&rev_21&col04#4&f87ce30&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"001","manufacturer":"Intel","product":"Precise Touch","release":4,"interface":-1,"usagePage":13,"usage":2}
[09:12:24.767] {"vendorId":1118,"productId":2338,"path":"\\\\?\\hid#vid_045e&pid_0922&col09#7&36425755&0&0008#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Microsoft","product":"Surface Keyboard","release":2817,"interface":-1,"usagePage":65285,"usage":4}
[09:12:24.767] {"vendorId":1118,"productId":61442,"path":"\\\\?\\hid#hid_device_system_vhf#4&e9aeb1&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"1.0","manufacturer":"Microsoft","product":"HID VHF Driver","release":1,"interface":-1,"usagePage":1,"usage":13}
[09:12:24.767] {"vendorId":1118,"productId":2386,"path":"\\\\?\\hid#ven_8086&dev_9d3e&subsys_00000000&rev_21&col05#4&f87ce30&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"001","manufacturer":"Intel","product":"Precise Touch","release":4,"interface":-1,"usagePage":13,"usage":4}
[09:12:24.767] {"vendorId":1118,"productId":1365,"path":"\\\\?\\hid#mshw0124&col02#5&2666cd9c&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"1234","manufacturer":"Microsoft","product":"Tcon Device","release":65535,"interface":-1,"usagePage":65295,"usage":512}
[09:12:24.768] {"vendorId":0,"productId":0,"path":"\\\\?\\hid#mshw0029&col01#3&12bcb554&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"1.0","manufacturer":"Microsoft","product":"GPIO Button Driver","release":0,"interface":-1,"usagePage":1,"usage":6}
[09:12:24.768] {"vendorId":0,"productId":0,"path":"\\\\?\\hid#mshw0029&col02#3&12bcb554&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"1.0","manufacturer":"Microsoft","product":"GPIO Button Driver","release":0,"interface":-1,"usagePage":12,"usage":1}
[09:12:24.768] {"vendorId":1118,"productId":0,"path":"\\\\?\\hid#converteddevice&col01#6&2496175a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","release":0,"interface":-1,"usagePage":1,"usage":6}
[09:12:24.768] {"vendorId":1118,"productId":2386,"path":"\\\\?\\hid#ven_8086&dev_9d3e&subsys_00000000&rev_21&col06#4&f87ce30&0&0005#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"001","manufacturer":"Intel","product":"Precise Touch","release":4,"interface":-1,"usagePage":1,"usage":2}
[09:12:24.768] {"vendorId":0,"productId":0,"path":"\\\\?\\hid#mshw0029&col03#3&12bcb554&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"1.0","manufacturer":"Microsoft","product":"GPIO Button Driver","release":0,"interface":-1,"usagePage":1,"usage":128}
[09:12:24.768] {"vendorId":1118,"productId":0,"path":"\\\\?\\hid#converteddevice&col02#6&2496175a&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","release":0,"interface":-1,"usagePage":12,"usage":1}
[09:12:24.768] {"vendorId":1118,"productId":2338,"path":"\\\\?\\hid#vid_045e&pid_0922&col0b#7&36425755&0&000a#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Microsoft","product":"Surface Keyboard","release":2817,"interface":-1,"usagePage":65280,"usage":63744}
[09:12:24.769] {"vendorId":1118,"productId":0,"path":"\\\\?\\hid#converteddevice&col03#6&2496175a&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}","release":0,"interface":-1,"usagePage":1,"usage":128}
[09:12:24.769] {"vendorId":1118,"productId":2386,"path":"\\\\?\\hid#ven_8086&dev_9d3e&subsys_00000000&rev_21&col01#4&f87ce30&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"001","manufacturer":"Intel","product":"Precise Touch","release":4,"interface":-1,"usagePage":65535,"usage":1}
[09:12:24.769] {"vendorId":1118,"productId":2386,"path":"\\\\?\\hid#ven_8086&dev_9d3e&subsys_00000000&rev_21&col07#4&f87ce30&0&0006#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"001","manufacturer":"Intel","product":"Precise Touch","release":4,"interface":-1,"usagePage":65295,"usage":80}
[09:12:24.769] {"vendorId":1118,"productId":61441,"path":"\\\\?\\hid#hid_device_system_vhf#4&20681acc&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"1.0","manufacturer":"Microsoft","product":"HID VHF Driver","release":1,"interface":-1,"usagePage":1,"usage":6}
[09:12:24.769] {"vendorId":1118,"productId":2386,"path":"\\\\?\\hid#ven_8086&dev_9d3e&subsys_00000000&rev_21&col02#4&f87ce30&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"001","manufacturer":"Intel","product":"Precise Touch","release":4,"interface":-1,"usagePage":13,"usage":4}
[09:12:24.769] {"vendorId":1118,"productId":2386,"path":"\\\\?\\hid#ven_8086&dev_9d3e&subsys_00000000&rev_21&col08#4&f87ce30&0&0007#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"001","manufacturer":"Intel","product":"Precise Touch","release":4,"interface":-1,"usagePage":65295,"usage":96}
[09:12:24.769] {"vendorId":1118,"productId":2338,"path":"\\\\?\\hid#vid_045e&pid_0922&col01#7&36425755&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Microsoft","product":"Surface Keyboard","release":2817,"interface":-1,"usagePage":1,"usage":6}
[09:12:24.769] {"vendorId":1118,"productId":2338,"path":"\\\\?\\hid#vid_045e&pid_0922&col02#7&36425755&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Microsoft","product":"Surface Keyboard","release":2817,"interface":-1,"usagePage":1,"usage":2}
[09:12:24.770] {"vendorId":1118,"productId":2338,"path":"\\\\?\\hid#vid_045e&pid_0922&col03#7&36425755&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Microsoft","product":"Surface Keyboard","release":2817,"interface":-1,"usagePage":12,"usage":1}
[09:12:24.770] {"vendorId":1118,"productId":2386,"path":"\\\\?\\hid#ven_8086&dev_9d3e&subsys_00000000&rev_21&col03#4&f87ce30&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"001","manufacturer":"Intel","product":"Precise Touch","release":4,"interface":-1,"usagePage":65291,"usage":11}
[09:12:24.770] {"vendorId":1118,"productId":2338,"path":"\\\\?\\hid#vid_045e&pid_0922&col04#7&36425755&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Microsoft","product":"Surface Keyboard","release":2817,"interface":-1,"usagePage":65285,"usage":1}
[09:12:24.770] {"vendorId":1118,"productId":2386,"path":"\\\\?\\hid#ven_8086&dev_9d3e&subsys_00000000&rev_21&col0a#4&f87ce30&0&0009#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"001","manufacturer":"Intel","product":"Precise Touch","release":4,"interface":-1,"usagePage":65289,"usage":256}
[09:12:24.770] {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_04#9&293861ad&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":4,"usagePage":1,"usage":2}
[09:12:24.770] {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#9&1812babc&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":128,"usage":129}
[09:12:24.770] {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_01#9&2b42d6fa&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":1,"usagePage":1,"usage":6}
[09:12:24.770] {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_02#9&2d82931&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":2,"usagePage":12,"usage":1}
[09:12:24.770] {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_03#9&1608456f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","product":"Ultimate Hacking Keyboard","release":257,"interface":3,"usagePage":1,"usage":128}
[09:12:24.771] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#9&1812babc&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":128,"usage":129}
[09:12:24.771] [UhkHidDevice] USB[W]: 09 
[09:12:24.776] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[09:12:24.776] [DeviceOperation] USB[T]: Read left module version information
[09:12:24.776] [UhkHidDevice] USB[W]: 0e 01 00 
[09:12:24.796] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 01 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[09:12:24.796] [DeviceOperation] USB[T]: Read right module version information
[09:12:24.797] [UhkHidDevice] USB[W]: 00 01 
[09:12:24.804] [UhkHidDevice] USB[R]: 00 08 00 01 00 05 00 04 00 02 00 00 00 04 00 00 00 00 00 04 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[09:12:24.805] Device right firmware version: 8.1.5
[09:12:24.805] Device left firmware version: 8.1.5
[09:12:24.807] New firmware version: 8.2.5
[09:12:24.807] [UhkOperations] Operating system: Windows_NT 10.0.17134 x64
[09:12:24.807] [UhkOperations] Start flashing right firmware
[09:12:24.807] [UhkHidDevice] Start reenumeration, mode: Bootloader
[09:12:24.924] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[09:12:24.924] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[09:12:24.929] [DeviceService] updateFirmware error { message: 'Cannot write to HID device',
  stack: 'Error: Cannot write to HID device\n    at UhkHidDevice.<anonymous> (C:\\Users\\millerjl\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\webpack:\\uhk-usb\\dist\\src\\uhk-hid-device.js:184:1)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\millerjl\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\webpack:\\uhk-usb\\dist\\src\\uhk-hid-device.js:4:42)\n    at <anonymous>' }
[09:12:24.929] [UhkHidDevice] USB[W]: 09 
[09:12:24.933] [DeviceService] Read hardware modules information failed Error: Cannot write to HID device
    at Promise (C:\Users\millerjl\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:109:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (C:\Users\millerjl\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at C:\Users\millerjl\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (C:\Users\millerjl\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:3:1)
    at UhkHidDevice.write (C:\Users\millerjl\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (C:\Users\millerjl\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:140:1)
    at Generator.next (<anonymous>)

[09:12:24.935] [UhkHidDevice] Transfer error:  Error: could not read from HID device

[09:12:24.935] [UhkHidDevice] Device communication closing.
[09:12:24.935] [UhkHidDevice] Device communication closed.
[09:12:25.446] [DeviceService] Device connection state changed to: { bootloaderActive: false,
  connected: false,
  hasPermission: true }
Cannot write to HID device
```

**Comment by mondalaci** [comment]
Is your UHK directly connected to the Surface Book, or is it connected via docking station / USB hub?

In any case, please retry with other USB ports. Give every one of your USB ports a try.

**Comment by millerjl2** [comment]
There are only two USB ports, so I'll try the other one.  I do not have a docking station or USB hub in the mix.

**Comment by millerjl2** [comment]
I did finally test out the other USB port and the same issue occurs.  This might be an interesting issue without a viable solution.  Since the surfacebook 2 is effectively a tablet with a keyboard dock and there are no directly accessible ports on the tablet portion, it may be unable to flash updates to the keyboard.  As it is with nothing but the UHK plugged into either USB port this machine is unable to flash updates.

**Comment by mondalaci** [comment]
We've been getting similar Surface related reports. I'm afraid #755 is the only solution which will likely take a while. In the meantime, the only solution is to use another computer to update the firmware of your UHK. I'm sorry but this is the best I can offer right now. I'm closing this ticket due to the lack of an alternative solution. Feel free to follow #755.
