### ISSUE TITLE
Firmware update fails with error message on Win10; potentially unusual USB configuration

### ISSUE THREAD

**Issue by nfd9001** [UltimateHackingKeyboard/agent#779]
Updating to firmware version 8.4.5 fails in Agent under Windows 10. I will note here that I disconnected all other USB devices and tried running Agent with elevated permissions to no avail. USB *may* behave slightly unusually on my device, since it's a Surface Book.

Log:
```
Start flashing firmware
[10:38:19.076] [UhkHidDevice] Available devices unchanged
[10:38:19.077] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#8&25e1b701&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":65280,"usage":1}
[10:38:19.077] [UhkHidDevice] USB[W]: 09 
[10:38:19.081] [ { Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ng-valid: true'. Current value: 'ng-valid: false'.
      at viewDebugError (file:///C:/Users/alexa/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:59977:32)
      at expressionChangedAfterItHasBeenCheckedError (file:///C:/Users/alexa/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:59955:12)
      at checkBindingNoChanges (file:///C:/Users/alexa/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:60122:15)
      at checkNoChangesNodeInline (file:///C:/Users/alexa/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:64178:9)
      at checkNoChangesNode (file:///C:/Users/alexa/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:64144:9)
      at debugCheckNoChangesNode (file:///C:/Users/alexa/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:64973:45)
      at debugCheckRenderNodeFn (file:///C:/Users/alexa/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:64913:13)
      at Object.eval [as updateRenderer] (ng:///SharedModule/SideMenuComponent.ngfactory.js:703:5)
      at Object.debugUpdateRenderer [as updateRenderer] (file:///C:/Users/alexa/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:64895:21)
      at checkNoChangesView (file:///C:/Users/alexa/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:63984:14)
    ngDebugContext: 
     DebugContext_ {
       view: [Object],
       nodeIndex: 9,
       nodeDef: [Object],
       elDef: [Object],
       elView: [Object] },
    ngErrorLogger: [Function: bound ] } ]
[10:38:19.084] [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[10:38:19.084] [DeviceOperation] USB[T]: Read left module version information
[10:38:19.085] [UhkHidDevice] USB[W]: 0e 01 00 
[10:38:19.092] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 02 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[10:38:19.093] [DeviceOperation] USB[T]: Read right module version information
[10:38:19.093] [UhkHidDevice] USB[W]: 00 01 
[10:38:19.100] [UhkHidDevice] USB[R]: 00 08 00 02 00 05 00 04 00 03 00 01 00 04 00 00 00 00 00 04 00 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[10:38:19.101] Device right firmware version: 8.2.5
[10:38:19.101] Device left firmware version: 8.2.5
[10:38:19.264] New firmware version: 8.4.5
[10:38:19.265] [UhkOperations] Operating system: Windows_NT 10.0.17134 x64
[10:38:19.265] [UhkOperations] Start flashing right firmware
[10:38:19.265] [UhkHidDevice] Start reenumeration, mode: Bootloader
[10:38:19.385] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[10:38:19.385] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[10:38:19.394] [DeviceService] updateFirmware error { message: 'Cannot write to HID device',
  stack: 'Error: Cannot write to HID device\n    at UhkHidDevice.<anonymous> (C:\\Users\\alexa\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\webpack:\\uhk-usb\\dist\\src\\uhk-hid-device.js:184:1)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\alexa\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\webpack:\\uhk-usb\\dist\\src\\uhk-hid-device.js:4:42)\n    at <anonymous>' }
[10:38:19.395] [UhkHidDevice] USB[W]: 09 
[10:38:19.395] [DeviceService] Read hardware modules information failed Error: Cannot write to HID device
    at Promise (C:\Users\alexa\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:109:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (C:\Users\alexa\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at C:\Users\alexa\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (C:\Users\alexa\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:3:1)
    at UhkHidDevice.write (C:\Users\alexa\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (C:\Users\alexa\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:140:1)
    at Generator.next (<anonymous>)
    at C:\Users\alexa\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (C:\Users\alexa\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:3:1)
    at UhkHidDevice.waitUntilKeyboardBusy (C:\Users\alexa\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:138:1)
    at DeviceService.<anonymous> (C:\Users\alexa\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\src\services\device.service.ts:137:31)
    at Generator.next (<anonymous>)

[10:38:19.399] [UhkHidDevice] Transfer error:  Error: could not read from HID device

[10:38:19.399] [UhkHidDevice] Device communication closing.
[10:38:19.399] [UhkHidDevice] Device communication closed.
[10:38:19.922] [DeviceService] Device connection state changed to: { bootloaderActive: false,
  connected: false,
  hasPermission: true }
Cannot write to HID device
```

**Comment by mondalaci** [comment]
Would you give a try to every USB ports of your Surface Book? How many USB ports does it have, by the way?

**Comment by nfd9001** [comment]
Ah, pardon me, I apparently didn't actually send this the other day.

I have, with and without elevation, right after a reboot, etc. The Surface Book has two USB ports, both in its base, which is detachable.

**Comment by mondalaci** [comment]
Thanks for the further feedback! I'm closing this issue in favor of #755 which may take a while, but it's the only way to solve this problem. In the meantime, please use another computer to update the firmware. I know it's not ideal and I'm sorry for the inconvenience.
