### ISSUE TITLE
Firmware not updating to 8.4.5 on Win10

### ISSUE THREAD

**Issue by phlpl** [UltimateHackingKeyboard/agent#787]
Also having issues updating to 8.4.5 with Win10.  Tried disconnecting all other devices including bluetooth and tried updating the UHK with all USB ports.  Looks like there is an issue with my laptop being multi touch and having a pen?  Tried to find the device in device manager to disable it but the option is greyed out.  My laptop is a Lenovo X1 Yoga 1st gen.

`Start flashing firmware
[19:23:30.923] [UhkHidDevice] Available devices unchanged
[19:23:30.924] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#7&14dadeeb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":65280,"usage":1}
[19:23:30.925] [UhkHidDevice] USB[W]: 09 
[19:23:30.929] [ { Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ng-valid: true'. Current value: 'ng-valid: false'.
      at viewDebugError (file:///C:/Users/phili/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:59977:32)
      at expressionChangedAfterItHasBeenCheckedError (file:///C:/Users/phili/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:59955:12)
      at checkBindingNoChanges (file:///C:/Users/phili/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:60122:15)
      at checkNoChangesNodeInline (file:///C:/Users/phili/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:64178:9)
      at checkNoChangesNode (file:///C:/Users/phili/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:64144:9)
      at debugCheckNoChangesNode (file:///C:/Users/phili/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:64973:45)
      at debugCheckRenderNodeFn (file:///C:/Users/phili/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:64913:13)
      at Object.eval [as updateRenderer] (ng:///SharedModule/SideMenuComponent.ngfactory.js:703:5)
      at Object.debugUpdateRenderer [as updateRenderer] (file:///C:/Users/phili/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:64895:21)
      at checkNoChangesView (file:///C:/Users/phili/AppData/Local/Programs/uhk-agent/resources/app.asar/renderer/vendor.bundle.js:63984:14)
    ngDebugContext: 
     DebugContext_ {
       view: [Object],
       nodeIndex: 9,
       nodeDef: [Object],
       elDef: [Object],
       elView: [Object] },
    ngErrorLogger: [Function: bound ] } ]
[19:23:30.933] [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[19:23:30.933] [DeviceOperation] USB[T]: Read left module version information
[19:23:30.934] [UhkHidDevice] USB[W]: 0e 01 00 
[19:23:30.941] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 02 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[19:23:30.942] [DeviceOperation] USB[T]: Read right module version information
[19:23:30.942] [UhkHidDevice] USB[W]: 00 01 
[19:23:30.949] [UhkHidDevice] USB[R]: 00 08 00 02 00 05 00 04 00 03 00 01 00 04 00 00 00 00 00 04 00 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[19:23:30.949] Device right firmware version: 8.2.5
[19:23:30.950] Device left firmware version: 8.2.5
[19:23:32.218] New firmware version: 8.4.5
[19:23:32.219] [UhkOperations] Operating system: Windows_NT 10.0.17134 x64
[19:23:32.219] [UhkOperations] Start flashing right firmware
[19:23:32.220] [UhkHidDevice] Start reenumeration, mode: Bootloader
[19:23:32.350] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[19:23:32.350] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[19:23:33.054] [UhkHidDevice] reenumeration devices up
[19:23:33.054] [UhkHidDevice] Device communication closing.
[19:23:33.054] [UhkHidDevice] Device communication closed.
[19:23:33.054] [blhost] RUN: C:\Users\phili\AppData\Local\Programs\uhk-agent\resources\packages\blhost\win\blhost.exe --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[19:23:33.141] [blhost] STDOUT: Error: UsbHidPeripheral() cannot open USB HID device (vid=0x1d50, pid=0x6120, sn=).
[19:23:33.187] [blhost] EXIT_CODE: 1
[19:23:33.187] [blhost] FINISHED: 1
[19:23:33.188] [blhost] CLOSE_CODE: 1
[19:23:33.562] [DeviceService] updateFirmware error { message: 'blhost error code:1',
  stack: 'Error: blhost error code:1\n    at finish (C:\\Users\\phili\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\webpack:\\uhk-usb\\src\\uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (C:\\Users\\phili\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\webpack:\\uhk-usb\\src\\uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[19:23:33.568] [UhkHidDevice] Available devices:
[19:23:33.569] {"vendorId":1386,"productId":20544,"path":"\\\\?\\hid#vid_056a&pid_5040&col01#6&2b723ce4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"\t","manufacturer":"Wacom Co.,Ltd.","product":"Pen and multitouch sensor","release":4,"interface":-1,"usagePage":1,"usage":1}
[19:23:33.569] {"vendorId":1386,"productId":20544,"path":"\\\\?\\hid#vid_056a&pid_5040&col02#6&2b723ce4&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"\t","manufacturer":"Wacom Co.,Ltd.","product":"Pen and multitouch sensor","release":4,"interface":-1,"usagePage":65297,"usage":10}
[19:23:33.569] {"vendorId":1386,"productId":20544,"path":"\\\\?\\hid#vid_056a&pid_5040&col03#6&2b723ce4&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"\t","manufacturer":"Wacom Co.,Ltd.","product":"Pen and multitouch sensor","release":4,"interface":-1,"usagePage":65297,"usage":2}
[19:23:33.569] {"vendorId":1386,"productId":20544,"path":"\\\\?\\hid#vid_056a&pid_5040&col04#6&2b723ce4&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"\t","manufacturer":"Wacom Co.,Ltd.","product":"Pen and multitouch sensor","release":4,"interface":-1,"usagePage":65297,"usage":17}
[19:23:33.569] {"vendorId":1386,"productId":20544,"path":"\\\\?\\hid#vid_056a&pid_5040&col05#6&2b723ce4&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"\t","manufacturer":"Wacom Co.,Ltd.","product":"Pen and multitouch sensor","release":4,"interface":-1,"usagePage":13,"usage":2}
[19:23:33.570] {"vendorId":1386,"productId":20544,"path":"\\\\?\\hid#vid_056a&pid_5040&col06#6&2b723ce4&0&0005#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"\t","manufacturer":"Wacom Co.,Ltd.","product":"Pen and multitouch sensor","release":4,"interface":-1,"usagePage":13,"usage":4}
[19:23:33.570] {"vendorId":1386,"productId":20544,"path":"\\\\?\\hid#vid_056a&pid_5040&col07#6&2b723ce4&0&0006#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"\t","manufacturer":"Wacom Co.,Ltd.","product":"Pen and multitouch sensor","release":4,"interface":-1,"usagePage":13,"usage":14}
[19:23:33.570] {"vendorId":1386,"productId":20544,"path":"\\\\?\\hid#vid_8087&pid_0ac2#6&33c00a7a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","release":4,"interface":-1}
[19:23:33.570] {"vendorId":1386,"productId":20544,"path":"\\\\?\\hid#vid_056a&pid_5040&col08#6&2b723ce4&0&0007#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"\t","manufacturer":"Wacom Co.,Ltd.","product":"Pen and multitouch sensor","release":4,"interface":-1,"usagePage":1,"usage":6}
[19:23:33.570] {"vendorId":1386,"productId":20544,"path":"\\\\?\\hid#vid_0000&pid_0000#6&3124e721&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","release":4,"interface":-1}
[19:23:33.570] {"vendorId":1386,"productId":20544,"path":"\\\\?\\hid#vid_8087&pid_0ac2#6&210659d5&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","release":4,"interface":-1}
[19:23:33.571] {"vendorId":7504,"productId":24864,"path":"\\\\?\\hid#vid_1d50&pid_6120#6&1eccd0df&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":-1,"usagePage":65280,"usage":1}
[19:23:33.571] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (C:\Users\phili\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:92:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (C:\Users\phili\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at C:\Users\phili\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (C:\Users\phili\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:3:1)
    at UhkHidDevice.write (C:\Users\phili\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (C:\Users\phili\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:140:1)
    at Generator.next (<anonymous>)

[19:23:34.127] [DeviceService] Device connection state changed to: { bootloaderActive: true, connected: false, hasPermission: true }
blhost error code:1
`

**Comment by mondalaci** [comment]
Please give every one of your USB ports a try.

**Comment by phlpl** [comment]
Tried all ports, didn't work

**Comment by mondalaci** [comment]
I'm sorry to hear. I'm closing this issue in favor of #755. I'm afraid there's no other fix. It may take a while to get this done. In the meantime, your best shot is using another computer for updating the firmware. I'm sorry about this.
