### ISSUE TITLE
Error updating the firmware

### ISSUE THREAD

**Issue by i02sopop** [UltimateHackingKeyboard/agent#810]
WhenI try to update the firmware I get the following error message:
```Start flashing firmware
[04:18:02.405] Agent version: 1.2.11
[04:18:02.526] [UhkHidDevice] Available devices unchanged
[04:18:02.527] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"0001:0019:00","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
[04:18:02.528] [UhkHidDevice] USB[W]: 09 
[04:18:02.531] [ { Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ng-valid: true'. Current value: 'ng-valid: false'.
      at viewDebugError (file:///tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/renderer/vendor.bundle.js:59977:32)
      at expressionChangedAfterItHasBeenCheckedError (file:///tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/renderer/vendor.bundle.js:59955:12)
      at checkBindingNoChanges (file:///tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/renderer/vendor.bundle.js:60122:15)
      at checkNoChangesNodeInline (file:///tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/renderer/vendor.bundle.js:64178:9)
      at checkNoChangesNode (file:///tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/renderer/vendor.bundle.js:64144:9)
      at debugCheckNoChangesNode (file:///tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/renderer/vendor.bundle.js:64973:45)
      at debugCheckRenderNodeFn (file:///tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/renderer/vendor.bundle.js:64913:13)
      at Object.eval [as updateRenderer] (ng:///SharedModule/SideMenuComponent.ngfactory.js:703:5)
      at Object.debugUpdateRenderer [as updateRenderer] (file:///tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/renderer/vendor.bundle.js:64895:21)
      at checkNoChangesView (file:///tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/renderer/vendor.bundle.js:63984:14)
    ngDebugContext: 
     DebugContext_ {
       view: [Object],
       nodeIndex: 9,
       nodeDef: [Object],
       elDef: [Object],
       elView: [Object] },
    ngErrorLogger: [Function: bound ] } ]
[04:18:02.549] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[04:18:02.550] [DeviceOperation] USB[T]: Read left module version information
[04:18:02.550] [UhkHidDevice] USB[W]: 0e 01 00 
[04:18:02.559] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 02 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[04:18:02.560] [DeviceOperation] USB[T]: Read right module version information
[04:18:02.560] [UhkHidDevice] USB[W]: 00 01 
[04:18:02.570] [UhkHidDevice] USB[R]: 00 08 00 02 00 05 00 04 00 03 00 01 00 04 00 00 00 00 00 04 00 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[04:18:02.571] Device right firmware version: 8.2.5
[04:18:02.571] Device left firmware version: 8.2.5
[04:18:02.845] New firmware version: 8.5.2
[04:18:02.846] [UhkOperations] Operating system: Linux 4.18.0-1-amd64 x64
[04:18:02.846] [UhkOperations] Start flashing right firmware
[04:18:02.847] [UhkHidDevice] Start reenumeration, mode: Bootloader
[04:18:03.073] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[04:18:03.073] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[04:18:04.160] [UhkHidDevice] reenumeration devices up
[04:18:04.161] [UhkHidDevice] Device communication closing.
[04:18:04.161] [UhkHidDevice] Device communication closed.
[04:18:04.163] [blhost] RUN: /tmp/.mount_uhk-ag9OVTlE/app/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[04:18:04.218] [blhost] STDOUT: Error: UsbHidPeripheral() cannot open USB HID device (vid=0x1d50, pid=0x6120, sn=).
[04:18:04.222] [blhost] EXIT_CODE: 1
[04:18:04.223] [blhost] FINISHED: 1
[04:18:04.654] [DeviceService] updateFirmware error { message: 'blhost error code:1',
  stack: 'Error: blhost error code:1\n    at finish (/tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[04:18:04.701] [UhkHidDevice] Available devices:
[04:18:04.702] {"vendorId":7504,"productId":24864,"path":"0001:001a:00","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":0}
[04:18:04.702] {"vendorId":4164,"productId":31235,"path":"0005:0004:00","product":"Osmium Interface","release":0,"interface":0}
[04:18:04.702] {"vendorId":4164,"productId":31235,"path":"0005:0004:01","product":"Osmium Interface","release":0,"interface":1}
[04:18:04.703] {"vendorId":4164,"productId":31235,"path":"0005:0004:02","product":"Osmium Interface","release":0,"interface":2}
[04:18:04.703] {"vendorId":1637,"productId":24576,"path":"0005:0003:00","release":137,"interface":0}
[04:18:04.703] {"vendorId":1637,"productId":24576,"path":"0005:0003:01","release":137,"interface":1}
[04:18:04.703] {"vendorId":1637,"productId":24576,"path":"0005:0003:02","release":137,"interface":2}
[04:18:04.704] {"vendorId":1149,"productId":8264,"path":"0001:0003:00","manufacturer":"Primax","product":"Kensington Eagle Trackball","release":1536,"interface":0}
[04:18:04.705] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:92:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at /tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (/tmp/.mount_uhk-ag9OVTlE/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:140:1)
    at Generator.next (<anonymous>)

[04:18:04.708] [blhost] CLOSE_CODE: 1
[04:18:05.283] [DeviceService] Device connection state changed to: { bootloaderActive: true, connected: false, hasPermission: true }
blhost error code:1```
I am in a Debian environment and I have the required packages installed. Everything else works well except the firmware update.

**Comment by mondalaci** [comment]
Do you have tmpfs mounted with noexec? If so, remount as executable and let me know.

**Comment by i02sopop** [comment]
Not in `/tmp`, this is the list of tmpfs I have mounted:
```udev on /dev type devtmpfs (rw,nosuid,relatime,size=16419340k,nr_inodes=4104835,mode=755)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=3295188k,mode=755)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (rw,mode=755)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,relatime,size=8388608k)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=3295184k,mode=700,uid=1000,gid=1000)

**Comment by i02sopop** [comment]
In the terminal I can also see this error:
```
[13:38:07.188] [error] [ { TypeError: Cannot read property 'leftModuleInfo' of undefined
      at Object.eval [as updateRenderer] (ng:///SharedModule/DeviceFirmwareComponent.ngfactory.js:151:44)
      at Object.debugUpdateRenderer [as updateRenderer] (file:///tmp/.mount_uhk-agGR3WVJ/app/resources/app.asar/renderer/vendor.bundle.js:64895:21)
      at checkAndUpdateView (file:///tmp/.mount_uhk-agGR3WVJ/app/resources/app.asar/renderer/vendor.bundle.js:64009:14)
      at callViewAction (file:///tmp/.mount_uhk-agGR3WVJ/app/resources/app.asar/renderer/vendor.bundle.js:64355:21)
      at execComponentViewsAction (file:///tmp/.mount_uhk-agGR3WVJ/app/resources/app.asar/renderer/vendor.bundle.js:64287:13)
      at checkAndUpdateView (file:///tmp/.mount_uhk-agGR3WVJ/app/resources/app.asar/renderer/vendor.bundle.js:64010:5)
      at callViewAction (file:///tmp/.mount_uhk-agGR3WVJ/app/resources/app.asar/renderer/vendor.bundle.js:64355:21)
      at execEmbeddedViewsAction (file:///tmp/.mount_uhk-agGR3WVJ/app/resources/app.asar/renderer/vendor.bundle.js:64313:17)
      at checkAndUpdateView (file:///tmp/.mount_uhk-agGR3WVJ/app/resources/app.asar/renderer/vendor.bundle.js:64005:5)
      at callViewAction (file:///tmp/.mount_uhk-agGR3WVJ/app/resources/app.asar/renderer/vendor.bundle.js:64355:21)
    ngDebugContext: 
     DebugContext_ {
       view: [Object],
       nodeIndex: 15,
       nodeDef: [Object],
       elDef: [Object],
       elView: [Object] },
    ngErrorLogger: [Function: bound ] } ]

**Comment by mondalaci** [comment]
It seems like the blhost firmware update utility can't access the bootloader. I'm wondering whether udev rules were set up correctly. Please `cat /etc/udev/rules.d/50-uhk60.rules`

**Comment by i02sopop** [comment]
I don't have the udev rules :disappointed: Where should I see what rules I need to put in udev?

**Comment by i02sopop** [comment]
Ok, I've already seen it at https://github.com/UltimateHackingKeyboard/agent/blob/master/rules/50-uhk60.rules, and with those rules I have been able to update the firmware, thank you very much :).

**Comment by mondalaci** [comment]
I'm glad it works for you, but something is very strange on your end. When Agent first runs, it should ask you to escalate privileges. Did it work? Did you do it manually? You must have set up something if Agent connected to your UHK at all.

I want to get to the bottom of this because I wouldn't like to receive such reports in the future, but rather solve the root cause.

**Comment by i02sopop** [comment]
No, it didn't ask to escalate privileges, it just asked for integration of the agent into the system (icons and stuff like that), but I run the agent from the terminal and I run xmonad, so it's not the most standart X environment :sweat_smile:

**Comment by mondalaci** [comment]
Oh geez, ok. Well, I'm glad it's now working for you. :)
