### ISSUE TITLE
Dell XPS 15 9560 (07BE)

### ISSUE THREAD

**Issue by dklann** [UltimateHackingKeyboard/agent#866]
Consistently reproducible: attempting to flash firmware version 8.5.3 bundled with UHK Agent version 1.2.12 fails. Log attached.
I removed all other USB devices, restarted the computer, and made the attempt several times. Failed every time until I ran the Agent as root (with sudo). Successfully updated as root.

Update (copied from the agent):
Start flashing firmware
[08:08:32.362] Agent version: 1.2.12
[08:08:32.375] [UhkHidDevice] Available devices unchanged
[08:08:32.431] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"/dev/hidraw0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
[08:08:32.432] [UhkHidDevice] USB[W]: 09 
[08:08:32.438] [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[08:08:32.439] [DeviceOperation] USB[T]: Read left module version information
[08:08:32.440] [UhkHidDevice] USB[W]: 0e 01 00 
[08:08:32.446] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 04 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[08:08:32.447] [DeviceOperation] USB[T]: Read right module version information
[08:08:32.448] [UhkHidDevice] USB[W]: 00 01 
[08:08:32.454] [UhkHidDevice] USB[R]: 00 08 00 04 00 05 00 04 00 04 00 00 00 04 00 00 00 00 00 04 00 01 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[08:08:32.455] Device right firmware version: 8.4.5
[08:08:32.456] Device left firmware version: 8.4.5
[08:08:32.461] New firmware version: 8.5.3
[08:08:32.463] [UhkOperations] Operating system: Linux 4.19.2-arch1-1-ARCH x64
[08:08:32.464] [UhkOperations] Start flashing right firmware
[08:08:32.466] [UhkHidDevice] Start reenumeration, mode: Bootloader
[08:08:32.576] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[08:08:32.577] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[08:08:33.211] [UhkHidDevice] reenumeration devices up
[08:08:33.211] [UhkHidDevice] Device communication closing.
[08:08:33.212] [UhkHidDevice] Device communication closed.
[08:08:33.214] [blhost] RUN: /tmp/.mount_UHK.AgbJQR8P/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[08:08:33.298] [blhost] STDOUT: Error: UsbHidPeripheral() cannot open USB HID device (vid=0x1d50, pid=0x6120, sn=).
[08:08:33.303] [blhost] EXIT_CODE: 1
[08:08:33.304] [blhost] FINISHED: 1
[08:08:33.305] [blhost] CLOSE_CODE: 1
[08:08:33.308] [DeviceService] updateFirmware error { message: 'blhost error code:1',
  stack: 'Error: blhost error code:1\n    at finish (/tmp/.mount_UHK.AgbJQR8P/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/tmp/.mount_UHK.AgbJQR8P/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[08:08:33.312] [UhkHidDevice] Available devices:
[08:08:33.312] {"vendorId":7504,"productId":24864,"path":"/dev/hidraw0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":0,"usagePage":24943,"usage":25714}
[08:08:33.314] {"vendorId":1267,"productId":9377,"path":"/dev/hidraw5","serialNumber":"","manufacturer":"ELAN","product":"Touchscreen","release":4369,"interface":0}
[08:08:33.316] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/tmp/.mount_UHK.AgbJQR8P/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:107:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgbJQR8P/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:104:1)
    at Generator.next (<anonymous>)
    at /tmp/.mount_UHK.AgbJQR8P/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/tmp/.mount_UHK.AgbJQR8P/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/tmp/.mount_UHK.AgbJQR8P/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:103:1)
    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgbJQR8P/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:155:1)
    at Generator.next (<anonymous>)
    at /tmp/.mount_UHK.AgbJQR8P/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/tmp/.mount_UHK.AgbJQR8P/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.waitUntilKeyboardBusy (/tmp/.mount_UHK.AgbJQR8P/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:153:1)
    at DeviceService.<anonymous> (/tmp/.mount_UHK.AgbJQR8P/resources/app.asar/webpack:/src/services/device.service.ts:140:31)
    at Generator.next (<anonymous>)

blhost error code:1

**Comment by mondalaci** [comment]
Please include the output of `cat /etc/udev/rules.d/50-uhk60.rules`

**Comment by dklann** [comment]
Ahhh.... I see now.

    # Ultimate Hacking Keyboard rules
    # These are the udev rules for accessing the USB interfaces of the UHK as non-root users.
    # Copy this file to /etc/udev/rules.d and physically reconnect the UHK afterwards.
    SUBSYSTEM=="input", GROUP="input", MODE="0666"
    SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", MODE:="0666", GROUP="plugdev"
    KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", MODE="0666", GROUP="plugdev"

The group `plugdev` was missing on my system. I have since added group `plugdev` and added my username to the group. I am away from my office for a few more days, so I will be unable to check this until a few more days from now. I will report back then.

Thank you!

**Comment by mondalaci** [comment]
Thanks for the follow up! Which Linux distro and version?

**Comment by dklann** [comment]
Linux distro: Arch, current. I tried again (as a member of the Linux group `plugdev`) and the firmware update failed with the following log:

    Start flashing firmware
    [16:53:56.100] Agent version: 1.2.12
    [16:53:56.104] [UhkHidDevice] Available devices unchanged
    [16:53:56.158] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
    [16:53:56.159] [UhkHidDevice] USB[W]: 09 
    [16:53:56.166] [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
    [16:53:56.166] [DeviceOperation] USB[T]: Read left module version information
    [16:53:56.166] [UhkHidDevice] USB[W]: 0e 01 00 
    [16:53:56.174] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 05 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
    [16:53:56.174] [DeviceOperation] USB[T]: Read right module version information
    [16:53:56.174] [UhkHidDevice] USB[W]: 00 01 
    [16:53:56.182] [UhkHidDevice] USB[R]: 00 08 00 05 00 03 00 04 00 05 00 00 00 04 00 00 00 00 00 04 00 01 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
    [16:53:56.182] Device right firmware version: 8.5.3
    [16:53:56.182] Device left firmware version: 8.5.3
    [16:53:56.184] New firmware version: 8.5.3
    [16:53:56.185] [UhkOperations] Operating system: Linux 4.19.2-arch1-1-ARCH x64
    [16:53:56.185] [UhkOperations] Start flashing right firmware
    [16:53:56.186] [UhkHidDevice] Start reenumeration, mode: Bootloader
    [16:53:56.290] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
    [16:53:56.291] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
    [16:53:56.989] [UhkHidDevice] reenumeration devices up
    [16:53:56.990] [UhkHidDevice] Device communication closing.
    [16:53:56.990] [UhkHidDevice] Device communication closed.
    [16:53:56.991] [blhost] RUN: /tmp/.mount_UHK.AgIkYozd/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
    [16:53:57.021] [blhost] STDOUT: Error: UsbHidPeripheral() cannot open USB HID device (vid=0x1d50, pid=0x6120, sn=).
    [16:53:57.023] [blhost] EXIT_CODE: 1
    [16:53:57.023] [blhost] FINISHED: 1
    [16:53:57.024] [DeviceService] updateFirmware error { message: 'blhost error code:1', stack: 'Error: blhost error code:1\n    at finish (/tmp/.mount_UHK.AgIkYozd/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/tmp/.mount_UHK.AgIkYozd/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
    [16:53:57.028] [UhkHidDevice] Available devices:
    [16:53:57.028] {"vendorId":7504,"productId":24864,"path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":0}
    [16:53:57.028] {"vendorId":1267,"productId":9377,"path":"/dev/hidraw6","serialNumber":"","manufacturer":"ELAN","product":"Touchscreen","release":4369,"interface":0}
    [16:53:57.029] {"vendorId":1118,"productId":1907,"path":"/dev/hidraw7","serialNumber":"","manufacturer":"Microsoft","product":"Microsoft� Nano Transceiver v1.0","release":1636,"interface":0}
    [16:53:57.029] {"vendorId":1118,"productId":1907,"path":"/dev/hidraw8","serialNumber":"","manufacturer":"Microsoft","product":"Microsoft� Nano Transceiver v1.0","release":1636,"interface":1}
    [16:53:57.029] {"vendorId":1118,"productId":1907,"path":"/dev/hidraw9","serialNumber":"","manufacturer":"Microsoft","product":"Microsoft� Nano Transceiver v1.0","release":1636,"interface":2}
    [16:53:57.029] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/tmp/.mount_UHK.AgIkYozd/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:107:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgIkYozd/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:104:1)
    at Generator.next (<anonymous>)
    at /tmp/.mount_UHK.AgIkYozd/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/tmp/.mount_UHK.AgIkYozd/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/tmp/.mount_UHK.AgIkYozd/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:103:1)
    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgIkYozd/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:155:1)
    at Generator.next (<anonymous>)
    at /tmp/.mount_UHK.AgIkYozd/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/tmp/.mount_UHK.AgIkYozd/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.waitUntilKeyboardBusy (/tmp/.mount_UHK.AgIkYozd/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:153:1)
    at DeviceService.<anonymous> (/tmp/.mount_UHK.AgIkYozd/resources/app.asar/webpack:/src/services/device.service.ts:140:31)
    at Generator.next (<anonymous>)
    [16:53:57.031] [blhost] CLOSE_CODE: 1
    blhost error code:1

**Comment by mondalaci** [comment]
Please create a file that can only be accessed by the plugdev group, and check if you as a user can read/write it.
