### ISSUE TITLE
Error upgrading firmware 8.2.5 to 8.5.3 using Agent 1.2.12 on windows 10

### ISSUE THREAD

**Issue by vanife** [UltimateHackingKeyboard/agent#868]
Using both 8.5.3 bundled with Agent, and also from the firmware page - same result.

Here is the log:
```

Start flashing firmware
[20:16:20.982] Agent version: 1.2.12
[20:16:21.003] [UhkHidDevice] Available devices unchanged
[20:16:21.003] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#9&1294f385&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":65280,"usage":1}
[20:16:21.004] [UhkHidDevice] USB[W]: 09 
[20:16:21.010] [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[20:16:21.011] [DeviceOperation] USB[T]: Read left module version information
[20:16:21.011] [UhkHidDevice] USB[W]: 0e 01 00 
[20:16:21.019] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 02 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[20:16:21.021] [DeviceOperation] USB[T]: Read right module version information
[20:16:21.021] [UhkHidDevice] USB[W]: 00 01 
[20:16:21.031] [UhkHidDevice] USB[R]: 00 08 00 02 00 05 00 04 00 03 00 01 00 04 00 00 00 00 00 04 00 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[20:16:21.032] Device right firmware version: 8.2.5
[20:16:21.032] Device left firmware version: 8.2.5
[20:16:21.034] New firmware version: 8.5.3
[20:16:21.034] [UhkOperations] Operating system: Windows_NT 10.0.17134 x64
[20:16:21.034] [UhkOperations] Start flashing right firmware
[20:16:21.034] [UhkHidDevice] Start reenumeration, mode: Bootloader
[20:16:21.150] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[20:16:21.150] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[20:16:21.150] [DeviceService] updateFirmware error { message: 'Cannot write to HID device',
  stack: 'Error: Cannot write to HID device\n    at UhkHidDevice.<anonymous> (C:\\Users\\ivan.melnychuk\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\webpack:\\uhk-usb\\dist\\src\\uhk-hid-device.js:199:1)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\ivan.melnychuk\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\webpack:\\uhk-usb\\dist\\src\\uhk-hid-device.js:4:42)\n    at <anonymous>' }
[20:16:21.151] [UhkHidDevice] USB[W]: 09 
[20:16:21.155] [DeviceService] Read hardware modules information failed Error: Cannot write to HID device
    at Promise (C:\Users\ivan.melnychuk\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:124:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (C:\Users\ivan.melnychuk\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:104:1)
    at Generator.next (<anonymous>)
    at C:\Users\ivan.melnychuk\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (C:\Users\ivan.melnychuk\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:3:1)
    at UhkHidDevice.write (C:\Users\ivan.melnychuk\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:103:1)
    at UhkHidDevice.<anonymous> (C:\Users\ivan.melnychuk\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:155:1)
    at Generator.next (<anonymous>)

[20:16:21.157] [UhkHidDevice] Transfer error:  Error: could not read from HID device

[20:16:21.157] [UhkHidDevice] Device communication closing.
[20:16:21.158] [UhkHidDevice] Device communication closed.
Cannot write to HID device

```

**Comment by mondalaci** [comment]
Are you using a USB hub or docking station? Please try to connect your UHK directly to your USB port. If still doesn't work, disconnect other USB devices, and try every USB port of your computer.

If it doesn't work then please state your hardware specs.

**Comment by mondalaci** [comment]
You shouldn't need to run Agent as admin. Waiting for your update!

**Comment by vanife** [comment]
Even after computer restart (and without any other devices connected) I had the same error when trying to update the firmware on my Microsoft Surface Book 2.
But then i swiched to one desktop computer (also Windows 10) and updating firmware worked from the first time.
Therefore, closing the issue due to this workaround, although not really solved.

**Comment by mondalaci** [comment]
Surface Book 2 is known to be problematic when it comes to firmware updates. #755 will hopefully resolve this issue.
