### ISSUE TITLE
Failed to flash new firmware

### ISSUE THREAD

**Issue by dison77** [UltimateHackingKeyboard/agent#880]
Attempting to flash firmware 8.5.3 onto my new keyboard running version 8.2.5 fails on Windows 10.

Start flashing firmware
[12:26:58.083] Agent version: 1.2.12
[12:26:58.141] [UhkHidDevice] Available devices unchanged
[12:26:58.142] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#8&220024a3&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":65280,"usage":1}
[12:26:58.142] [UhkHidDevice] USB[W]: 09
[12:26:58.202] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[12:26:58.202] [DeviceOperation] USB[T]: Read left module version information
[12:26:58.202] [UhkHidDevice] USB[W]: 0e 01 00
[12:26:58.208] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 02 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[12:26:58.209] [DeviceOperation] USB[T]: Read right module version information
[12:26:58.209] [UhkHidDevice] USB[W]: 00 01
[12:26:58.216] [UhkHidDevice] USB[R]: 00 08 00 02 00 05 00 04 00 03 00 01 00 04 00 00 00 00 00 04 00 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[12:26:58.217] Device right firmware version: 8.2.5
[12:26:58.217] Device left firmware version: 8.2.5
[12:26:58.217] New firmware version: 8.5.3
[12:26:58.217] [UhkOperations] Operating system: Windows_NT 10.0.16299 x64
[12:26:58.218] [UhkOperations] Start flashing right firmware
[12:26:58.218] [UhkHidDevice] Start reenumeration, mode: Bootloader
[12:26:58.388] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[12:26:58.388] [UhkHidDevice] USB[W]: 01 00 88 13 00 00
[12:26:58.388] [DeviceService] updateFirmware error { message: 'Cannot write to HID device', stack: 'Error: Cannot write to HID device\n at UhkHidDevice.<anonymous> (C:\\Users\\mbreindel\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\webpack:\\uhk-usb\\dist\\src\\uhk-hid-device.js:199:1)\n at Generator.next (<anonymous>)\n at fulfilled (C:\\Users\\mbreindel\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\webpack:\\uhk-usb\\dist\\src\\uhk-hid-device.js:4:42)\n at <anonymous>' }
[12:26:58.388] [UhkHidDevice] USB[W]: 09
[12:26:58.388] [DeviceService] Read hardware modules information failed Error: Cannot write to HID device at Promise (C:\Users\mbreindel\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:124:1) at Promise (<anonymous>) at UhkHidDevice.<anonymous> (C:\Users\mbreindel\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:104:1) at Generator.next (<anonymous>) at C:\Users\mbreindel\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:7:1 at Promise (<anonymous>) at __awaiter (C:\Users\mbreindel\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:3:1) at UhkHidDevice.write (C:\Users\mbreindel\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:103:1) at UhkHidDevice.<anonymous> (C:\Users\mbreindel\AppData\Local\Programs\uhk-agent\resources\app.asar\webpack:\uhk-usb\dist\src\uhk-hid-device.js:155:1) at Generator.next (<anonymous>)
[12:26:58.388] [UhkHidDevice] Transfer error: Error: could not read from HID device
[12:26:58.388] [UhkHidDevice] Device communication closing.
[12:26:58.388] [UhkHidDevice] Device communication closed.
Cannot write to HID device

**Comment by mondalaci** [comment]
Please try to directly connect your UHK to your computer instead of using a USB hub or docking station and retry.

**Comment by dison77** [comment]
It was connected directly, but switching to another port solved the problem.

Thanks,
Matt

**Comment by mondalaci** [comment]
Well done!
