### ISSUE TITLE
Can't flash 8.5.3 firmware

### ISSUE THREAD

**Issue by tvansteenburgh** [UltimateHackingKeyboard/agent#955]
I have nothing plugged into my laptop except the UHK. Downloaded agent 1.2.12 and am attempting to update to firmware 8.5.3 from the Firmware screen in the agent. Here's the firmware update log:

```
Start flashing firmware
[09:34:51.778] Agent version: 1.2.12
[09:34:51.791] [UhkHidDevice] Available devices unchanged
[09:34:51.852] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"/dev/hidraw2","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":26995,"usage":28271}
[09:34:51.853] [UhkHidDevice] USB[W]: 09
[09:34:51.859] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[09:34:51.860] [DeviceOperation] USB[T]: Read left module version information
[09:34:51.862] [UhkHidDevice] USB[W]: 0e 01 00
[09:34:51.869] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 04 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[09:34:51.872] [DeviceOperation] USB[T]: Read right module version information
[09:34:51.873] [UhkHidDevice] USB[W]: 00 01
[09:34:51.883] [UhkHidDevice] USB[R]: 00 08 00 04 00 05 00 04 00 04 00 00 00 04 00 00 00 00 00 04 00 01 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[09:34:51.888] Device right firmware version: 8.4.5
[09:34:51.889] Device left firmware version: 8.4.5
[09:34:51.901] New firmware version: 8.5.3
[09:34:51.912] [UhkOperations] Operating system: Linux 4.15.0-50-generic x64
[09:34:51.913] [UhkOperations] Start flashing right firmware
[09:34:51.920] [UhkHidDevice] Start reenumeration, mode: Bootloader
[09:34:52.062] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[09:34:52.063] [UhkHidDevice] USB[W]: 01 00 88 13 00 00
[09:34:52.843] [UhkHidDevice] reenumeration devices up
[09:34:52.843] [UhkHidDevice] Device communication closing.
[09:34:52.843] [UhkHidDevice] Device communication closed.
[09:34:52.845] [blhost] RUN: /tmp/.mount_UHK.AgNMvBLQ/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[09:34:52.990] [blhost] STDOUT: Error: UsbHidPeripheral() cannot open USB HID device (vid=0x1d50, pid=0x6120, sn=).
[09:34:53.009] [blhost] EXIT_CODE: 1
[09:34:53.018] [blhost] FINISHED: 1
[09:34:53.023] [DeviceService] updateFirmware error { message: 'blhost error code:1', stack: 'Error: blhost error code:1\n at finish (/tmp/.mount_UHK.AgNMvBLQ/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n at ChildProcess.childProcess.on.code (/tmp/.mount_UHK.AgNMvBLQ/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n at emitTwo (events.js:125:13)\n at ChildProcess.emit (events.js:213:7)\n at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[09:34:53.032] [UhkHidDevice] Available devices:
[09:34:53.033] {"vendorId":7504,"productId":24864,"path":"/dev/hidraw2","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":0,"usagePage":14898,"usage":11825}
[09:34:53.034] {"vendorId":1267,"productId":8400,"path":"/dev/hidraw0","serialNumber":"","manufacturer":"ELAN","product":"Touchscreen","release":4370,"interface":0,"usagePage":14900,"usage":11825}
[09:34:53.038] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected at Promise (/tmp/.mount_UHK.AgNMvBLQ/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:107:1) at Promise (<anonymous>) at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgNMvBLQ/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:104:1) at Generator.next (<anonymous>) at /tmp/.mount_UHK.AgNMvBLQ/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1 at Promise (<anonymous>) at __awaiter (/tmp/.mount_UHK.AgNMvBLQ/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1) at UhkHidDevice.write (/tmp/.mount_UHK.AgNMvBLQ/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:103:1) at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgNMvBLQ/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:155:1) at Generator.next (<anonymous>) at /tmp/.mount_UHK.AgNMvBLQ/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1 at Promise (<anonymous>) at __awaiter (/tmp/.mount_UHK.AgNMvBLQ/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1) at UhkHidDevice.waitUntilKeyboardBusy (/tmp/.mount_UHK.AgNMvBLQ/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:153:1) at DeviceService.<anonymous> (/tmp/.mount_UHK.AgNMvBLQ/resources/app.asar/webpack:/src/services/device.service.ts:140:31) at Generator.next (<anonymous>)
[09:34:53.046] [blhost] CLOSE_CODE: 1
blhost error code:1
```

**Comment by mondalaci** [comment]
This is a permission related issue which shouldn't happen if you let Agent set up udev permissions. Did you?

**Comment by tvansteenburgh** [comment]
Ah, thanks for the hint, running the agent with sudo resolved it.
